### PR TITLE
Update charts to 1.3.0 release

### PR DESCRIPTION
**Pull request by ChandanSagar**
- Updated README
- Updated chart versioin 1.3.0
- Updated values.yaml
- Updated clusterrole.yaml

Signed-off-by: ChandanSagar <chandan.pradhan@mayadata.io>

### CODE REVIEW

**Comment by ChandanSagar** [comment]
@guangbochen : Please take a look, thanks.

**Comment by guangbochen** [comment]
Can we change `latest` folder name to a specific version like `v1.3.0` instead, thanks.

We are changing the folder naming standard and for future PR you can do:
```
1. base copy old version to the new version folder
2. bump chart version and commit changes
```

**Comment by ChandanSagar** [comment]
Thanks for the review. Renamed the folder.  PTAL.

**Comment by guangbochen** [comment]
LGTM. @deniseschannon

**Pull request merged**
