### PR TITLE
[release-v2.6] Charts release for Rancher v2.6.11

### PR DESCRIPTION
**Pull request by stormqueen1990**
### Checkpoint 0: Validate `release.yaml`

Validation steps:
- [x] Each chart version in `release.yaml` DOES NOT modify an already released chart. If so, stop and modify the versions so that it releases a net-new chart.
- [x] Each chart version in `release.yaml` IS exactly 1 more minor version OR 1 more patch version than the last released chart version. If not, stop and modify the versions so that it releases a net-new chart.

### Checkpoint 1: Compare contents of assets/ to charts/

Validation steps:
- [x] Running `make unzip` to regenerate the `charts/` from scratch, then `git diff` to check differences between `assets/` and `charts/` yields NO differences or innocuous differences.

IMPORTANT: Do not undo these changes for future steps since we want to keep the charts/ that match the current contents of assets!

### Checkpoint 2: Compare assets against index.yaml

Validation steps:
- [x] The `index.yaml` file has an entry for each chart version.
- [x] The `index.yaml` entries for each chart matches the `Chart.yaml` for each chart.
- [x] Each chart has ALL required annotations
  - kube-version annotation
  - rancher-version annotation
  - permits-os annotation (indicates Windows and/or Linux)

### Checkpoint 3: Logical Checks

Validation steps (requires manual inspection of differences between previous and latest chart version):
- [x] Ensure no RC images are included.
- [x] Ensure all mirrored images include the right prefix.
- [x] Ensure any new images have `repository` and `tag` on the same level to ensure the rancher-images.txt is generated correctly for it for airgap scenarios.

### CODE REVIEW

**Comment by stormqueen1990** [comment]
While running through the checklist, I noticed the following bits:
* The `sriov` chart seems to not be using the `image.repository` pattern: https://github.com/rancher/charts/blob/4fec49eacad7f2828e79918b2cbf00faa67dc67c/charts/sriov/100.0.5%2Bup0.1.0/values.yaml#L30-L51
I saw the previous release was similar, so I'm assuming this is not an issue.

* The `epinio` chart has this annotation pointing to ghcr.io/dexidp: https://github.com/rancher/charts/blob/4fec49eacad7f2828e79918b2cbf00faa67dc67c/charts/epinio/100.0.5%2Bup1.6.2/charts/dex/Chart.yaml#L5-L7
I believe this is also not an issue because I see the mirrored image elsewhere:
https://github.com/rancher/charts/blob/4fec49eacad7f2828e79918b2cbf00faa67dc67c/charts/epinio/100.0.5%2Bup1.6.2/charts/dex/values.yaml#L8-L11

**Comment by stormqueen1990** [comment]
As specified in `release.yaml`, the `sriov` and `sriov-crd` charts are releasing two versions with Rancher v2.6.11:
https://github.com/rancher/charts/blob/c11a7898bcb38b71d361e0b7e43b5d75ddac564e/release.yaml#L54-L59

**Review by prachidamle — APPROVED** [review]
LGTM

**Comment by pennyscissors** [comment]
> As specified in `release.yaml`, the `sriov` and `sriov-crd` charts are releasing two versions with Rancher v2.6.11:
> 
> https://github.com/rancher/charts/blob/c11a7898bcb38b71d361e0b7e43b5d75ddac564e/release.yaml#L54-L59

~Is this intentional? We don't commonly release 2 versions of the same chart in a Rancher release.~ This was cleared up offline, they are assumed to be intentional

**Review by pennyscissors — APPROVED** [review]

**Pull request merged**
