### PR TITLE
updated the px image to 2.7.1 version

### PR DESCRIPTION
**Pull request by trierra**

### CODE REVIEW

**Review by harsh-px — APPROVED** [review]

**Comment by trierra** [comment]
@PennyScissors the PR is failing because of one of the unreachables repos in other projects. Can you please help to merge this? 
`
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
--
44 | Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
45 | Error linting charts`

**Comment by harsh-px** [comment]
Ping @PennyScissors on the PR question above.

**Comment by harsh-px** [comment]
https://github.com/rancher/charts/pull/1236 supersedes this. This PR can be closed.

**Comment by PennyScissors** [comment]
Closing in favor of https://github.com/rancher/charts/pull/1236

**Pull request closed without merging**
