### PR TITLE
Bump System Upgrade Controller Major Version for 1.25

### PR DESCRIPTION
**Pull request by HarrisonWAffel**
## Issue: https://github.com/rancher/rancher/issues/40464

This PR bumps the major version for the system-upgrade-controller. It also removes the unreleased version `v101.1.0+up0.4.0` in favor of this new major version `v102.0.0+up0.4.0`. This commit for SUC hasn't been changed, so `v102.0.0` matches the contents of `v101.1.0`.

### CODE REVIEW

**Review by snasovich — APPROVED** [review]

**Review by snasovich — CHANGES_REQUESTED** [review]
Actually @HarrisonWAffel , please update `release.yaml` too

**Comment by HarrisonWAffel** [comment]
Ah, good point. Updated in latest commit

**Review by snasovich — APPROVED** [review]
LGTM, let's see if CI succeeds now

**Review by a-blender — APPROVED** [review]
CI is passing. LGTM to me with the release.yaml update

**Pull request merged**
