### PR TITLE
[openebs] update charts to latest 0.8.2 release

### PR DESCRIPTION
**Pull request by prateekpandey14**
- Updated README
  - Updated chart version
  - Updated values.yaml
  - Updated questions.yaml

Signed-off-by: prateekpandey14 <prateek.pandey@openebs.io>

### CODE REVIEW

**Comment by prateekpandey14** [comment]
@guangbochen continous-integration is failing due to some linting errors in portworx charts.. PTAL

**Comment by guangbochen** [comment]
sure thanks for the update, and LGTM of your chart.

**Comment by deniseschannon** [comment]
@prateekpandey14 Can we fix the lint errors so the CI passes?

**Comment by muratkars** [comment]
Should we also move the chart under charts/charts instead of charts/proposed @guangbochen ? 
cc @prateekpandey14

**Comment by guangbochen** [comment]
yes, you can move it to the charts/ directory, but in the catalog UI it will be the same. @muratkars @prateekpandey14

**Comment by guangbochen** [comment]
@prateekpandey14 can u rebase to the latest `dev` to address the CI failure, thanks.

**Comment by prateekpandey14** [comment]
@guangbochen done, rebased and also moved the chart under charts/charts. thanks

**Comment by guangbochen** [comment]
LGTM

**Pull request merged**
