### PR TITLE
[dev-v2.7] bump observability chart versions for release 2.7.13

### PR DESCRIPTION
**Pull request by alexandreLamarre**
## Problem

To address some release versioning issues, working versions of the observability charts will follow rc releases

## Testing

N/A

## Backporting considerations
N/A

### CODE REVIEW

**Review by joshmeranda — APPROVED** [review]

**Comment by adamkpickering** [comment]
Hi @alexandreLamarre, I am having a hard time understanding the purpose of this PR. Can you please link to any issues that explain the context? Or explain further? Thanks!

**Comment by alexandreLamarre** [comment]
@adamkpickering I am bumping the versions in a separate PR as multiple PRs need to fit changes into new versions. Among them:
- Patches that were slated for 2.7.12
- Patches that were reverted in dev-v2.7 during the fast forward from 2.7.11 due to a versioning issue on our end

**Review by adamkpickering — APPROVED** [review]

**Review by nicholasSUSE — COMMENTED** [review]
I am confused, this PR is bumping the same version on the same Chart:
https://github.com/rancher/charts/pull/3608/commits/58ebcc4f1841b3d104ab88613faf20419f2edf94

**Comment by nicholasSUSE** [comment]
> I am confused, this PR is bumping the same version on the same Chart: [58ebcc4](https://github.com/rancher/charts/commit/58ebcc4f1841b3d104ab88613faf20419f2edf94)

@alexandreLamarre

**Comment by lucasmlp** [comment]
@alexandreLamarre I've fixed the `index.yaml` issues in `dev-v2.7` in this [PR](https://github.com/rancher/charts/pull/3613). You should be fine after rebasing your branch with `upstream/dev-v2.7`.
Try to modify only one chart per PR, please. It makes it hard for us to revert only one chart's work when it was merged with another in case something goes wrong.

**Review by joshmeranda — APPROVED** [review]

**Pull request merged**
