### PR TITLE
Added artifactory-ha chart version 0.12.16

### PR DESCRIPTION
**Pull request by jainishshah17**

### CODE REVIEW

**Comment by jainishshah17** [comment]
@guangbochen Can you help me with this CI failure?

**Comment by guangbochen** [comment]
Hi @jainishshah17, the CI lint fail has been fixed, can u rebase to the latest `dev`, thanks

**Comment by ankushchadha** [comment]
@guangbochen - can you help? We need to get going on this.

**Comment by guangbochen** [comment]
sure, we have re-synced the `dev` branch to address the CI failing, @jainishshah17 can u please help to rebase your PR, I will review and merge it after that, thanks.

**Comment by jainishshah17** [comment]
@guangbochen Done

**Comment by guangbochen** [comment]
@jainishshah17 can you please rebase instead of merging the upstream `dev` branch, thanks

**Comment by jainishshah17** [comment]
@guangbochen Ok

**Comment by guangbochen** [comment]
the PR still contains the old commit, the proper steps to remove it will be:

```
git fetch upstream
git checkout -b new-dev upstream/dev
git cherry-pick 4b250baab4bfcb01a3b388675ef43aca2b64f42a
git push you-remote -f v0.12.16
```

**Comment by jainishshah17** [comment]
@guangbochen Fianally!

**Comment by guangbochen** [comment]
LGTM.

**Pull request merged**
