### PR TITLE
Add istio 1.11.4

### PR DESCRIPTION
**Pull request by doflamingo721**
Add support for the latest istio release: 
https://istio.io/latest/news/releases/1.11.x/announcing-1.11.4/

Linked issue:
https://github.com/rancher/rancher/issues/33683
https://github.com/rancher/rancher/issues/35100

mirroring images: https://github.com/rancher/image-mirror/pull/177

### CODE REVIEW

**Review by jiaqiluo — DISMISSED** [review]
overall LGTM
wait for @brendarearden's review and suggestions about how to address her comment https://github.com/rancher/charts/pull/1578#discussion_r736776417

**Review by brendarearden — CHANGES_REQUESTED** [review]
LGTM, but needs to be rebased with recent istio changes - I added support for volumes in the istio installer

**Review by jiaqiluo — APPROVED** [review]
LGTM

**Review by brendarearden — APPROVED** [review]
LGTM

**Pull request merged**
