### PR TITLE
Forwardport 2.5 charts to 2.6

### PR DESCRIPTION
**Pull request by dhruvmewada15**
This PR forward ports charts released in Rancher 2.5.13 to the Rancher 2.6 branch.

**How does this PR work?**

1. Change the `configuration.yaml` to validate against the release-v2.5 branch _(commit 1)_.
2. Run `make validate`, which will compare the contents of our current directory against the contents of the dev-v2.5 branch, copy over assets and charts, modify the index.yaml, and generate a release.yaml that will mark charts that were modified or added if we were to make a release from dev-v2.5 -> release-v2.5 _(commit 2)_
3. Added the annotation which was missing in `rancher-cis-benchmark:v1.0.700` _(commit 3)_
4. We revert the change to the `configuration.yaml` _(commit 4)_
5.  Manual change made where I ran `rm -rf charts/rancher-operator charts/rancher-operator-crd assets/rancher-operator assets/rancher-operator-crd && make index` in order to delete the forward ported rancher-operator charts _(commit 4)_ 
6. Delete the `release.yaml` _(commit 6)_ 
7. and run make validate again to generate the release.yaml that marks charts that were modified or added if we were to make a release from dev-v2.6 -> release-v2.6._(commit 7)_

**Linked Issue:**
https://github.com/rancher/rancher/issues/37601

**How does this solve the issue?**

- Forward port charts of 2.5 to 2.6 which has `rancher-cis-benchmark:v1.0.700` . This will be pushed to the helm repo [https://charts.rancher.io/](https://charts.rancher.io/) which is currently hosting release-2.6 branch charts. Once this PR is merged `rancher-cis-benchmark:v1.0.700` shall be available in the helm repo as well.

### CODE REVIEW

**Comment by prachidamle** [comment]
LGTM
@aiyengar2 @PennyScissors can you pls review as well if this forward porting of charts looks good?

**Review by aiyengar2 — DISMISSED** [review]
LGTM

Note for other reviewers: the modified assets were ones where we forward-ported and added annotations for Rancher 2.6 to them.

**Review by doflamingo721 — COMMENTED** [review]
lgtm

**Review by doflamingo721 — DISMISSED** [review]

**Review by PennyScissors — DISMISSED** [review]

**Review by samkulkarni20 — APPROVED** [review]
Approving the rebase. @PennyScissors @aiyengar2 had previously approved the original changes.

**Pull request merged**
