### PR TITLE
Update system-upgrade-controller

### PR DESCRIPTION
**Pull request by rohitsakala**

### CODE REVIEW

**Review by aiyengar2 — APPROVED** [review]
```bash
arvindiyengar: ~/Rancher/charts/src/github.com/rancher/charts
$ diff -uNr charts/system-upgrade-controller/100.0.3+up0.3.2/Chart.yaml charts/system-upgrade-controller/100.0.4+up0.3.2/Chart.yaml
```
```diff
diff -uNr charts/system-upgrade-controller/100.0.3+up0.3.2/Chart.yaml charts/system-upgrade-controller/100.0.4+up0.3.2/Chart.yaml
--- charts/system-upgrade-controller/100.0.3+up0.3.2/Chart.yaml	2022-07-25 17:39:34.000000000 -0700
+++ charts/system-upgrade-controller/100.0.4+up0.3.2/Chart.yaml	2022-08-03 12:05:40.000000000 -0700
@@ -8,11 +8,11 @@
   catalog.cattle.io/rancher-version: '>= 2.6.3-0 < 2.7.0-0'
   catalog.cattle.io/release-name: system-upgrade-controller
 apiVersion: v1
-appVersion: v0.8.1
+appVersion: v0.9.1
 description: General purpose controller to make system level updates to nodes
 home: https://github.com/rancher/system-charts/blob/dev-v2.6/charts/rancher-k3s-upgrader
 kubeVersion: '>= 1.16.0-0'
 name: system-upgrade-controller
 sources:
 - https://github.com/rancher/system-charts/blob/dev-v2.6/charts/rancher-k3s-upgrader
-version: 100.0.3+up0.3.2
+version: 100.0.4+up0.3.2
diff -uNr charts/system-upgrade-controller/100.0.3+up0.3.2/values.yaml charts/system-upgrade-controller/100.0.4+up0.3.2/values.yaml
--- charts/system-upgrade-controller/100.0.3+up0.3.2/values.yaml	2022-07-25 17:39:34.000000000 -0700
+++ charts/system-upgrade-controller/100.0.4+up0.3.2/values.yaml	2022-08-03 12:05:40.000000000 -0700
@@ -5,9 +5,9 @@
 systemUpgradeController:
   image:
     repository: rancher/system-upgrade-controller
-    tag: v0.8.1
+    tag: v0.9.1

 kubectl:
   image:
     repository: rancher/kubectl
-    tag: v1.20.2
+    tag: v1.20.15
```

LGTM from a charts perspective, but @rohitsakala should we bump the image on rancher/system-charts to have a version of 0.3.3? Seems like we are making a non-trivial change that should be tracked in a different chart version

**Comment by rohitsakala** [comment]
Made this PR - https://github.com/rancher/system-charts/pull/568

**Comment by HarrisonWAffel** [comment]
@rohitsakala [This PR is going to remove version 100.0.3](https://github.com/rancher/charts/pull/2008), as it introduced a [bug when rolling back rancher versions](https://github.com/rancher/rancher/issues/38501). Subsequently, this PR will need to be updated to use that version (100.0.3) as opposed to 100.0.4 so that we do not have a bad version in our history. Sorry for the unexpected churn  

Additionally, [the system-charts PR](https://github.com/rancher/system-charts/pull/568) seems to be modifying a released version of the chart (v0.3.2), which may not be a good idea if we are making substantial changes.

**Comment by aiyengar2** [comment]
@rohitsakala closing this PR in favor of https://github.com/rancher/charts/pull/2024, which resolves @HarrisonWAffel's comment as well.

**Pull request closed without merging**
