### PR TITLE
fix rancher-monitoring-crd installation issue

### PR DESCRIPTION
**Pull request by w13915984028**
## Issue: 

https://github.com/rancher/rancher/issues/43418

## Problem

The `rancher-monitoring-crd` jobs uses `kubectl replace -Rf /etc/crd || kubectl create -Rf /etc/crd;`, but the RBAC has only `verbs: ['create', 'get', 'patch', 'delete']`

## Solution

Add `update` to RBAC

### Manual Testing

Install `rancher-monitoring-crd `` in bootstrap stage (e.g. in Harvester), the `prometheuses.monitoring.coreos.com` CRD is not correctly installed, and the error message is observed in both 
https://github.com/rancher/rancher/issues/43418
and
https://github.com/harvester/harvester/issues/3969
and more

## Backporting considerations

Please note, at least `102.0.0+up40.1.2` and `102.0.1+up40.1.2` are affected, more releases need to be checked by the owner, thanks.

### CODE REVIEW

**Comment by ebuildy** [comment]
This version have been released on release branch hence on production :/ 

https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring-crd/102.0.1%2Bup40.1.2/templates/rbac.yaml#L12

Please guys can you accept the PR? Or give a workaround.

**Review by joshmeranda — APPROVED** [review]

**Review by dbason — CHANGES_REQUESTED** [review]
We should bump the version and also make sure this is forward ported into v2.8

**Comment by w13915984028** [comment]
It took too long to review this PR, the code is rebased with dev-v2.8 branch, and a new PR is ready for review now:

@joshmeranda @dbason please re-review below PR, thanks.

https://github.com/rancher/charts/pull/3045

**Comment by nicholasSUSE** [comment]
Hello @w13915984028 @joshmeranda 
Is this Pull Request still relevant?
Can I close it?

**Comment by joshmeranda** [comment]
@nicholasSUSE this is deprecated by https://github.com/rancher/charts/pull/3318. We can close

**Pull request closed without merging**
