### PR TITLE
Bump rancher-eks-operator to 1.1.4

### PR DESCRIPTION
**Pull request by macedogm**
Bump executed to refresh base image and update its packages. No modifications were done to the chart itself.

### CODE REVIEW

**Review by annablender — APPROVED** [review]
LGTM, long as there are no merge conflicts

**Review by annablender — CHANGES_REQUESTED** [review]
Asset generation should be in a separate 'make charts' commit

**Review by annablender — APPROVED** [review]

**Review by annablender — CHANGES_REQUESTED** [review]
The base image change here is not a functional change, so it makes more sense to tag an rc instead of a release version. Tag `1.1.4-rc1`

**Comment by macedogm** [comment]
The bump was done in https://github.com/rancher/charts/pull/1965.

**Pull request closed without merging**
