### PR TITLE
Adding new partner app - bluehub into the forked rancher/charts repo

### PR DESCRIPTION
**Pull request by bluespireinc**
This PR is to include new partner app bluehub from Blue Spire.

### CODE REVIEW

**Comment by PennyScissors** [comment]
@bluespireinc I'm seeing the following error in our tests

```
ValueError:
Error validating data /drone/src/charts/bluehub/v0.1.0/Chart.yaml with schema /etc/ct/chart_schema.yaml
    home: Required field missing
```

**Comment by PennyScissors** [comment]
Is there a way I can get access to your fork and branch so that I can test the chart in rancher? 
Your repository comes up as unknown.
`bluespireinc wants to merge 5 commits into rancher:master from unknown repository`

**Comment by bluespireinc** [comment]
Please close this PR as the files were corrupted while upload. We've created a new PR - #614 . Thank you

**Comment by PennyScissors** [comment]
Closed in favor of PR: https://github.com/rancher/charts/pull/614

**Pull request closed without merging**
