### PR TITLE
[v2.9] Bump aks-operator to v1.3.0-rc2

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by recena** [comment]
@mjura Since you are modifying several Helm Charts at the same time, and the PR title does not represent (or describe) the change, Could you provide context and information in the PR description?

**Comment by mjura** [comment]
> @mjura Since you are modifying several Helm Charts at the same time, and the PR title does not represent (or describe) the change, Could you provide context and information in the PR description?

@recena what changed recently with releasing Helm charts? I have modified only aks-operator and run `make charts`

**Comment by recena** [comment]
@mjura Maybe I am wrong but I see you are modifying several Helm Charts at the same time. Let me double check with @rancher/mapps

**Comment by diogoasouza** [comment]
> @mjura Maybe I am wrong but I see you are modifying several Helm Charts at the same time. Let me double check with @rancher/mapps

That's right. There's many modifications to many charts, but it should only be for aks-operator

**Comment by nicholasSUSE** [comment]
> > @mjura Since you are modifying several Helm Charts at the same time, and the PR title does not represent (or describe) the change, Could you provide context and information in the PR description?
> 
> @recena what changed recently with releasing Helm charts? I have modified only aks-operator and run `make charts`

Just to be sure when you ran `make charts`
Did you specify the `PACKAGE=` to a specific chart?

**Comment by mjura** [comment]
@recena @diogoasouza @nicholasSUSE Thank you for your help, after specifying `PACKAGE=` name it started to work fine. I see here some issue, I suspect that in branch `dev-v2.9` we have already not tested changes, because for `dev-v2.8` `make charts` just works fine without specifying `PACKAGE=` name.

**Review by mbologna — APPROVED** [review]

**Review by salasberryfin — APPROVED** [review]

**Comment by nicholasSUSE** [comment]
## Validation steps
  - Ensure all container images have repository and tag on the same level to ensure that all container images are included in rancher-images.txt which are used by airgap customers.
  <pre>
  Ex:-
    longhorn-controller:
      repository: rancher/hardened-sriov-cni
      tag: v2.6.3-build20230913
  </pre>
  - Add a 👍 (thumbs up) reaction to this comment once done. CI won't pass without this reaction to the github-action bot's latest validation comment.
  - Approve the PR to run the CI check.

**Pull request merged**
