### PR TITLE
Bump rancher-webhook to v0.5.0-rc6

### PR DESCRIPTION
**Pull request by tomleb**
## Issue: https://github.com/rancher/rancher/issues/40584

Includes https://github.com/rancher/webhook/pull/332 to fix integration tests in rancher/rancher.

### CODE REVIEW

**Review by JonCrowther — APPROVED** [review]

**Review by maxsokolovsky — APPROVED** [review]

**Comment by tomleb** [comment]
@recena It seems like with the new CODEOWNER thing we must get approval from mapps team to merge this. Is this correct? If so, how should we deal with bump to webhook that are "urgent"-ish, where urgent-ish in this case is that CI for rancher/rancher are constantly failing due to `-rc5` introducing a regression?

**Comment by tomleb** [comment]
Rebased since it couldn't be merged anymore.

**Comment by tomleb** [comment]
Rebased again.

**Comment by tomleb** [comment]
CCing @rancher/mapps to see if we can get this in, since this fixes an issue on rancher release/v2.9 preventing any CI run from succeeding.

**Comment by tomleb** [comment]
The check container image fails to find some images like:
`rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.6.3` but that image exists, I'm able to pull them (at least from docker.io).

```
time="2024-02-20T17:54:12Z" level=info msg="Checking tag rancher/jimmidyson-configmap-reload:v0.3.0"
time="2024-02-20T17:54:12Z" level=error msg="failed to check tag rancher/jimmidyson-configmap-reload:v0.3.0 - received unexpected status code 502 with message: {}"
...
time="2024-02-20T17:54:12Z" level=info msg="Checking tag rancher/mirrored-prom-prometheus:v2.18.2"
time="2024-02-20T17:54:12Z" level=error msg="failed to check tag rancher/mirrored-prom-prometheus:v2.18.2 - received unexpected status code 502 with message: {}"
...
time="2024-02-20T17:54:13Z" level=info msg="Checking tag rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.4.3"
time="2024-02-20T17:54:13Z" level=error msg="failed to check tag rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.4.3 - received unexpected status code 502 with message: {}"
...
 time="2024-02-20T17:54:13Z" level=info msg="Checking tag rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.6.3"
time="2024-02-20T17:54:13Z" level=error msg="failed to check tag rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.6.3 - received unexpected status code 502 with message: {}"
...
 time="2024-02-20T17:54:17Z" level=info msg="Checking tag rancher/mirrored-openpolicyagent-gatekeeper:v3.5.1"
time="2024-02-20T17:54:17Z" level=error msg="failed to check tag rancher/mirrored-openpolicyagent-gatekeeper:v3.5.1 - received unexpected status code 500 with message: {}"
```

**EDIT:** Also looks like we're getting rate limited at that CI step a few times:

```
time="2024-02-20T18:13:46Z" level=info msg="Checking tag rancher/eks-operator:v1.1.2"
time="2024-02-20T18:13:46Z" level=info msg="request was rate limited, retrying in 59.202874041s"
```

**Review by nicholasSUSE — APPROVED** [review]

**Pull request merged**
