### PR TITLE
Add Longhorn 1.4.3 chart with dev-2.7

### PR DESCRIPTION
**Pull request by weizhe0422**
[Longhorn 6102](https://github.com/longhorn/longhorn/issues/6102)

https://github.com/rancher/rancher/issues/41622

Signed-off-by: Ray Chang [ray.chang@suse.com]

cc @innobead @PhanLe1010 @khushboo-rancher

### CODE REVIEW

**Comment by weizhe0422** [comment]
Try to install Longhorn `V1.4.3` via Rancher Apps but replace the image repository from rancher mirror: `rancher/mirrored-longhornio-` to `longhornio/, the installation is successful.
image
image


Still need wait QA further verification and mirror images release: https://github.com/rancher/image-mirror/pull/416

**Comment by roger-ryao** [comment]
- [x] Fresh installation
- [x] Uninstallation
- [x] Upgrade from v1.3.3 - > v1.4.3
- [x] Upgrade from v1.4.2 - > v1.4.3

verify is passed this PR as follow step

**The test steps**
1. Create pod_with_pvc. https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pod_with_pvc.yaml
2. Create orphaned data.
SSH to one of the nodes and copy the contents of one replica directory, 
e.g., `pvc-abc-…012`, to a new directory named `pvc-abc-…013`. This will make `pvc-abc-…013` an orphaned replica.
3. Deploy a statefulSet and attach to the volume. https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml
4. Validate that the volume is created and attached to the pod properly in the Longhorn GUI.
5. Validate the pod is mounted properly.
6. Scale down and up the statefulSet to check volume detach and attach is working fine.

**Comment by khushboo-rancher** [comment]
Leaving a note, https://github.com/rancher/image-mirror/pull/416 should be merged before this PR.

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by PhanLe1010** [comment]
The conflict is probably the file `release.yaml` is out of sync with the base branch @weizhe0422 Resolve that then we should be good

**Comment by weizhe0422** [comment]
@PhanLe1010 Thank you, I have fixed the `release.yaml` conflict.

**Review by rohitsakala — APPROVED** [review]

**Pull request merged**
