### PR TITLE
Add NeuVector chart version 2.7.3

### PR DESCRIPTION
**Pull request by selvamt94**
## Problem
NeuVector has released app version 5.3.0 along with helm chart 2.7.3, which need to be added to Rancher feature charts version 2.7 (release-v2.7). We would like to include this chart in Rancher Manager release v2.7.11 otherwise this need to be released as OOB.

## Solution
New Chart release
### Manual Testing
Tested fresh install of the chart 102.0.8+up2.7.3 and l upgrade from previous version on RKE and RKE2 cluster.
## QA Testing Considerations
Tested fresh install of the chart 102.0.8+up2.7.3 and l upgrade from previous version on RKE and RKE2 cluster.

### CODE REVIEW

**Comment by adamkpickering** [comment]
Looks good to me, though I'm going to hold off on the approval because I think this may need to be merged into `dev-v2.7.11`, not `dev-v2.7`. @nicholasSUSE @lucasmlp can you please confirm that this is the case?

To be clear, `dev-v2.7` would normally be the right target for this PR. We are merging things to `dev-v2.7.11` because there was confusion over branching and a lot of work was put on that branch. We are in the process of resolving this.

**Review by nicholasSUSE — CHANGES_REQUESTED** [review]
Please rebase the PR and target it to `dev-v2.7.11`

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Comment by lucasmlp** [comment]
@nicholasSUSE and @adamkpickering 
@selvamt94 opened a different [PR](https://github.com/rancher/charts/pull/3474) to the `dev-v2.7.11`

**Comment by lucasmlp** [comment]
@selvamt94 please rebase this with the base branch so I can merge the PR

**Review by nicholasSUSE — APPROVED** [review]
If there is another PR for 2.7.11 then this is approved.

**Pull request merged**
