### PR TITLE
Bump fleet v0.5.0-rc1

### PR DESCRIPTION
**Pull request by mattfarina**

### CODE REVIEW

**Comment by prachidamle** [comment]
related tickets: 
https://github.com/rancher/rancher/issues/38966
https://github.com/rancher/rancher/issues/38967

**Review by prachidamle — APPROVED** [review]
LGTM, needs a rebase

**Review by aiyengar2 — APPROVED** [review]
LGTM, ping me when you resolve conflicts so I can reapprove!

**Comment by mattfarina** [comment]
This is replaced by the PR at #2112

**Pull request closed without merging**
