### PR TITLE
Update fleet to v0.3.4-rc4

### PR DESCRIPTION
**Pull request by nickgerace**
Note: this may change to be merged into `dev-v2.5-source` pending @aiyengar2.

Relevant issue: https://github.com/rancher/rancher/issues/30516

### CODE REVIEW

**Review by StrongMonkey — DISMISSED** [review]

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Comment by aiyengar2** [comment]
@nickgerace I pointed this PR to dev-v2.5-source and reran the workflow. No other changes are necessary.

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
Rebase to run the new scripts workflow

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Review by cbron — APPROVED** [review]

**Pull request merged**
