### PR TITLE
Chart version 1.0.19

### PR DESCRIPTION
**Pull request by dlbock**
This changeset includes:
- Mount `/var/lib/containers/storage` in the `DaemonSet` for CRI-O support
- Update the `instana/agent` image tag to the latest available `1.0.42` that's on DockerHub as of Dec 16 2019 (https://hub.docker.com/r/instana/agent/tags)

### CODE REVIEW

**Comment by dlbock** [comment]
@guangbochen Use this PR instead of the previous one. Thanks!

**Comment by dlbock** [comment]
@guangbochen still need some help with the failed linting. I'm not sure how to fix the issue.

**Comment by guangbochen** [comment]
@dlbock can u please rebase to the master branch, thanks

**Comment by dlbock** [comment]
@guangbochen can do. Should I be creating PRs from `master` going forward? Or is this a one time thing? Just need to know so I can update our automated pipeline.

**Comment by dlbock** [comment]
@guangbochen okay, I've rebased this PR on `master`. Looks like the checks passed. Let me know if I need to change the base branch going forward as I will have other PRs coming soon. Thank you!

**Comment by guangbochen** [comment]
LGTM, @dlbock u can submit PR to the master branch, thanks.

**Comment by dlbock** [comment]
@guangbochen This PR is submitted to the `master` branch.

Also, can you clarify if we need to be submitting PRs to the `master` branch going forward instead of the `partners` branch?

**Comment by guangbochen** [comment]
thanks @dlbock, and yes it is fine to submit against the `master` branch going forward.

**Pull request merged**
