### PR TITLE
Removing assets, since new chart version is being started from v1.0.0

### PR DESCRIPTION
**Pull request by prachidamle**
Removing assets, since new chart version is being started from v0.2.0, as per the discussion here:
https://github.com/rancher/charts/pull/710#discussion_r495613240

https://github.com/rancher/cis-operator/issues/37

### CODE REVIEW

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
Need to remove contents of `charts/rancher-cis-benchmark`, `sha256sum/rancher-cis-benchmark`, and `assets/index.yaml` as well.

**Review by cbron — COMMENTED** [review]
Looks fine to me, lets get other PR in first to get new version out

**Review by cbron — APPROVED** [review]

**Comment by cbron** [comment]
If we are just removing a version and not renaming the chart, we only need to remove the assets/index.yaml and index.yaml. If renaming the chart we need to do all of them.

**Review by aiyengar2 — APPROVED** [review]
Needs a rebase but LGTM!

**Review by cbron — APPROVED** [review]
Sha removal isn't necessary but thats ok, it will just repopulate.

**Review by aiyengar2 — APPROVED** [review]

**Pull request merged**
