### PR TITLE
[dev-v2.8] Bump chart cloud-provider-harvester to v0.2.3

### PR DESCRIPTION
**Pull request by w13915984028**
## Issue: 

https://github.com/harvester/harvester/issues/4703

## Problem

Harvester chart cloud-provider-harvester v0.2.3 (https://github.com/harvester/charts/releases/tag/harvester-cloud-provider-0.2.3) is released, but not in Rancher charts v2.7 and v2.8.

BTW, the `up0.2.3` fixed an important issue: https://github.com/harvester/harvester/issues/4678.

## Solution

Bump chart cloud-provider-harvester to v0.2.3

### CODE REVIEW

**Comment by nicholasSUSE** [comment]
Hello @w13915984028 
Is this Pull Request still relevant?
Can I close it?

**Comment by w13915984028** [comment]
@nicholasSUSE We still need this bump, I will rebase the PR to solve the conflict, thanks.

**Comment by w13915984028** [comment]
@nicholasSUSE @lucasmlp :

The PR is rebased, we have merged the https://github.com/rancher/charts/pull/3377 into v2.7.11; and this PR is for dev-v2.8, please help review and merge, thanks.

**Review by nicholasSUSE — APPROVED** [review]
Looks good to me. @w13915984028 
Please have in mind that we at Mapps team can only review some patterns in charts that we do not own. 
I strongly recommend that you get a second review from someone else that also owns this chart.

**Comment by recena** [comment]
This should be reviewed by @rancher/harvester.

**Comment by w13915984028** [comment]
@nicholasSUSE @recena @lucasmlp 

We have already reviewed the charts in Harvester side; but we have no rights to merge the chart into this repository. 

It seems no named one from Rancher is responsible for review this chart. It tooks many time to continuously rebase.

Any idea to optimize and speed up the chart merging process? thanks.

**Comment by recena** [comment]
@w13915984028 There are conflicts, you can't merge it.

**Comment by recena** [comment]
@w13915984028 Moreover, you need a approval from @rancher/harvester (team).

**Comment by recena** [comment]
@w13915984028 

> but we have no rights to merge the chart into this repository.

You do have permission.

> It seems no named one from Rancher is responsible for review this chart. It tooks many time to continuously rebase.

This chart is under @rancher/harvester (team)

> Any idea to optimize and speed up the chart merging process? thanks.

When meeting the criteria, you can merge.

**Comment by w13915984028** [comment]
@recena Your suggestions are very helpful :), appreciated.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
