### PR TITLE
adding new resource signer in cluster role required k8s 1.18 onwards

### PR DESCRIPTION
**Pull request by ajeetas**

### CODE REVIEW

**Comment by PennyScissors** [comment]
I'm still running into the same problem with this version using kubernetes v1.18.8.

Steps to reproduce:
1. enable istio in 3 node (1 etcd, 1 control-plane, 1 worker) cluster
2. install chart in default project (Accept EULA, and leave other chart values unchanged)

Logs from container: `sidecar-certs-generator`
```
time="2020-09-02T20:08:11Z" level=debug msg="in-Cluster environment. Generating config file using script \n" 
time="2020-09-02T20:08:11Z" level=debug msg="KUBECONFIG: /tmp/configdir/config" 
time="2020-09-02T20:08:11Z" level=debug msg="Running script /home/appuser/scripts/webhook-create-signed-cert.sh" 
time="2020-09-02T20:08:22Z" level=debug msg="Error:%!(EXTRA *exec.ExitError=exit status 1)" 
time="2020-09-02T20:08:22Z" level=error msg="Could not run CPX webhook script: exit status 1" 
time="2020-09-02T20:08:22Z" level=error msg="Could not generate certificate for cpx-sidecar-injector webhook service: Could not run CPX webhook script: exit status 1" 
```

Logs from container: `sidecar-injector-webhook`
```
2020-09-02T20:09:08.001030Z	info	version root@71a9470ea93c-docker.io/istio-1.0.0-3a136c90ec5e308f236e0d7ebb5c4c5e405217f4-Clean 
2020-09-02T20:09:08.001746Z	info	New configuration: sha256sum 2df91240866374ec9cc5f0db054110b4e723445ead3aef7d29711634ac04313a 
2020-09-02T20:09:08.001771Z	info	Policy: enabled 
2020-09-02T20:09:08.001853Z	info	Template: | 
  containers: 
  - name: istio-adaptor 
    image: quay.io/citrix/citrix-istio-adaptor:1.2.1 
    imagePullPolicy: IfNotPresent 
    env: 
    - name: POD_NAME 
      valueFrom: 
        fieldRef: 
          fieldPath: metadata.name 
    - name: POD_NAMESPACE 
      valueFrom: 
        fieldRef: 
          fieldPath: metadata.namespace 
    - name: INSTANCE_IP 
      valueFrom: 
        fieldRef: 
          fieldPath: status.podIP 
    - name: NODE_NAME 
      valueFrom: 
        fieldRef: 
          fieldPath: spec.nodeName 
    - name: APPLICATION_NAME 
      valueFrom: 
        fieldRef: 
          fieldPath: metadata.labels['app'] 
    - name: NS_USER 
      value: nsroot 
    - name: NS_PASSWORD 
      value: nsroot 
    args: 
    - -pilot-location 
    - istio-pilot.istio-system:15011 # istio-pilot.istio-system:15011 
    - -proxy-type 
    - "sidecar" 
    - -pilot-SAN 
    - spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account 
    - -netscaler-url 
    - "http://127.0.0.1" 
    - -secure-connect=true 
    - -adm-ip 
    - "" 
    volumeMounts: 
    - mountPath: /etc/certs/ 
      name: istio-certs 
      readOnly: true 
    - mountPath: /etc/nslogin 
      name: nslogin 
      readOnly: true 
    securityContext: 
      readOnlyRootFilesystem: true 
      runAsUser: 32024 # UID of istio-adaptor container's user 
  - name: cpx-proxy 
    image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-47.22 
    imagePullPolicy: IfNotPresent 
    securityContext: 
      privileged: true 
    env: 
    - name: "EULA" 
Error: failed to create injection webhook open /etc/istio/certs/cert.pem: no such file or directory 
      value: "YES" 
    - name: "CPX_SIDECAR_MODE" 
      value: "true" 
    - name: "MGMT_HTTP_PORT" 
      value: "10080" 
    - name: "MGMT_HTTPS_PORT" 
      value: "10443" 
    - name: "KUBERNETES_TASK_ID" 
      value: "" 
    - name: "NS_CPX_LITE" 
      value: 1 
    - name: "LS_IP" 
      value: 
    - name: "LS_PORT" 
      value: 27000 
    - name: "LOGSTREAM_COLLECTOR_IP" 
      value: 
    volumeMounts: 
    - mountPath: /cpx/conf/ 
      name: cpx-conf 
  volumes: 
  - name: cpx-conf 
    emptyDir: {} 
  - name: nslogin 
    secret: 
      optional: true 
      secretName: nslogin 
  - name: istio-certs 
    secret: 
      optional: true 
      [[ if eq .Spec.ServiceAccountName "" -]] 
      secretName: istio.default 
      [[ else -]] 
      secretName: [[ printf "istio.%s" .Spec.ServiceAccountName ]] 
      [[ end -]] 
```

**Comment by ajeetas** [comment]
Hi @PennyScissors

Please provide the below details:

1. Istio version

2. kubectl get clusterrole  -n <namespace> -o yaml

3. kubectl get csr  -n <namespace>

**Comment by PennyScissors** [comment]
@ajeetas Yes, the problem I'm seeing and logs come from template v1.2.3. If you need I can setup a cluster, install the chart and give you access so you can check it out. 

1. Istio version: 1.5.9

2. kubectl get pods  -n istio-system 
```
> kubectl get pods -n istio-system
NAME                                      READY   STATUS    RESTARTS   AGE
istio-citadel-7948958b74-l4kqn            1/1     Running   0          20h
istio-galley-57db864687-6pvfb             1/1     Running   0          20h
istio-pilot-68778f6cdf-gxhcl              2/2     Running   1          20h
istio-policy-5c885875fb-r9mtz             2/2     Running   1          20h
istio-sidecar-injector-5f5fbc7ff9-rv78t   1/1     Running   0          20h
istio-telemetry-ccf5f4b98-s4f4s           2/2     Running   1          20h
istio-tracing-767b77df75-qhk5d            1/1     Running   0          20h
kiali-7dcf6488b-cc89v                     1/1     Running   0          20h
```
2. kubectl get clusterrole  -n <namespace_name> -o yaml
https://pastebin.com/C9JAde6K

3. kubectl get csr  -n <namespace_name>
```
> kubectl get csr  -n citrix-cpx-istio-sidecar-injector
NAME                                 AGE   SIGNERNAME                     REQUESTOR                                                                                      CONDITION
cpx-sidecar-injector.citrix-system   10m   kubernetes.io/legacy-unknown   system:serviceaccount:citrix-cpx-istio-sidecar-injector:cpx-sidecar-injector-service-account   Approved
```
4. kubectl get clusterrole cpx-sidecar-injector-istio-system  -n <namespace_name> -o yaml
```
> kubectl get clusterrole cpx-sidecar-injector-istio-system  -n citrix-cpx-istio-sidecar-injector -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: citrix-cpx-istio-sidecar-injector
    meta.helm.sh/release-namespace: citrix-cpx-istio-sidecar-injector
  creationTimestamp: "2020-09-03T16:44:29Z"
  labels:
    app: cpx-sidecar-injector
    app.kubernetes.io/managed-by: Helm
    io.cattle.field/appId: citrix-cpx-istio-sidecar-injector
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:io.cattle.field/appId: {}
      f:rules: {}
    manager: Go-http-client
    operation: Update
    time: "2020-09-03T16:44:29Z"
  name: cpx-sidecar-injector-istio-system
  resourceVersion: "213110"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/cpx-sidecar-injector-istio-system
  uid: 224f1214-cec5-4de8-846b-49c213834174
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - get
  - list
  - create
  - watch
  - delete
  - update
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/legacy-unknown
  resources:
  - signers
  verbs:
  - get
  - list
  - create
  - watch
  - delete
  - update
  - approve
```

**Review by PennyScissors — COMMENTED** [review]
@ajeetas Yes, the problem I'm seeing and logs come from template v1.2.3. If you need I can setup a cluster, install the chart and give you access so you can check it out. 

1. Istio version: 1.5.9

2. kubectl get pods  -n istio-system 
```
> kubectl get pods -n istio-system
NAME                                      READY   STATUS    RESTARTS   AGE
istio-citadel-7948958b74-l4kqn            1/1     Running   0          20h
istio-galley-57db864687-6pvfb             1/1     Running   0          20h
istio-pilot-68778f6cdf-gxhcl              2/2     Running   1          20h
istio-policy-5c885875fb-r9mtz             2/2     Running   1          20h
istio-sidecar-injector-5f5fbc7ff9-rv78t   1/1     Running   0          20h
istio-telemetry-ccf5f4b98-s4f4s           2/2     Running   1          20h
istio-tracing-767b77df75-qhk5d            1/1     Running   0          20h
kiali-7dcf6488b-cc89v                     1/1     Running   0          20h
```
2. kubectl get clusterrole  -n <namespace_name> -o yaml
https://pastebin.com/s6DZd7X2 (too long to paste here)

3. kubectl get csr  -n <namespace_name>
```
> kubectl get csr  -n citrix-cpx-istio-sidecar-injector
NAME                                 AGE   SIGNERNAME                     REQUESTOR                                                                                      CONDITION
cpx-sidecar-injector.citrix-system   10m   kubernetes.io/legacy-unknown   system:serviceaccount:citrix-cpx-istio-sidecar-injector:cpx-sidecar-injector-service-account   Approved
```
4. kubectl get clusterrole cpx-sidecar-injector-istio-system  -n <namespace_name> -o yaml
```
> kubectl get clusterrole cpx-sidecar-injector-istio-system  -n citrix-cpx-istio-sidecar-injector -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: citrix-cpx-istio-sidecar-injector
    meta.helm.sh/release-namespace: citrix-cpx-istio-sidecar-injector
  creationTimestamp: "2020-09-03T16:44:29Z"
  labels:
    app: cpx-sidecar-injector
    app.kubernetes.io/managed-by: Helm
    io.cattle.field/appId: citrix-cpx-istio-sidecar-injector
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:io.cattle.field/appId: {}
      f:rules: {}
    manager: Go-http-client
    operation: Update
    time: "2020-09-03T16:44:29Z"
  name: cpx-sidecar-injector-istio-system
  resourceVersion: "213110"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/cpx-sidecar-injector-istio-system
  uid: 224f1214-cec5-4de8-846b-49c213834174
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - get
  - list
  - create
  - watch
  - delete
  - update
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/legacy-unknown
  resources:
  - signers
  verbs:
  - get
  - list
  - create
  - watch
  - delete
  - update
  - approve
```

**Comment by PennyScissors** [comment]
@ajeetas Just following up on this.

**Comment by ajeetas** [comment]
@PennyScissors  I will working on this, I will update you asap. Thanks!

**Comment by ajeetas** [comment]
@PennyScissors  Please try to run with the new commit.

**Comment by PennyScissors** [comment]
@ajeetas Thank you! Just tried it out and ran into the same problem.

**Comment by ajeetas** [comment]
Thank you @PennyScissors 
Please do the following :
1. Just to make sure, delete existing created chart `citrix-cpx-istio-sidecar-injector`. 
2. kubernetes version should be 1.18.8 (If It is 1.19 need to check further)
3. Please delete CSR, clusterrole, clusterrolebinding
    1. kubectl delete csr cpx-sidecar-injector.citrix-system -n <namespace>
    2.  kubectl delete clusterrole cpx-sidecar-injector-istio-system -n <namespace>
    3.  kubectk delete clusterrolebinding cpx-sidecar-injector-admin-role-binding-istio-system -n <namespace>
4. deploy chart citrix-cpx-istio-sidecar-injector.

**Comment by PennyScissors** [comment]
Thanks @ajeetas 
I'm using k8s v1.18.8, and I skipped the cleanup steps since I've been using new clusters for each installation to test this chart.

Here is the information requested:

```
> kubectl get csr -n citrix-cpx-istio-sidecar-injector
NAME                                 AGE   SIGNERNAME                     REQUESTOR                                                                                      CONDITION
cpx-sidecar-injector.citrix-system   50s   kubernetes.io/legacy-unknown   system:serviceaccount:citrix-cpx-istio-sidecar-injector:cpx-sidecar-injector-service-account   Approved
```

```
> kubectl get clusterrole cpx-sidecar-injector-istio-system -n citrix-cpx-istio-sidecar-injector -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2020-09-23T21:35:30Z"
  labels:
    app: cpx-sidecar-injector
    io.cattle.field/appId: citrix-cpx-istio-sidecar-injector
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:io.cattle.field/appId: {}
      f:rules: {}
    manager: Go-http-client
    operation: Update
    time: "2020-09-23T21:35:30Z"
  name: cpx-sidecar-injector-istio-system
  resourceVersion: "11709"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/cpx-sidecar-injector-istio-system
  uid: bf6ab257-1f4b-4078-af97-2e7aab1ef1be
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - get
  - list
  - create
  - watch
  - delete
  - update
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/legacy-unknown
  - '*'
  resources:
  - signers
  verbs:
  - get
  - list
  - create
  - watch
  - delete
  - update
  - approve
```

**Error:**
```
> kubectl get clusterrolebinding cpx-sidecar-injector-istio-system -n citrix-cpx-istio-sidecar-injector -o yaml
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "cpx-sidecar-injector-istio-system" not found
```

**Comment by ajeetas** [comment]
Please deploy chart with new commit.
1.  kubectl logs -n <namespace> <cpx-sidecar-injector-pod-name> -c sidecar-certs-generator
2. kubectl get csr -n <namespace_name>
3. kubectl get clusterrole cpx-sidecar-injector-istio-system -n <namespace_name> -o yaml
4. kubectl get clusterrolebinding cpx-sidecar-injector-admin-role-binding-istio-system -n <namespace_name> -o yaml


If new changes will not work, Please provide your setup details for further debugging.


Thanks,
Ajeeta

**Comment by PennyScissors** [comment]
Hello @ajeetas, I still see the same error. I sent you the setup details on Slack. Thanks!

**Comment by ajeetas** [comment]
Hi @PennyScissors 

I have updated `app-readme` with the required information to add kube-controllers info for RKE based cluster in cloud provider. Please check it and review the PR.

**Review by PennyScissors — APPROVED** [review]
lgtm

**Pull request merged**
