### PR TITLE
fix(Longhorn): fix group name for Longhorn Longhorn CSI Liveness Prob…

### PR DESCRIPTION
**Pull request by weizhe0422**
## Issue: 
https://github.com/longhorn/longhorn/issues/5794

## Problem
The group name of `Longhorn CSI Liveness Probe Image Tag` in `question.yaml` is not correct and it makes the options category to the wrong page.

## Solution
Fix the upstream to make the group name should be Longhorn CSI Driver Images rather than Longhorn CSI Liveness Probe Images

## Testing
 1. Having a K8S cluster
 2. Add repository with https://github.com/weizhe0422/rancher-charts/tree/dev-v2.7_LH_Issue%235794
 3. Try to install Longhorn v1.3.3 and check the `Edit Options
 4. Uncheck `Use Default Images`
 5. The 'Longhorn CSI Liveness Probe Image Tag' should belong to `Longhorn CSI Driver Images` page like below 
    截圖 2023-04-25 下午2 56 33

cc @innobead @PhanLe1010 @khushboo-rancher 

Signed-off-by: Ray Chang <ray.chang@suse.com>

### CODE REVIEW

**Comment by khushboo-rancher** [comment]
I'm not able to pull the repo in the Rancher. It could be because of the branch name `dev-v2.6_LH_Issue#235794`

`Git clone --depth=1 -n --branch=dev-v2.7_LH_Issue#235794 -- https://github.com/weizhe0422/rancher-charts management-state/git-repo/test-lh/e3d20f6b9e0de4c5f947566d3edeb58782852de08959b8e951fec0ac6786fac3 error: exit status 128, detail: Cloning into 'management-state/git-repo/test-lh/e3d20f6b9e0de4c5f947566d3edeb58782852de08959b8e951fec0ac6786fac3'... warning: Could not find remote branch dev-v2.7_LH_Issue#235794 to clone. fatal: Remote branch dev-v2.7_LH_Issue#235794 not found in upstream origin`

**Comment by khushboo-rancher** [comment]
Thanks @weizhe0422 for helping me resolve the problem.

Fix - LGTM

**Review by PhanLe1010 — COMMENTED** [review]
As discussed with @weizhe0422 It seems that Longhorn 1.3.3 is already released into release-2.7 and release-v2.6 branch which means we shouldn't touch it unless we bump the Rancher chart version (the x.y.z value in the x.y.z+up1.3.3 format) 

We think that we should wait for the next Longhorn 1.3.4 release to update this instead. What do you think? @innobead @khushboo-rancher

**Comment by nicholasSUSE** [comment]
Closed due to inactivity and lack of labels

**Pull request closed without merging**
