### PR TITLE
Backport nginx bump and alertmanager secret change to Monitoring

### PR DESCRIPTION
**Pull request by aiyengar2**
Backports https://github.com/rancher/charts/pull/1384 and https://github.com/rancher/charts/pull/1324.

Related Issues: https://github.com/rancher/rancher/issues/33851, https://github.com/rancher/rancher/issues/33442

### CODE REVIEW

**Review by jiaqiluo — DISMISSED** [review]
LGTM

**Review by jiaqiluo — APPROVED** [review]

**Review by brendarearden — APPROVED** [review]
lgtm

**Comment by aiyengar2** [comment]
The reason for the rancher-webhook change is described in https://github.com/rancher/charts-build-scripts/issues/56.

The rancher-webhook asset from dev-v2.5.9 was shipped to release-v2.5. While this has the same contents as that of dev-v2.5 (as seen in the charts/ directory and manually verified), the TGZ file in release-v2.5 probably differs from that in dev-v2.5 due to metadata changes like timestamp differences between the two branches.

https://github.com/rancher/charts-build-scripts/issues/56 has been filed since this is a false positive flagged by `make validate`, but to fix for now I have pulled in the TGZ from release-v2.5 to dev-v2.5.

**Review by cbron — APPROVED** [review]
Only reviewed new asset, not backport

**Pull request merged**
