### PR TITLE
Bump redskyops chart to v0.1.2

### PR DESCRIPTION
**Pull request by jgustie**

### CODE REVIEW

**Comment by guangbochen** [comment]
@jgustie can you please help to add two commits of the version bump, thanks.
1. base copy v0.1.1 to v0.1.2
2. commit the updates of v0.1.2

**Comment by guangbochen** [comment]
@jgustie thanks for the update but we are expecting two commits in total, can u please rebase your commits and drop commits `00c9cdf` & `f8903d7`, thanks.

**Comment by guangbochen** [comment]
also, the `partners` branch would be the base branch for partners to submit PRs, thanks. @deniseschannon can u please help to double confirm it, thanks.

**Comment by jgustie** [comment]
I dropped the two redundant commits, let me know if there is anything else.

**Comment by guangbochen** [comment]
@jgustie can u please help to rebase the branch to `partners`, thanks.

**Comment by guangbochen** [comment]
LGTM thanks. @deniseschannon

**Pull request merged**
