### PR TITLE
[dev-v2.8] feat: bump harvester-cloud-provider to v0.2.4

### PR DESCRIPTION
**Pull request by FrankYang0529**
## Issue: 

https://github.com/harvester/harvester/issues/4947
https://github.com/harvester/harvester/issues/5247
https://github.com/harvester/charts/pull/230

### CODE REVIEW

**Review by lucasmlp — CHANGES_REQUESTED** [review]
A new asset was added but there's no entry being added in `index.yaml`?

**Comment by FrankYang0529** [comment]
> A new asset was added but there's no entry being added in `index.yaml`?

I update `103.0.1` to `103.0.2` and there is new entry in `index.yaml`. Thanks.

**Comment by w13915984028** [comment]
@lucasmlp A question about the `permits-os` annotation (per https://github.com/rancher/charts/tree/dev-v2.9?tab=readme-ov-file#chartyaml-and-indexyaml). Thanks.

From `rancher-charts`,  `neuvector` cliams to only support linux; other charts are with `catalog.cattle.io/permits-os: linux,windows`. How to verify if Harvester relateds charts supporting `Windows` or not ?

```
charts/neuvector/102.0.1+up2.4.3/Chart.yaml:  catalog.cattle.io/permit-os: linux
..
charts/neuvector-monitor/102.0.3+up2.6.0/Chart.yaml:  catalog.cattle.io/permit-os: linux
```

**Review by w13915984028 — APPROVED** [review]
LGTM, thanks.

**Comment by FrankYang0529** [comment]
Hi @lucasmlp, may you help us review this PR? Thanks.

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Pull request merged**
