### PR TITLE
#1848 Fixes Grafana dashboard error with same pod name in different namespaces

### PR DESCRIPTION
**Pull request by danielhass**
This PR addresses rancher/rancher#39430 

Another issue created by me on the rancher/rancher repo describes the problem in further details: rancher/rancher#37282

Main changes are simplified queries in the following dashboards:
- packages/rancher-monitoring/rancher-monitoring/generated-changes/overlay/files/rancher/workloads/rancher-workload-pods.json
- packages/rancher-monitoring/rancher-monitoring/generated-changes/overlay/files/rancher/workloads/rancher-workload.json

With these in place the error described in the issue are gone.

This PR also includes a bump of the rancher-monitoring chart to v100.1.4+up19.0.3.

### CODE REVIEW

**Review by geethub97 — DISMISSED** [review]

**Comment by geethub97** [comment]
PR looks good to me, some testing is still pending.

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
nit: need you to move the `package.yaml` change into the first commit, not the second, since it is not a generated change. Also rename the second commit `make charts`

---

```diff
arvindiyengar: ~/Rancher/charts/src/github.com/rancher/charts
$ diff -uNr charts/rancher-monitoring/100.1.4+up19.0.3 charts/rancher-monitoring/100.1.3+up19.0.3
diff -uNr charts/rancher-monitoring/100.1.4+up19.0.3/Chart.yaml charts/rancher-monitoring/100.1.3+up19.0.3/Chart.yaml
--- charts/rancher-monitoring/100.1.4+up19.0.3/Chart.yaml	2022-09-22 13:29:38.000000000 -0700
+++ charts/rancher-monitoring/100.1.3+up19.0.3/Chart.yaml	2022-09-22 11:37:27.000000000 -0700
@@ -121,4 +121,4 @@
 - https://github.com/prometheus-community/helm-charts
 - https://github.com/prometheus-operator/kube-prometheus
 type: application
-version: 100.1.4+up19.0.3
+version: 100.1.3+up19.0.3
diff -uNr charts/rancher-monitoring/100.1.4+up19.0.3/files/rancher/workloads/rancher-workload-pods.json charts/rancher-monitoring/100.1.3+up19.0.3/files/rancher/workloads/rancher-workload-pods.json
--- charts/rancher-monitoring/100.1.4+up19.0.3/files/rancher/workloads/rancher-workload-pods.json	2022-09-22 13:29:38.000000000 -0700
+++ charts/rancher-monitoring/100.1.3+up19.0.3/files/rancher/workloads/rancher-workload-pods.json	2022-09-22 09:41:01.000000000 -0700
@@ -568,7 +568,7 @@
         "label": null,
         "multi": false,
         "name": "namespace",
-        "query": "query_result(group (kube_pod_info{namespace!=\"\"}) by (namespace))",
+        "query": "query_result(kube_pod_info{namespace!=\"\"} * on(pod) group_right(namespace, created_by_kind, created_by_name) count({__name__=~\"container_.*|windows_container_.*\", pod!=\"\"}) by (pod))",
         "refresh": 2,
         "regex": "/.*namespace=\"([^\"]*)\"/",
         "sort": 0,
diff -uNr charts/rancher-monitoring/100.1.4+up19.0.3/files/rancher/workloads/rancher-workload.json charts/rancher-monitoring/100.1.3+up19.0.3/files/rancher/workloads/rancher-workload.json
--- charts/rancher-monitoring/100.1.4+up19.0.3/files/rancher/workloads/rancher-workload.json	2022-09-22 13:29:38.000000000 -0700
+++ charts/rancher-monitoring/100.1.3+up19.0.3/files/rancher/workloads/rancher-workload.json	2022-09-22 09:41:01.000000000 -0700
@@ -568,7 +568,7 @@
         "label": null,
         "multi": false,
         "name": "namespace",
-        "query": "query_result(group (kube_pod_info{namespace!=\"\"}) by (namespace))",
+        "query": "query_result(kube_pod_info{namespace!=\"\"} * on(pod) group_right(namespace, created_by_kind, created_by_name) count({__name__=~\"container_.*|windows_container_.*\", pod!=\"\"}) by (pod))",
         "refresh": 2,
         "regex": "/.*namespace=\"([^\"]*)\"/",
         "sort": 0,
```

Otherwise this change LGTM. Thank you for your contribution!! 🥳 🥳

**Comment by aiyengar2** [comment]
We'll still be holding off merging till we have bandwidth to ensure this is tested. Asked in https://github.com/rancher/charts/issues/1848#issuecomment-1255520558.

But we'll try to aim this for the next 2.6 release. Once it has been triaged, if this has any conflicts, I may just fork this PR and cherry-pick your commits via `git cherry-pick -x` (to keep your name on as the author!)

Also @danielhass can you add the entry to the [`release.yaml`](https://github.com/rancher/charts/blob/dev-v2.6/release.yaml)? This is a file we use to track the chart versions that will be released in a given release and is a requirement for CI to pass.

**Comment by danielhass** [comment]
Thanks @aiyengar2 for the detailed review and comments.

I tried to apply all changes requested, rebased onto the latest `dev-v2.6` commit and force pushed the changes.

Please let me know if this looks good or anything else needs to be changes.

Thrilled that my first Rancher contribution might go through :tada:

**Comment by danielhass** [comment]
@aiyengar2 this PR has been open for a few months now. Rancher 2.7 has been released a few days ago. Are you still considering this one?

**Comment by nicholasSUSE** [comment]
Hello @danielhass @aiyengar2 can I close this PR?

**Comment by nicholasSUSE** [comment]
Closed due to inactivity

**Pull request closed without merging**
