### PR TITLE
Epinio in Rancher Charts 2.7 Dev

### PR DESCRIPTION
**Pull request by andreas-kupries**
Ref https://github.com/rancherlabs/image-scanning/issues/1454

Adds chart 101.0.0-up1.4.0 to the 2.7 dev branch.
Note the epinio version bump to 1.4.0.

Testing depends on two open issues:
  - Ticket https://github.com/rancherlabs/eio/issues/1384 
  - PR https://github.com/rancher/image-mirror/pull/315

Note that while the assets for 100.0.0-up1.2.1 are present that they are linked to the 2.6 branch, both by version number (`100`) and `rancher-version` annotation.

The new `101...` has proper version number and annotation for 2.7.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
Folded the work for https://github.com/rancherlabs/image-scanning/issues/1590 into this PR, as it has not been merged yet.

**Comment by andreas-kupries** [comment]
Regarding the :boom: CI ... Error looks to be

> time="2022-11-15T10:12:00Z" level=fatal msg="encountered error while trying to prepare package: encountered error while preparing main chart: encountered error while trying to prepare dependencies in charts: encountered error while preparing main chart: encountered error while trying to pull upstream into charts: unable to read gzip formatted file: gzip: invalid header"

Doing a local wget I get a gzipped tarball I can inspect and unpack just fine.
The only anomaly I see is `file` reporting an extra gzip field, a comment:

> dex-0.12.1.tgz: gzip compressed data, extra field, has comment

Could such a thing break `make validate` ?
I had run `make validate` locally, and it was ok.

**Comment by andreas-kupries** [comment]
Lovely (and not even sarcastic ;) ), the :boom: is gone. While there was a rebase the only modified file was `release.yaml` ... I guess the issue with the compressed tar was a transient network thing.

**Comment by thehejik** [comment]
### QA report
#### Testing environment
Rancher `v2.7.0` on top of a single-node `k3s-v1.24.6+k3s1` cluster with incorporated traefik lb. Helm chart git repository for Epinio Rancher App installation https://github.com/epinio/charts.git and branch `is1454-awscli-image-update-2.7`

#### Tested
* Adding the custom repository for this PR
* Installation of `Epinio (101.0.0+up1.4.0)` App helm chart in Rancher (local k3s cluster) by using default values (+entered base epinio domain) - `epinio` and `epinio-crd` apps were successfully deployed in `cattle-epinio-system` namespace
* All the input boxed for values were ok
* All the relevant resources like pods are in `Ready` state
* Accessed `epinio-ui` over ingress, login by using default credentials
* Created epinio `workspace` namespace for its applications
* Deployment of sample-app phpinfo() app stored in local folder
* Accessing the sample-app over provided URL in epinio-ui
* All resources still ok
* Verified that the new image `rancher/mirrored-amazon-aws-cli:2.8.9` is used by `stage-*` pod.
* Uninstallation (`epinio` and then `epinio-crd`) ok

Everything was working as expected.
image

**Review by thehejik — APPROVED** [review]
LGTM

**Review by olblak — APPROVED** [review]

**Pull request merged**
