### PR TITLE
[dev-v2.8] Add Longhorn 1.5.4 chart

### PR DESCRIPTION
**Pull request by mantissahz**
Release Longhorn v1.5.4 into Rancher 2.8

Longhorn https://github.com/longhorn/longhorn/issues/7878
Rancher https://github.com/rancher/rancher/issues/43675

Signed-off-by: James Lu [james.lu@suse.com](mailto:james.lu@suse.com)

cc @innobead @PhanLe1010 @khushboo-rancher @roger-ryao

Waiting for Longhorn 1.5.4 images merged into the Rancher image-mirror list.

### CODE REVIEW

**Comment by roger-ryao** [comment]
Prerequisites:
- Set the Concurrent Automatic Engine Upgrade Per Node Limit to a value greater than 0.
- `LONGHORN_REPO` is set to `longhornio`.
- Rancher : v2.8.3-rc2

Verify is passed as follows step
- [x] Fresh installation
- [x] Uninstallation
- [x] Upgrade from `v1.5.3` - > `v1.5.4`
- [x] Upgrade from `v1.4.4` - > `v1.5.4`

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by PhanLe1010** [comment]
This PR is blocked by https://github.com/rancher/image-mirror/pull/584

**Comment by PhanLe1010** [comment]
Image PR is ready at https://github.com/rancher/image-mirror/pull/585

**Comment by PhanLe1010** [comment]
Image PR was merged. This PR is ready for merging 

Can you git commit amend and force push to retrigger the PR validation pipeline @mantissahz ?

**Review by nicholasSUSE — APPROVED** [review]
From what I could see the PR is coherent. Please keep in mind that we can only review semver errors, mismatch between packages and charts and etc...
The functionality of the chart is responsibility of the owner. 

Just need to resolve the CI errors:
```
level=error msg="images that are not on Docker Hub: map[rancher/mirrored-longhornio-backing-image-manager:[v1.5.4] rancher/mirrored-longhornio-csi-attacher:[v4.4.2] rancher/mirrored-longhornio-csi-node-driver-registrar:[v2.9.2] rancher/mirrored-longhornio-csi-provisioner:[v3.6.2] rancher/mirrored-longhornio-csi-resizer:[v1.9.2] rancher/mirrored-longhornio-csi-snapshotter:[v6.3.2] rancher/mirrored-longhornio-livenessprobe:[v2.12.0] rancher/mirrored-longhornio-longhorn-engine:[v1.5.4] rancher/mirrored-longhornio-longhorn-instance-manager:[v1.5.4] rancher/mirrored-longhornio-longhorn-manager:[v1.5.4] rancher/mirrored-longhornio-longhorn-share-manager:[v1.5.4] rancher/mirrored-longhornio-longhorn-ui:[v1.5.4] rancher/mirrored-longhornio-support-bundle-kit:[v0.0.33]]"
```

**Review by shuo-wu — APPROVED** [review]

**Pull request merged**
