### PR TITLE
fix(Longhorn): fix group name for Longhorn Longhorn CSI Liveness Prob…

### PR DESCRIPTION
**Pull request by weizhe0422**
## Issue: 
https://github.com/longhorn/longhorn/issues/5794

## Problem
The group name of `Longhorn CSI Liveness Probe Image Tag` in `question.yaml` is not correct and it makes the options category to the wrong page.

## Solution
Fix the upstream to make the group name should be Longhorn CSI Driver Images rather than Longhorn CSI Liveness Probe Images

## Testing
 1. Having a K8S cluster
 2. Add repository with https://github.com/weizhe0422/rancher-charts/tree/dev-v2.7_LH_Issue%235794
 3. Try to install Longhorn v1.3.3 and check the `Edit Options
 4. Uncheck `Use Default Images`
 5. The 'Longhorn CSI Liveness Probe Image Tag' should belong to `Longhorn CSI Driver Images` page like below 
    截圖 2023-04-25 下午2 56 33

cc @innobead @PhanLe1010 @khushboo-rancher 

Signed-off-by: Ray Chang <ray.chang@suse.com>

### CODE REVIEW

**Review by innobead — DISMISSED** [review]
LGTM. 

@khushboo-rancher can you help re-validate this?

**Comment by innobead** [comment]
@weizhe0422 I assume we need to do the same change to dev-2.7. It seems Longhorn 1.3.3 has not been released yet, so we can update both.

**Comment by weizhe0422** [comment]
> @weizhe0422 I assume we need to do the same change to dev-2.7. It seems Longhorn 1.3.3 has not been released yet, so we can update both. 
> 
> 
> 
> 

Yes, I have another [PR#2568](https://github.com/rancher/charts/pull/2568) for fixing `dev-2.7`.

**Comment by khushboo-rancher** [comment]
I'm not able to pull the repo in the Rancher. It could be because of the branch name `dev-v2.6_LH_Issue#5794`

`Git clone --depth=1 -n --branch=dev-v2.7_LH_Issue#5794 -- https://github.com/weizhe0422/rancher-charts management-state/git-repo/test-lh/e3d20f6b9e0de4c5f947566d3edeb58782852de08959b8e951fec0ac6786fac3 error: exit status 128, detail: Cloning into 'management-state/git-repo/test-lh/e3d20f6b9e0de4c5f947566d3edeb58782852de08959b8e951fec0ac6786fac3'... warning: Could not find remote branch dev-v2.7_LH_Issue#5794 to clone. fatal: Remote branch dev-v2.7_LH_Issue#5794 not found in upstream origin
--`

**Comment by weizhe0422** [comment]
@khushboo-rancher  

I think the error that happened is indeed related to the branch name because of the `#` character. I refer to this [document](https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names), and I think it can work normally if using single quotes like this: 
```shell
Git clone --depth=1 -n --branch='dev-v2.7_LH_Issue#5794' -- https://github.com/weizhe0422/rancher-charts management-state/git-repo/test-lh/e3d20f6b9e0de4c5f947566d3edeb58782852de08959b8e951fec0ac6786fac3
```
Would you mind using this command and trying it again? Thanks a lot.

**Comment by khushboo-rancher** [comment]
I'm using Rancher UI to pull this. I added the single quotes, still getting the same problem.
`Git clone --depth=1 -n --branch='dev-v2.7_LH_Issue#235794' -- https://github.com/weizhe0422/rancher-charts management-state/git-repo/test-lh/e3d20f6b9e0de4c5f947566d3edeb58782852de08959b8e951fec0ac6786fac3 error: exit status 128, detail: Cloning into 'management-state/git-repo/test-lh/e3d20f6b9e0de4c5f947566d3edeb58782852de08959b8e951fec0ac6786fac3'... warning: Could not find remote branch 'dev-v2.7_LH_Issue#235794' to clone. fatal: Remote branch 'dev-v2.7_LH_Issue#235794' not found in upstream origin`

**Comment by khushboo-rancher** [comment]
Grouping issue looks resolved now. Thanks @weizhe0422

**Comment by PhanLe1010** [comment]
Same as https://github.com/rancher/charts/pull/2568#pullrequestreview-1408373626

**Comment by nicholasSUSE** [comment]
Closed due to inactivity and lack of labels

**Pull request closed without merging**
