### PR TITLE
Add Path_Key for openrc k3s logs

### LINKED ISSUE #1329: [rancher-logging] Add file path to fluentbit config for openrc logs
For k3s openrc logs fluentbit isn't adding any metadata to the logs.  We should include the filepath to identify these logs, and match what we are doing for rke controlplane logs.

### PR DESCRIPTION
**Pull request by dbason**
Fixes #1329

### CODE REVIEW

**Comment by paynejacob** [comment]
@bashofmann is there an issue associated with this? if not can you open one so we can track it.

**Review by paynejacob — DISMISSED** [review]

**Review by nickgerace — APPROVED** [review]

**Comment by nickgerace** [comment]
@dbason we need an associated issue and have it in the description before merging, but this LGTM

**Comment by dbason** [comment]
I've created and issue and updated it now.  I'll rebase and regenerate the charts as well.

**Comment by nickgerace** [comment]
@dbason is this ready for re-review?

**Comment by dbason** [comment]
It was, but it looks like there's another conflict with the chart tarball.  I'll fix that up now

**Review by nickgerace — APPROVED** [review]

**Pull request merged**
