### PR TITLE
Releasing chart for 2.5.17

### PR DESCRIPTION
**Pull request by aiyengar2**

### CODE REVIEW

**Comment by aiyengar2** [comment]
Comparing internal diff to see if any annotations have changed...

**Comment by aiyengar2** [comment]
```bash
$ diff -uNr charts/fleet-agent/fleet-agent/0.3.900+up0.3.9 charts/fleet-agent/fleet-agent/0.3.1000+up0.3.10-security1
```

```diff
diff -uNr charts/fleet-agent/fleet-agent/0.3.900+up0.3.9/Chart.yaml charts/fleet-agent/fleet-agent/0.3.1000+up0.3.10-security1/Chart.yaml
--- charts/fleet-agent/fleet-agent/0.3.900+up0.3.9/Chart.yaml	2023-01-23 15:25:21
+++ charts/fleet-agent/fleet-agent/0.3.1000+up0.3.10-security1/Chart.yaml	2023-01-23 15:49:01
@@ -6,8 +6,8 @@
   catalog.cattle.io/permits-os: linux,windows
   catalog.cattle.io/release-name: fleet-agent
 apiVersion: v2
-appVersion: 0.3.9
+appVersion: 0.3.10-security1
 description: Fleet Manager Agent - GitOps at Scale
 icon: https://charts.rancher.io/assets/logos/fleet.svg
 name: fleet-agent
-version: 0.3.900+up0.3.9
+version: 0.3.1000+up0.3.10-security1
diff -uNr charts/fleet-agent/fleet-agent/0.3.900+up0.3.9/values.yaml charts/fleet-agent/fleet-agent/0.3.1000+up0.3.10-security1/values.yaml
--- charts/fleet-agent/fleet-agent/0.3.900+up0.3.9/values.yaml	2023-01-23 15:25:21
+++ charts/fleet-agent/fleet-agent/0.3.1000+up0.3.10-security1/values.yaml	2023-01-23 15:49:01
@@ -1,7 +1,7 @@
 image:
   os: "windows,linux"
   repository: rancher/fleet-agent
-  tag: v0.3.9
+  tag: v0.3.10-security1

 # The public URL of the Kubernetes API server running the Fleet Manager must be set here
 # Example: https://example.com:6443
```

**Comment by aiyengar2** [comment]
```bash
$ diff -uNr charts/fleet-crd/fleet-crd/0.3.900+up0.3.9 charts/fleet-crd/fleet-crd/0.3.1000+up0.3.10-security1
```

```diff
diff -uNr charts/fleet-crd/fleet-crd/0.3.900+up0.3.9/Chart.yaml charts/fleet-crd/fleet-crd/0.3.1000+up0.3.10-security1/Chart.yaml
--- charts/fleet-crd/fleet-crd/0.3.900+up0.3.9/Chart.yaml	2023-01-23 15:25:21
+++ charts/fleet-crd/fleet-crd/0.3.1000+up0.3.10-security1/Chart.yaml	2023-01-23 15:49:01
@@ -6,8 +6,8 @@
   catalog.cattle.io/permits-os: linux,windows
   catalog.cattle.io/release-name: fleet-crd
 apiVersion: v2
-appVersion: 0.3.9
+appVersion: 0.3.10-security1
 description: Fleet Manager CustomResourceDefinitions
 icon: https://charts.rancher.io/assets/logos/fleet.svg
 name: fleet-crd
-version: 0.3.900+up0.3.9
+version: 0.3.1000+up0.3.10-security1
```

**Comment by aiyengar2** [comment]
```bash
$ diff -uNr charts/fleet/fleet/0.3.900+up0.3.9 charts/fleet/fleet/0.3.1000+up0.3.10-security1
```

```diff
diff -uNr charts/fleet/fleet/0.3.900+up0.3.9/Chart.yaml charts/fleet/fleet/0.3.1000+up0.3.10-security1/Chart.yaml
--- charts/fleet/fleet/0.3.900+up0.3.9/Chart.yaml	2023-01-23 15:25:21
+++ charts/fleet/fleet/0.3.1000+up0.3.10-security1/Chart.yaml	2023-01-23 15:49:01
@@ -9,7 +9,7 @@
   catalog.cattle.io/provides-gvr: clusters.fleet.cattle.io/v1alpha1
   catalog.cattle.io/release-name: fleet
 apiVersion: v2
-appVersion: 0.3.9
+appVersion: 0.3.10-security1
 dependencies:
 - condition: gitops.enabled
   name: gitjob
@@ -17,4 +17,4 @@
 description: Fleet Manager - GitOps at Scale
 icon: https://charts.rancher.io/assets/logos/fleet.svg
 name: fleet
-version: 0.3.900+up0.3.9
+version: 0.3.1000+up0.3.10-security1
diff -uNr charts/fleet/fleet/0.3.900+up0.3.9/charts/gitjob/values.yaml charts/fleet/fleet/0.3.1000+up0.3.10-security1/charts/gitjob/values.yaml
--- charts/fleet/fleet/0.3.900+up0.3.9/charts/gitjob/values.yaml	2023-01-23 15:25:21
+++ charts/fleet/fleet/0.3.1000+up0.3.10-security1/charts/gitjob/values.yaml	2023-01-23 15:49:01
@@ -1,6 +1,6 @@
 gitjob:
   repository: rancher/gitjob
-  tag: v0.1.26
+  tag: v0.1.26-security1

 tekton:
   repository: rancher/tekton-utils
diff -uNr charts/fleet/fleet/0.3.900+up0.3.9/values.yaml charts/fleet/fleet/0.3.1000+up0.3.10-security1/values.yaml
--- charts/fleet/fleet/0.3.900+up0.3.9/values.yaml	2023-01-23 15:25:21
+++ charts/fleet/fleet/0.3.1000+up0.3.10-security1/values.yaml	2023-01-23 15:49:01
@@ -1,11 +1,11 @@
 image:
   repository: rancher/fleet
-  tag: v0.3.9
+  tag: v0.3.10-security1
   imagePullPolicy: IfNotPresent

 agentImage:
   repository: rancher/fleet-agent
-  tag: v0.3.9
+  tag: v0.3.10-security1
   imagePullPolicy: IfNotPresent

 # For cluster registration the public URL of the Kubernetes API server must be set here
```

**Comment by aiyengar2** [comment]
```bash
$ diff -uNr charts/rancher-webhook/rancher-webhook/0.1.500+up0.1.5 charts/rancher-webhook/rancher-webhook/0.1.600+up0.1.6
```

```diff
diff -uNr charts/rancher-webhook/rancher-webhook/0.1.500+up0.1.5/Chart.yaml charts/rancher-webhook/rancher-webhook/0.1.600+up0.1.6/Chart.yaml
--- charts/rancher-webhook/rancher-webhook/0.1.500+up0.1.5/Chart.yaml	2023-01-23 15:25:21
+++ charts/rancher-webhook/rancher-webhook/0.1.600+up0.1.6/Chart.yaml	2023-01-23 15:49:03
@@ -6,7 +6,7 @@
   catalog.cattle.io/rancher-version: <2.5.99-0
   catalog.cattle.io/release-name: rancher-webhook
 apiVersion: v2
-appVersion: 0.1.5
+appVersion: 0.1.6
 description: ValidatingAdmissionWebhook for Rancher types
 name: rancher-webhook
-version: 0.1.500+up0.1.5
+version: 0.1.600+up0.1.6
diff -uNr charts/rancher-webhook/rancher-webhook/0.1.500+up0.1.5/values.yaml charts/rancher-webhook/rancher-webhook/0.1.600+up0.1.6/values.yaml
--- charts/rancher-webhook/rancher-webhook/0.1.500+up0.1.5/values.yaml	2023-01-23 15:25:21
+++ charts/rancher-webhook/rancher-webhook/0.1.600+up0.1.6/values.yaml	2023-01-23 15:49:03
@@ -1,6 +1,6 @@
 image:
   repository: rancher/rancher-webhook
-  tag: v0.1.5
+  tag: v0.1.6
   imagePullPolicy: IfNotPresent

 global:
```

**Comment by aiyengar2** [comment]
Diffs look good

**Comment by aiyengar2** [comment]
Checked to see if contents contained within asset tgz files is identical to what was verified in the charts directory...

Ran the following commands:
```bash
tar -xvf assets/fleet-agent/fleet-agent-0.3.1000+up0.3.10-security1.tgz && diff -uNr fleet-agent charts/fleet-agent/fleet-agent/0.3.1000+up0.3.10-security1 && rm -rf fleet-agent
tar -xvf assets/fleet-crd/fleet-crd-0.3.1000+up0.3.10-security1.tgz && diff -uNr fleet-crd charts/fleet-crd/fleet-crd/0.3.1000+up0.3.10-security1 && rm -rf fleet-crd
tar -xvf assets/fleet/fleet-0.3.1000+up0.3.10-security1.tgz && diff -uNr fleet charts/fleet/fleet/0.3.1000+up0.3.10-security1 && rm -rf fleet
tar -xvf assets/rancher-webhook/rancher-webhook-0.1.600+up0.1.6.tgz && diff -uNr rancher-webhook charts/rancher-webhook/rancher-webhook/0.1.600+up0.1.6 && rm -rf rancher-webhook
```

No diffs were produced. LGTM

**Comment by aiyengar2** [comment]
Pulled in charts-build-scripts v0.4.0 and ran `./bin/charts-build-scripts index`; no changes were observed. This means the index.yaml is up-to-date.

Also looked over the index.yaml annotations manually and didn't catch any issues.

**Review by aiyengar2 — COMMENTED** [review]
With the above comments, we know that:
1. (manually verified) The charts that are in this PR are the only ones that are intended to be released. They are all the latest of their own release line; no versions are released currently that are ahead of them.
2. (diff commands) The changes introduced from the last released version of each chart to the current version are valid; no changes to annotations and no logical changes that might cause issues. **charts directory is valid**
3. (tar commands) The contents of the charts that we have assured match the contents of assets. **assets directory is valid**
4. (./bin/charts-build-scripts index) The contents of assets matches the contents of the index.yaml. Digests are up-to-date
5. (manually verified) The new charts in the index.yaml have the correct annotations.

LGTM

**Comment by prachidamle** [comment]
@aiyengar2 will the "-security1" suffix in the fleet images cause problem?

**Review by geethub97 — APPROVED** [review]

**Comment by aiyengar2** [comment]
> @aiyengar2 will the "-security1" suffix in the fleet images cause problem?

As far as I know, there shouldn't be any issue

**Pull request merged**
