### PR TITLE
Add sync action to sync branch betweem dev-v2.5 and gh-pages

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
@deniseschannon This adds the ability to auto-sync between contents of dev-v2.5 and gh-pages. This is needed to publish charts on gh-pages.

**Comment by deniseschannon** [comment]
@StrongMonkey what happens when we finally publish 2.5? I feel like we have a gap missing on how we're going to handle somethings.

What exactly does gh-pages do?

**Comment by StrongMonkey** [comment]
https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site @deniseschannon Github page only allows to build on gh-pages branch / master branch/ master branch on docs/ folder. This is just to sync the content to gh-pages branch so we can publish github chart. Atfer we publish 2.5 we can sync between 2.5 and gh-pages.

**Comment by StrongMonkey** [comment]
No longer needed

**Pull request closed without merging**
