### PR TITLE
[release-v2.6] Releasing chart

### PR DESCRIPTION
**Pull request by kinarashah**
Followed the steps mentioned here https://github.com/rancher/charts/tree/release-v2.6#cutting-a-release, except for the last step had to `git push -f origin release-v2.6.0`. 

Reviewers: 
From the checklist mentioned, 

- [ ] The assets/ and charts/ directories have been updated to match the Staging branch. All entires should be additions, not modifications.

I see a few modifications, but they're README.md changes, is that expected?  

- [ ] The index.yaml's diff shows only adds additional entries and does not modify or remove existing ones.
I see a few created TS modifications, like: 
```
-    created: "2021-07-19T16:27:00.084358-07:00"
+    created: "2021-08-06T16:57:34.002248452-07:00"
```

### CODE REVIEW

**Comment by aiyengar2** [comment]
### Update on Checklist

#### Fixed

> #### rancher-istio
> NEEDS TO CHANGE: Based on [rancher/rancher#32294](https://github.com/rancher/rancher/issues/32294), only 100.0.0+up1.10.4 should exist. Additional chart 1.8.601 needs to be removed or replaced with a 100.0.0+up1.8.601 version.

Addressed by https://github.com/rancher/charts/pull/1441.

> #### fleet
> NEEDS TO CHANGE: version still shows 100.0.0+up0.3.6-rc13
> 
> NEEDS TO CHANGE: appVersion still shows 0.3.6-rc13
> 
> NEEDS TO CHANGE: rancher/fleet image still shows v0.3.6-rc13

Addressed by https://github.com/rancher/charts/pull/1447.

> #### fleet-agent
> NEEDS TO CHANGE: version still shows 100.0.0+up0.3.6-rc13
> 
> NEEDS TO CHANGE: appVersion still shows 0.3.6-rc13
> 
> NEEDS TO CHANGE: rancher/fleet-agent image still shows v0.3.6-rc13

Addressed by https://github.com/rancher/charts/pull/1447.

> #### fleet-crd
> NEEDS TO CHANGE: version still shows 100.0.0+up0.3.6-rc13
> 
> NEEDS TO CHANGE: appVersion still shows 0.3.6-rc13

Addressed by https://github.com/rancher/charts/pull/1447.

> #### rancher-cis-benchmark
> NEEDS TO CHANGE: rancher/cis-operator image still shows v1.0.5-rc2

Addressed by https://github.com/rancher/charts/pull/1446.

> #### rancher-webhook
> 
> NEEDS TO CHANGE: Version 1.0.0+up0.2.0-beta06 seems to indicate we are using a beta upstream version; this should be fixed.
> 
> NEEDS TO CHANGE: Image rancher/rancher-webhook is using v0.2.0-beta06

Bumped in https://github.com/rancher/charts/pull/1444 to 07 and addressed in https://github.com/rancher/charts/pull/1449.


---

#### Pending

Waiting on Caleb to verify all my comments on [#1430 (comment)](https://github.com/rancher/charts/pull/1430#issuecomment-906721604)

#### rancher-backup
NEEDS TO CHANGE: version still shows 2.0.0+up2.0.0-rc11

NEEDS TO CHANGE: appVersion still shows 2.0.0-rc11

NEEDS TO CHANGE: rancher/backup-restore-operator image still uses v2.0.0-rc11

#### rancher-backup-crd
NEEDS TO CHANGE: version still shows 2.0.0+up2.0.0-rc11

NEEDS TO CHANGE: appVersion still shows 2.0.0-rc11

#### rancher-external-ip-webhook
NEEDS TO CHANGE: Version should be 100+up0.1.601 based on offline conversation. cc: @cmurphy

**Comment by aiyengar2** [comment]
Also pending a change from https://github.com/rancher/charts/pull/1448; this only changes the chart's contents, not the index.yaml. So it should not require anything more to review.

**Comment by PennyScissors** [comment]
Pending change from https://github.com/rancher/charts/pull/1451 to port the changes done in CPI to CSI; this only changes the chart's content, not the index.yaml.

**Review by cbron — CHANGES_REQUESTED** [review]
@kinarashah I think you need to remake this again, deleted charts like external-ip-webhook 1.0.0 or istio 1.8.601 are still here.

**Comment by aiyengar2** [comment]
### Update on Checklist

> #### rancher-backup
> NEEDS TO CHANGE: version still shows 2.0.0+up2.0.0-rc11
> 
> NEEDS TO CHANGE: appVersion still shows 2.0.0-rc11
> 
> NEEDS TO CHANGE: rancher/backup-restore-operator image still uses v2.0.0-rc11

Fixed in https://github.com/rancher/charts/pull/1452. Version changes to 2.0.0 instead since it matches upstream, and index.yaml was appropriately changed.

> #### rancher-backup-crd
> NEEDS TO CHANGE: version still shows 2.0.0+up2.0.0-rc11
> 
> NEEDS TO CHANGE: appVersion still shows 2.0.0-rc11

Fixed in https://github.com/rancher/charts/pull/1452.

No changes to the index.yaml introduced in https://github.com/rancher/charts/pull/1451.

---

charts/ and assets/ changes LGTM. Doing one final check of the index.yaml for approval...

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
These mode changes (not sure where they came from?) need to be undone:
- `assets/fleet-agent/fleet-agent-0.3.000.tgz`
- `charts/fleet-agent/fleet-agent/0.3.000/Chart.yaml`

I wasn't able to view the **whole** charts/ diff so there could be more dummy mode changes made.

@kinarashah can you undo with the following script?

```bash
git diff -p --diff-filter=ACM \
    | grep -E '^(diff|old mode|new mode)' \
    | sed -e 's/^old/NEW/;s/^new/old/;s/^NEW/new/' \
    | git apply
```

**Comment by aiyengar2** [comment]
index.yaml changes LGTM. Every added entry to the index.yaml matches the chart name + version that was expected to be released in https://github.com/rancher/rancher/issues/32294. No additional changes have been added.

Once we take care of the mode change for the above files, I think this PR is ready for a LGTM.

**Comment by kinarashah** [comment]
Pushed changes to remove mode changes.

**Review by aiyengar2 — APPROVED** [review]
LGTM 🥳

**Review by cbron — APPROVED** [review]
Lgtm
* Problems outlined earlier have been fixed
* I don't see any rc versions
* Chart versions match the github issue
* I don't see any unecessary charts that should be deleted
* We'll handle min/max in 2.6.1

**Pull request merged**
