### PR TITLE
Add Longhorn 1.4.2 chart with dev-2.7

### PR DESCRIPTION
**Pull request by weizhe0422**
[Longhorn 5864](https://github.com/longhorn/longhorn/issues/5864)

Signed-off-by: Ray Chang [ray.chang@suse.com]

cc @innobead @PhanLe1010 @khushboo-rancher

### CODE REVIEW

**Review by rohitsakala — APPROVED** [review]
LGTM. Will wait for other approvals and testing, QA.

**Comment by khushboo-rancher** [comment]
Validation - LGTM with longhornio images. 
**Note:** https://github.com/rancher/image-mirror/pull/391 needs to be merged before this PR gets merged, otherwise things will not work

**Review by khushboo-rancher — APPROVED** [review]

**Comment by PhanLe1010** [comment]
I am reviewing now. Sorry for the delay

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by rohitsakala** [comment]
@PhanLe1010 Is this good to merge ?

**Comment by PhanLe1010** [comment]
@rohitsakala yes, it is good to merge. Thank you very much

**Comment by Turb0Fly** [comment]
This still does not list Longhorn 1.4.2 in the release-v2.7 branch.  From Rancher 2.7.3, we still can only deploy or upgrade up to Longhorn 1.4.1.  When can we expect a merge into release-v2.7 ?

**Comment by PhanLe1010** [comment]
It should be available on release-v2.7 now

**Pull request merged**
