### PR TITLE
[dev-v2.6] add -root to logging root cr

### PR DESCRIPTION
**Pull request by superseb**
https://github.com/rancher/rancher/issues/35125

The Deployment `rancher-logging` using image `rancher/mirrored-banzaicloud-logging-operator:3.15.0` will start a controller that will use the name of the created `Logging` CR, to reconcile configured resources. Because that name defaults to `rancher-logging`, the controller "reconciles" (aka deletes) the ClusterRole and ClusterRoleBinding called `rancher-logging-fluentd` used by v1 logging. By renaming the CR to `$RELEASENAME-root`, the conflict is resolved and the resources are untouched.

### CODE REVIEW

**Comment by brendarearden** [comment]
is this going to cause issues on rancher-logging upgrade for existing deployments?

**Comment by superseb** [comment]
I have ran upgrade test using the current and this new chart, and the current logging CR gets deleted and the new one gets deployed. I think this is expected and the other scenarios can be covered by QA testing.

**Review by brendarearden — APPROVED** [review]
lgtm

**Comment by superseb** [comment]
Superseded by https://github.com/rancher/charts/pull/1729

**Pull request closed without merging**
