### PR TITLE
[instana-agent v1.0.17] Update the instana/agent image to 1.0.28. Use serviceAccountName instead of serviceAccount in daemonset.yaml

### PR DESCRIPTION
**Pull request by dlbock**
This updates the version of the `instana/agent` Docker image to the latest one available 1.0.28: https://hub.docker.com/r/instana/agent/tags

Also update `daemonset.yaml` to use `serviceAccountName` instead of the deprecated `serviceAccount` within `apps.v1.DaemonSetSpec.template.spec`. This has been deprecated since k8s 1.10: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#podspec-v1-core

### CODE REVIEW

**Comment by dlbock** [comment]
Because we essentially have to create a new versioned folder for every update, here's the diff:

```
diff -r charts/instana-agent/v1.0.16/Chart.yaml charts/instana-agent/v1.0.17/Chart.yaml
3c3
< version: 1.0.16
---
> version: 1.0.17

diff -r charts/instana-agent/v1.0.16/README.md charts/instana-agent/v1.0.17/README.md
91c91
< | `agent.image.tag`                  | The image tag to pull                                                   | `1.0.17`                                                                                                    |
---
> | `agent.image.tag`                  | The image tag to pull                                                   | `1.0.28`                                                                                                    |

diff -r charts/instana-agent/v1.0.16/questions.yml charts/instana-agent/v1.0.17/questions.yml
67c67
<     default: "1.0.17"
---
>     default: "1.0.28"

diff -r charts/instana-agent/v1.0.16/templates/daemonset.yaml charts/instana-agent/v1.0.17/templates/daemonset.yaml
22c22
<       serviceAccount: {{ template "instana-agent.serviceAccountName" . }}
---
>       serviceAccountName: {{ template "instana-agent.serviceAccountName" . }}

diff -r charts/instana-agent/v1.0.16/values.yaml charts/instana-agent/v1.0.17/values.yaml
29c29
<     tag: 1.0.17
---
>     tag: 1.0.28
```

**Comment by dlbock** [comment]
@guangbochen Need help reviewing & merging this change

**Comment by guangbochen** [comment]
@dlbock can u please reabse to the upstream/parterns branch and that's where we are going to test partner catalogs from, so the changes aren't held back with other charts, thanks.

```
and for submitting a new version can u please add two commits for it:
1. base code 1.0.16 to 1.0.17
2. commit for updated changes
```

thanks

**Comment by dlbock** [comment]
@guangbochen Done! Are these instructions written down somewhere that I missed?

**Comment by guangbochen** [comment]
LGTM, @dlbock we are working on the instruction as recently we are refactoring the procedure, thanks for bearing with us and will have them released soon, thanks.

@deniseschannon Can u PTAL and merge this PR, thanks.

**Comment by dlbock** [comment]
@guangbochen okay, no worries. I thought I had missed some documentation somewhere. Thanks for the quick turnaround on this, as Github says you're in Sydney, so the timezones are also playing a part in all this 😄

**Pull request merged**
