### PR TITLE
[v2.5.6] Release Charts

### PR DESCRIPTION
**Pull request by ryansann**
PR to release feature charts for Rancher v2.5.6

Issue:
- https://github.com/rancher/rancher/issues/30888

`make sync` output:
```json
{
 "fleet-agent/0.3.400": "fleet-agent/0.3.400-rc07",
 "fleet-crd/0.3.400": "fleet-crd/0.3.400-rc07",
 "fleet/0.3.400": "fleet/0.3.400-rc07",
 "longhorn-crd/1.1.001": "longhorn-crd/1.1.001-rc01",
 "longhorn/1.1.001": "longhorn/1.1.001-rc01",
 "rancher-backup-crd/1.0.301": "rancher-backup-crd/1.0.301-rc01",
 "rancher-backup/1.0.301": "rancher-backup/1.0.301-rc01",
 "rancher-cis-benchmark-crd/1.0.301": "rancher-cis-benchmark-crd/1.0.301-rc01",
 "rancher-cis-benchmark/1.0.301": "rancher-cis-benchmark/1.0.301-rc01",
 "rancher-external-ip-webhook/0.1.601": "rancher-external-ip-webhook/0.1.601-rc01",
 "rancher-gatekeeper-crd/3.3.000": "rancher-gatekeeper-crd/3.3.000-rc02",
 "rancher-gatekeeper/3.3.000": "rancher-gatekeeper/3.3.000-rc02",
 "rancher-istio/1.8.300": "rancher-istio/1.8.300-rc01",
 "rancher-kiali-server-crd/1.29.000": "rancher-kiali-server-crd/1.29.000-rc01",
 "rancher-kiali-server/1.29.000": "rancher-kiali-server/1.29.000-rc01",
 "rancher-logging-crd/3.9.000": "rancher-logging-crd/3.9.000-rc08",
 "rancher-logging/3.9.000": "rancher-logging/3.9.000-rc08",
 "rancher-monitoring-crd/9.4.203": "rancher-monitoring-crd/9.4.203-rc04",
 "rancher-monitoring/9.4.203": "rancher-monitoring/9.4.203-rc04",
 "rancher-operator-crd/0.1.300": "rancher-operator-crd/0.1.300-rc07",
 "rancher-operator/0.1.300": "rancher-operator/0.1.300-rc07",
 "rancher-pushprox/0.1.201": "rancher-pushprox/0.1.201-rc02",
 "rancher-tracing/1.20.001": "rancher-tracing/1.20.001-rc00",
 "rancher-tracing/1.20.002": "rancher-tracing/1.20.002-rc00",
 "rancher-webhook/0.1.0-beta901": "rancher-webhook/0.1.0-beta901-rc00",
 "rio/0.8.001": "rio/0.8.001-rc00"
} 

```

### CODE REVIEW

**Review by luthermonson — APPROVED** [review]

**Comment by ryansann** [comment]
Charts included in `make sync` output that are not in [the new charts for v2.5.6 issue](rancher/rancher#30888):
```
- longhorn-crd/1.1.001
- rancher-backup-crd/1.0.301
- rancher-cis-benchmark-crd/1.0.301
- rancher-gatekeeper-crd/3.3.000
- rancher-kiali-server-crd/1.29.000 (NOTE: Kiali is named differently in the issue)
- rancher-logging-crd/3.9.000
- rancher-monitoring-crd/9.4.203
```
These are probably acceptable as they are all CRD related

NOTE: the output above has two entries for `rancher-tracing`:
```
"rancher-tracing/1.20.001": "rancher-tracing/1.20.001-rc00",
 "rancher-tracing/1.20.002": "rancher-tracing/1.20.002-rc00",
```

**Comment by cbron** [comment]
@aiyengar2 can we update this now ? To fix tracing double chart.

**Comment by aiyengar2** [comment]
Once https://github.com/rancher/charts/pull/1014 is merged, we are ready to update

**Comment by ryansann** [comment]
New `make sync` output:
```
Found the following latest release candidate versions: {
 "fleet-agent/0.3.400": "fleet-agent/0.3.400-rc08",
 "fleet-crd/0.3.400": "fleet-crd/0.3.400-rc08",
 "fleet/0.3.400": "fleet/0.3.400-rc08",
 "longhorn-crd/1.1.001": "longhorn-crd/1.1.001-rc01",
 "longhorn/1.1.001": "longhorn/1.1.001-rc01",
 "rancher-backup-crd/1.0.301": "rancher-backup-crd/1.0.301-rc01",
 "rancher-backup/1.0.301": "rancher-backup/1.0.301-rc01",
 "rancher-cis-benchmark-crd/1.0.301": "rancher-cis-benchmark-crd/1.0.301-rc01",
 "rancher-cis-benchmark/1.0.301": "rancher-cis-benchmark/1.0.301-rc01",
 "rancher-external-ip-webhook/0.1.601": "rancher-external-ip-webhook/0.1.601-rc01",
 "rancher-gatekeeper-crd/3.3.000": "rancher-gatekeeper-crd/3.3.000-rc02",
 "rancher-gatekeeper/3.3.000": "rancher-gatekeeper/3.3.000-rc02",
 "rancher-istio/1.8.300": "rancher-istio/1.8.300-rc01",
 "rancher-kiali-server-crd/1.29.000": "rancher-kiali-server-crd/1.29.000-rc01",
 "rancher-kiali-server/1.29.000": "rancher-kiali-server/1.29.000-rc01",
 "rancher-logging-crd/3.9.000": "rancher-logging-crd/3.9.000-rc08",
 "rancher-logging/3.9.000": "rancher-logging/3.9.000-rc08",
 "rancher-monitoring-crd/9.4.203": "rancher-monitoring-crd/9.4.203-rc04",
 "rancher-monitoring/9.4.203": "rancher-monitoring/9.4.203-rc04",
 "rancher-operator-crd/0.1.300": "rancher-operator-crd/0.1.300-rc08",
 "rancher-operator/0.1.300": "rancher-operator/0.1.300-rc08",
 "rancher-pushprox/0.1.201": "rancher-pushprox/0.1.201-rc02",
 "rancher-tracing/1.20.002": "rancher-tracing/1.20.002-rc00",
 "rancher-webhook/0.1.0-beta901": "rancher-webhook/0.1.0-beta901-rc00",
 "rio/0.8.001": "rio/0.8.001-rc00"
} 
```

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Review by cbron — APPROVED** [review]
lgtm, but wait to merge until final RC is ready to go including system charts

**Comment by cbron** [comment]
Adding @deniseschannon in case she wants to review

**Comment by deniseschannon** [comment]
I'll leave the reviews to the rest of you for this. :)

**Comment by deniseschannon** [comment]
@ryansann We need to re-run this for the new vSphere charts.

**Comment by ryansann** [comment]
New `make sync` output:
```json
{
 "fleet-agent/0.3.400": "fleet-agent/0.3.400-rc08",
 "fleet-crd/0.3.400": "fleet-crd/0.3.400-rc08",
 "fleet/0.3.400": "fleet/0.3.400-rc08",
 "longhorn-crd/1.1.001": "longhorn-crd/1.1.001-rc01",
 "longhorn/1.1.001": "longhorn/1.1.001-rc01",
 "rancher-backup-crd/1.0.301": "rancher-backup-crd/1.0.301-rc01",
 "rancher-backup/1.0.301": "rancher-backup/1.0.301-rc01",
 "rancher-cis-benchmark-crd/1.0.301": "rancher-cis-benchmark-crd/1.0.301-rc01",
 "rancher-cis-benchmark/1.0.301": "rancher-cis-benchmark/1.0.301-rc01",
 "rancher-external-ip-webhook/0.1.601": "rancher-external-ip-webhook/0.1.601-rc01",
 "rancher-gatekeeper-crd/3.3.000": "rancher-gatekeeper-crd/3.3.000-rc02",
 "rancher-gatekeeper/3.3.000": "rancher-gatekeeper/3.3.000-rc02",
 "rancher-istio/1.8.300": "rancher-istio/1.8.300-rc01",
 "rancher-kiali-server-crd/1.29.000": "rancher-kiali-server-crd/1.29.000-rc01",
 "rancher-kiali-server/1.29.000": "rancher-kiali-server/1.29.000-rc01",
 "rancher-logging-crd/3.9.000": "rancher-logging-crd/3.9.000-rc08",
 "rancher-logging/3.9.000": "rancher-logging/3.9.000-rc08",
 "rancher-monitoring-crd/9.4.203": "rancher-monitoring-crd/9.4.203-rc04",
 "rancher-monitoring/9.4.203": "rancher-monitoring/9.4.203-rc04",
 "rancher-operator-crd/0.1.300": "rancher-operator-crd/0.1.300-rc08",
 "rancher-operator/0.1.300": "rancher-operator/0.1.300-rc08",
 "rancher-pushprox/0.1.201": "rancher-pushprox/0.1.201-rc02",
 "rancher-tracing/1.20.002": "rancher-tracing/1.20.002-rc00",
 "rancher-webhook/0.1.0-beta901": "rancher-webhook/0.1.0-beta901-rc00",
 "rio/0.8.001": "rio/0.8.001-rc00",
 "vsphere-cpi/1.0.000": "vsphere-cpi/1.0.000-rc00",
 "vsphere-csi/2.1.000": "vsphere-csi/2.1.000-rc00"
}
```

**Comment by ryansann** [comment]
New `make sync` output:
```json
{
 "fleet-agent/0.3.400": "fleet-agent/0.3.400-rc08",
 "fleet-crd/0.3.400": "fleet-crd/0.3.400-rc08",
 "fleet/0.3.400": "fleet/0.3.400-rc08",
 "longhorn-crd/1.1.001": "longhorn-crd/1.1.001-rc01",
 "longhorn/1.1.001": "longhorn/1.1.001-rc01",
 "rancher-backup-crd/1.0.301": "rancher-backup-crd/1.0.301-rc01",
 "rancher-backup/1.0.301": "rancher-backup/1.0.301-rc01",
 "rancher-cis-benchmark-crd/1.0.301": "rancher-cis-benchmark-crd/1.0.301-rc01",
 "rancher-cis-benchmark/1.0.301": "rancher-cis-benchmark/1.0.301-rc01",
 "rancher-external-ip-webhook/0.1.601": "rancher-external-ip-webhook/0.1.601-rc01",
 "rancher-gatekeeper-crd/3.3.000": "rancher-gatekeeper-crd/3.3.000-rc02",
 "rancher-gatekeeper/3.3.000": "rancher-gatekeeper/3.3.000-rc02",
 "rancher-istio/1.8.300": "rancher-istio/1.8.300-rc01",
 "rancher-kiali-server-crd/1.29.000": "rancher-kiali-server-crd/1.29.000-rc01",
 "rancher-kiali-server/1.29.000": "rancher-kiali-server/1.29.000-rc01",
 "rancher-logging-crd/3.9.000": "rancher-logging-crd/3.9.000-rc08",
 "rancher-logging/3.9.000": "rancher-logging/3.9.000-rc08",
 "rancher-monitoring-crd/9.4.203": "rancher-monitoring-crd/9.4.203-rc04",
 "rancher-monitoring/9.4.203": "rancher-monitoring/9.4.203-rc04",
 "rancher-operator-crd/0.1.300": "rancher-operator-crd/0.1.300-rc08",
 "rancher-operator/0.1.300": "rancher-operator/0.1.300-rc08",
 "rancher-pushprox/0.1.201": "rancher-pushprox/0.1.201-rc02",
 "rancher-tracing/1.20.002": "rancher-tracing/1.20.002-rc00",
 "rancher-webhook/0.1.0-beta901": "rancher-webhook/0.1.0-beta901-rc00",
 "rio/0.8.001": "rio/0.8.001-rc00",
 "vsphere-cpi/1.0.000": "vsphere-cpi/1.0.000-rc01",
 "vsphere-csi/2.1.000": "vsphere-csi/2.1.000-rc01"
}
```

**Comment by ryansann** [comment]
New `make sync` output:
```json
{
 "fleet-agent/0.3.400": "fleet-agent/0.3.400-rc08",
 "fleet-crd/0.3.400": "fleet-crd/0.3.400-rc08",
 "fleet/0.3.400": "fleet/0.3.400-rc08",
 "longhorn-crd/1.1.001": "longhorn-crd/1.1.001-rc01",
 "longhorn/1.1.001": "longhorn/1.1.001-rc01",
 "rancher-backup-crd/1.0.301": "rancher-backup-crd/1.0.301-rc01",
 "rancher-backup/1.0.301": "rancher-backup/1.0.301-rc01",
 "rancher-cis-benchmark-crd/1.0.301": "rancher-cis-benchmark-crd/1.0.301-rc01",
 "rancher-cis-benchmark/1.0.301": "rancher-cis-benchmark/1.0.301-rc01",
 "rancher-external-ip-webhook/0.1.601": "rancher-external-ip-webhook/0.1.601-rc01",
 "rancher-gatekeeper-crd/3.3.000": "rancher-gatekeeper-crd/3.3.000-rc02",
 "rancher-gatekeeper/3.3.000": "rancher-gatekeeper/3.3.000-rc02",
 "rancher-istio/1.8.300": "rancher-istio/1.8.300-rc01",
 "rancher-kiali-server-crd/1.29.000": "rancher-kiali-server-crd/1.29.000-rc01",
 "rancher-kiali-server/1.29.000": "rancher-kiali-server/1.29.000-rc01",
 "rancher-logging-crd/3.9.000": "rancher-logging-crd/3.9.000-rc08",
 "rancher-logging/3.9.000": "rancher-logging/3.9.000-rc08",
 "rancher-monitoring-crd/9.4.203": "rancher-monitoring-crd/9.4.203-rc04",
 "rancher-monitoring/9.4.203": "rancher-monitoring/9.4.203-rc04",
 "rancher-operator-crd/0.1.300": "rancher-operator-crd/0.1.300-rc08",
 "rancher-operator/0.1.300": "rancher-operator/0.1.300-rc08",
 "rancher-pushprox/0.1.201": "rancher-pushprox/0.1.201-rc02",
 "rancher-tracing/1.20.002": "rancher-tracing/1.20.002-rc00",
 "rancher-vsphere-cpi/1.0.000": "rancher-vsphere-cpi/1.0.000-rc01",
 "rancher-vsphere-csi/2.1.000": "rancher-vsphere-csi/2.1.000-rc01",
 "rancher-webhook/0.1.0-beta901": "rancher-webhook/0.1.0-beta901-rc00",
 "rio/0.8.001": "rio/0.8.001-rc00"
}
```

**Review by cbron — APPROVED** [review]
lgtm

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Pull request merged**
