### PR TITLE
Fix/issue 33046

### PR DESCRIPTION
**Pull request by paynejacob**
https://github.com/rancher/rancher/issues/33046
https://github.com/rancher/rancher/issues/33328

some of the timestamp parsers were incorrect.

### CODE REVIEW

**Comment by snasovich** [comment]
@paynejacob , can we change parsers outright here too? Any chance of breaking something that's currently working?

**Comment by paynejacob** [comment]
@snasovich The parsers were introduced for this release and have not been out yet.  There may be considerations in the future if new versions of k3s and such have new log formats.  Logging may need stricter rancher version compatibility if that is the case.

**Review by snasovich — APPROVED** [review]
The changes look OK to me, but consider this as "advisory review" approval. :)

**Review by nickgerace — APPROVED** [review]

**Review by cbron — APPROVED** [review]
lgtm as long as this works with all cases. Also next time can we title a PR like this "update k3s log format" or something more specific

**Pull request merged**
