### PR TITLE
changed the k8s registry url for certain k8s versions. Px version updated

### PR DESCRIPTION
**Pull request by trierra**

### CODE REVIEW

**Review by harsh-px — APPROVED** [review]

**Comment by harsh-px** [comment]
@PennyScissors  Can you help merge this? Thanks!

**Comment by harsh-px** [comment]
@PennyScissors just checking if you a change to look at this? Thanks !

This is required for us to support Kubernetes 1.18.

**Comment by PennyScissors** [comment]
@harsh-px I apologize, I haven't had a chance to review this, but I'll make sure to get this done by next week.

**Review by PennyScissors — APPROVED** [review]
lgtm

**Pull request merged**
