### PR TITLE
 delay during postStart if directory is not created by flexvolume driver

### PR DESCRIPTION
**Pull request by raunakkumar**
Signed-off-by: Raunak Kumar <rkumar@nimblestorage.com>

### CODE REVIEW

**Comment by shivamerla** [comment]
@guangbochen can you take a look at this please?

**Comment by guangbochen** [comment]
@shivamerla can u please help to rebase to the `master` branch and I will review it, thanks.

**Comment by raunakkumar** [comment]
Hi @guangbochen I have another PR  https://github.com/rancher/charts/pull/355 for the master branch but our previous chart version (3.0.0) doesn't exist in master but only in partners.

**Comment by guangbochen** [comment]
Hi @raunakkumar, I think the init version that you guys have submitted of `hpe-flexvolume` chart is `v3.1.0`, if PR #355 is the correct one please help to update the commits using 2 commits:
1. base copy v3.1.0 to v3.1.1
2. overwrite v3.1.0 with updated changes
Thanks

**Comment by raunakkumar** [comment]
Hi @guangbochen I had opened this PR wrt partners branch. Is there any reason you had changed it to master? We would want to have this PR with base branch partners

**Comment by guangbochen** [comment]
@raunakkumar partner branch is not synced, you need to submit the PR against the master branch, thanks.

**Comment by guangbochen** [comment]
I have set the base branch of this PR to master, can u please help to rebase it, also Rancher's catalog uses master, thanks.

**Comment by raunakkumar** [comment]
Our previous version of the chart only exists in the partners branch and not in master branch so we would want to have upgrade available from partners branch. Hope that helps

**Comment by guangbochen** [comment]
can u please cherry-pick it from the partner branch as the `partner` branch will be overwritten by the master in final sync, thanks.

**Comment by raunakkumar** [comment]
The cherry pick of this commit to master would not work as it will have only v3.1.1 and not v3.1.0.
By when is the sync going to happen ? 
We are looking for the fix within 2 weeks.

Would it be preferable for just have a single commit in master with both v3.1.0 and v3.1.1 ?

**Comment by raunakkumar** [comment]
Hi @guangbochen  Please review the PR https://github.com/rancher/charts/pull/360 for master. Hope this alleviates your concerns.

**Comment by guangbochen** [comment]
close in favor of #360, thanks

**Pull request closed without merging**
