### PR TITLE
Release 5.0.0-rc1 | Bump security scan to v0.2.13 | Remove 4.2.0-rc1

### PR DESCRIPTION
**Pull request by chiukapoor**
## Issue:
- https://github.com/rancher/rancher/issues/41787

## Solution:
- Bump security scan to v0.2.13
- Bump kubectl to v1.28.1
- Remove 4.2.0-rc1
- Release 5.0.0-rc1

## Testing:
- `make validate` pass

### CODE REVIEW

**Comment by chiukapoor** [comment]
cc: @rayandas @mitulshah-suse

**Comment by Priyashetty17** [comment]
@rayandas @mitulshah-suse Should we also bump kubectl from v1.26.3 to **v1.28.1** [here](https://github.com/rancher/charts/blob/b6ddc03a8ae8e4ecfda62ca3c7d21306c103245f/packages/rancher-cis-benchmark/charts/values.yaml#L50)?  

Reference: https://github.com/rancher/security-scan/pull/160

cc @andypitcher

**Comment by rayandas** [comment]
@Priyashetty17 Yeah, we can bump it here as well. It shouldn't be a problem.

**Comment by chiukapoor** [comment]
Bumped kubectl to v1.28.1 @Priyashetty17

**Review by andypitcher — APPROVED** [review]
LGTM.

**Pull request merged**
