### PR TITLE
[instana-agent] Chart version 1.0.31

### PR DESCRIPTION
**Pull request by dlbock**
#### What this PR does / why we need it:

- Introducing the option to configure and report to multiple Instana backends
- Additional documentation and cleanup on the README

### CODE REVIEW

**Comment by dlbock** [comment]
cc @PennyScissors

**Comment by dlbock** [comment]
@PennyScissors @deniseschannon Could I get this merged soon? I have another change coming up that a customer recently requested for. Thanks!

**Comment by dlbock** [comment]
Bumping this again @PennyScissors @deniseschannon

**Review by PennyScissors — APPROVED** [review]
lgtm

**Pull request merged**
