### PR TITLE
update system-upgrade-controller to v0.7.1

### PR DESCRIPTION
**Pull request by kinarashah**

### CODE REVIEW

**Review by superseb — APPROVED** [review]
I assume we are using the same chart version because its unreleased?

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Comment by kinarashah** [comment]
@superseb thanks for bringing this up, I wasn't sure either but @aiyengar2 confirmed that for charts like system-upgrade-controller that are directly checked into the repo - we can just update `/packages/${PACKAGE}/charts/values.yaml` and update index with `make charts`.

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/32904

**Pull request merged**
