### PR TITLE
removed k3s syslog parser

### PR DESCRIPTION
**Pull request by paynejacob**
syslog is not a valid parser

### CODE REVIEW

**Comment by paynejacob** [comment]
https://github.com/rancher/rancher/issues/28584

**Comment by brendarearden** [comment]
I think you also need to delete the tgz

**Review by cbron — APPROVED** [review]

**Comment by cbron** [comment]
Oh yea, Brenda is right, delete tgz

**Review by cbron — APPROVED** [review]

**Comment by cbron** [comment]
@paynejacob Did the tgz never get deleted ? The logging image still being upstream is one of 2 things blocking airgap installs.

**Pull request merged**
