### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by StrongMonkey**
After new fleet release, fleet-agent and fleet-crd charts are not updated correctly
https://github.com/rancher/fleet/issues/94

### CODE REVIEW

**Comment by StrongMonkey** [comment]
@cbron @aiyengar2 The xargs doesn't seem to work if multiple charts are changed, switch to for loop which seems to be more reliable. If you guys have any clue on xargs please let me know. This is to fix https://github.com/rancher/charts/runs/1162981323 where three charts are changed but only one chart is uploaded

**Review by aiyengar2 — APPROVED** [review]

**Comment by aiyengar2** [comment]
For future reference, this change was required since `./scripts/ci` only supports one argument based on: https://github.com/rancher/charts/blob/286df602a2af2b82ea9e52d1ca4d013f40f04718/scripts/ci#L5-L7.

xargs would pass in the charts as `$1`, `$2`, `$3`, etc. so using a for loop is necessary instead.

**Review by prachidamle — APPROVED** [review]
LGTM

**Comment by StrongMonkey** [comment]
The space change in the second commit is to change content so that chart can be reuploaded.

**Review by cbron — APPROVED** [review]
Spaces in package.yaml are to force a push. LGTM.

**Pull request merged**
