### PR TITLE
Fix missing epinio parts on 2.7

### PR DESCRIPTION
**Pull request by andreas-kupries**
Ref https://github.com/epinio/epinio/issues/1780

Epinio looks to be only partially copied into the `dev-v2.7` branch. Missing:

  - `epinio.svg` logo asset
  - `epinio-crd` chart
  - `epinio-crd` chart assets
  - `epinio-crd` entry in `release.yaml`
  - `epinio-crd` entry in `index.yaml`

This PR provides all the missing things.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
@PennyScissors Where do we stand here ?

**Review by aiyengar2 — COMMENTED** [review]
LGTM and seems like we need this for Epinio to pass a basic smoke test in 2.7, but waiting for approval since we’re past code freeze for 2.7.0

**Comment by prachidamle** [comment]
@andreas-kupries is this PR still applicable?

**Review by olblak — APPROVED** [review]

**Comment by olblak** [comment]
@andreas-kupries could you have a look to the conflicting files?

**Comment by andreas-kupries** [comment]
Definitely outdated. Fully superseded by later PR's. Closing.

**Pull request closed without merging**
