### PR TITLE
[dev-v2.8] Fix missing harvester annotation

### PR DESCRIPTION
**Pull request by lucasmlp**
## Problem
The chart was missing a required annotation `catalog.cattle.io/permits-os: linux`.

## Solution
- ran `make prepare`
- modified *packages/harvester/harvester-cloud-provider/charts/Chart.yaml*
- ran `make patch`
- ran `make clean`
- committed the changes
- ran `make charts`
- committed the changes

### CODE REVIEW

**Review by briandowns — APPROVED** [review]

**Review by Vicente-Cheng — APPROVED** [review]
lgtm!

Just curious, should we complete these changes on PR https://github.com/rancher/charts/pull/3601 instead of creating a new one?
cc @FrankYang0529

**Comment by FrankYang0529** [comment]
> Just curious, should we complete these changes on PR #3601 instead of creating a new one?

I also add the change to #3601. Thanks for the reminder.

**Review by starbops — APPROVED** [review]
LGTM, thank you.

**Comment by w13915984028** [comment]
Many charts under Rancher charts repo claim to support both Linux and Windows, `catalog.cattle.io/permits-os: linux,windows`

Supporting `Linux` is sure for Harvester related charts, but for `Windows`, does anyone have more insights?


Some charts are claiming as such.
```
charts/sriov-crd/100.0.2+up0.1.0/Chart.yaml:  catalog.cattle.io/permits-os: linux,windows
charts/sriov-crd/102.2.0+up0.1.0/Chart.yaml:  catalog.cattle.io/permits-os: linux
charts/sriov-crd/102.0.0+up0.1.0/Chart.yaml:  catalog.cattle.io/permits-os: linux
charts/sriov-crd/102.1.0+up0.1.0/Chart.yaml:  catalog.cattle.io/permits-os: linux
charts/sriov-crd/101.0.1+up0.1.0/Chart.yaml:  catalog.cattle.io/permits-os: linux
charts/sriov-crd/100.0.3+up0.1.0/Chart.yaml:  catalog.cattle.io/permits-os: linux,windows
charts/sriov-crd/103.0.0+up0.1.0/Chart.yaml:  catalog.cattle.io/permits-os: linux
charts/sriov-crd/100.0.5+up0.1.0/Chart.yaml:  catalog.cattle.io/permits-os: linux
charts/sriov-crd/100.0.4+up0.1.0/Chart.yaml:  catalog.cattle.io/permits-os: linux
```

**Comment by lucasmlp** [comment]
@Vicente-Cheng 
`harvester-cloud-provider 103.0.1+up0.2.3` is the one scheduled for release in _Rancher v2.8.3 Chart Release_. This fix must be separated from the bump so I can cherry-pick it during the release process

**Comment by lucasmlp** [comment]
@w13915984028 
These annotations are added by the chart feature owners. The charts have passed QA testing before being released. I only added `linux` to the chart because is the same on in the `os` annotation.

**Comment by Vicente-Cheng** [comment]
> `harvester-cloud-provider 103.0.1+up0.2.3` is the one scheduled for release in _Rancher v2.8.3 Chart Release_. This fix must be separated from the bump so I can cherry-pick it during the release process

Thanks for the explanation. That makes sense to me :)

**Pull request merged**
