### PR TITLE
[dev-v2.7] Bump harvester-csi-driver v0.1.17 and update kube-version

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
Issues: 
- https://github.com/harvester/harvester/issues/4396
- https://github.com/rancher/rancher/issues/44122

We want to bump harvester-csi-driver 0.1.17 and support kube-version v1.27 for the above issue.
That will help if the user customizes the hostname on the guest cluster VM.
 
Thanks! cc @bk201, @connorkuehl, @markhillgit

### CODE REVIEW

**Review by lucasmlp — CHANGES_REQUESTED** [review]
Please fix the conflicts in release.yaml and give thumbs up to the latest GitHub-actions [bot] comment in your PR. Otherwise, it looks good to me

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Comment by Vicente-Cheng** [comment]
Hi @lucasmlp
I resolved the conflict and also bumped the kube-version to v1.27.
Could you help to recheck it? Thanks! cc @bk201

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Comment by rebeccazzzz** [comment]
Thank you so much @lucasmlp. Would you mind helping us merge the PR as well?

**Comment by Vicente-Cheng** [comment]
Hi @lucasmlp, I resolve the conflict again.

Please help to recheck, thanks!

BTW do we need another review to approve and then merge?
Or can you help to merge after you approve?

Thanks!

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Pull request merged**
