### PR TITLE
Longhorn v1.3.1: Separate longhorn-crd package from main longhorn package and hide Longhorn 100.2.1+up1.3.1 chart with broken CRD install

### PR DESCRIPTION
**Pull request by PhanLe1010**
This PR does:
1. Separate longhorn-crd package from main longhorn package
2. Hide Longhorn 100.2.1+up1.3.1 chart with broken CRD install

### CODE REVIEW

**Comment by PhanLe1010** [comment]
This draft PR test the approach separating longhorn-crd package from main longhorn package.
This probably will not use this PR for the Longhorn 1.3.1
It is here for testing and comparison

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
cc @khushboo-rancher

**Comment by PhanLe1010** [comment]
### Test plan:

1. Cluster of Kubernetes 1.20
1. Adding this repo to the `apps` section in new rancher UI
    * repo: https://github.com/PhanLe1010/charts.git
    * branch: `release-v2.6-longhorn-1.3.1`
1. Access old rancher UI by navigating to `<your-rancher-url>/g`.
1. Install Longhorn 1.0.2 
1. Create/attach some volumes. Create a few recurring snapshot/backup job that run every minutes
1. Upgrade Longhorn to v1.2.4
1. Migrate Longhorn to new chart in new rancher UI https://longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui/ 
1. Upgrade to 1.3.1 in the UI
1. Verify that the upgrade is going fine. Before this fix, the upgrade would be stuck at with error:
```
Patch CustomResourceDefinition "volumes.longhorn.io" in namespace
error updating the resource "volumes.longhorn.io":
         cannot patch "volumes.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "volumes.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true
Error: UPGRADE FAILED: cannot patch "engineimages.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "engineimages.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true && cannot patch "nodes.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "nodes.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true && cannot patch "volumes.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "volumes.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true
```

### Notes:
1. This could be a manual test case cc @khushboo-rancher 
1. Another manual test case is: since GSK uses our broken chart `longhorn 100.2.1+up1.3.1` with [the workaround ](https://github.com/longhorn/longhorn/discussions/4198#discussioncomment-3074937) we would like to verify the future upgrade path for this customer and other similar users. The steps are:
    1. Cluster of Kubernetes 1.20
    1. Adding this repo to the `apps` section in new rancher UI
        * repo: https://github.com/PhanLe1010/charts.git
        * branch: `release-v2.6-longhorn-1.3.1` (I will update this one to keep the broken chart `longhorn 100.2.1+up1.3.1`)
    1. Access old rancher UI by navigating to `<your-rancher-url>/g`.
    1. Install Longhorn 1.0.2 
    1. Create/attach some volumes. Create a few recurring snapshot/backup job that run every minutes
    1. Upgrade Longhorn to v1.2.4
    1. Migrate Longhorn to new chart in new rancher UI https://longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui/ 
    1. Upgrade to `longhorn 100.2.1+up1.3.1` in the UI
    1. Verify the upgrade would be stuck at with error:
    ```
    Patch CustomResourceDefinition "volumes.longhorn.io" in namespace
    error updating the resource "volumes.longhorn.io":
             cannot patch "volumes.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "volumes.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true
    Error: UPGRADE FAILED: cannot patch "engineimages.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "engineimages.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true && cannot patch "nodes.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "nodes.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true && cannot patch "volumes.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "volumes.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true
    ```
    1. Apply [the workaround ](https://github.com/longhorn/longhorn/discussions/4198#discussioncomment-3074937)
    1. Retry upgrade to  `longhorn 100.2.1+up1.3.1` in the UI
    1. Verify the upgrade is ok
    1. Verify that the user can successfully upgrade to future chart releases (e.g., Longhorn v1.3.2) from this version `longhorn 100.2.1+up1.3.1`

**Comment by aiyengar2** [comment]
## Charts Checklist (built for v0.3.x charts-build-scripts)

Scripts Gist: https://gist.github.com/PennyScissors/70fac62fcbda2030415474bfea842143

### Checkpoint 0: Validate `release.yaml`

Validation steps:
- [ ] Each chart version in `release.yaml` DOES NOT modify an already released chart. If so, stop and modify the versions so that it releases a net-new chart.
- [ ] Each chart version in `release.yaml` IS exactly 1 more patch version than the last released chart version. If not, stop and modify the versions so that it releases a net-new chart.

### Checkpoint 1: Compare contents of assets/ to charts/

Validation steps:
- [ ] Running `make unzip` to regenerate the `charts/` from scratch, then `git diff` to check differences between `assets/` and `charts/` yields NO differences or innocuous differences.

IMPORTANT: Do not undo these changes for future steps since we want to keep the charts/ that match the current contents of assets!

### Checkpoint 2: Compare assets against index.yaml

Validation steps:
- [ ] The `index.yaml` file has an entry for each chart version.
- [ ] The `index.yaml` entries for each chart matches the `Chart.yaml` for each chart.
- [ ] Each chart has ALL required annotations
  - kube-version annotation
  - rancher-version annotation
  - permits-os annotation (indicates Windows and/or Linux)

### Checkpoint 3: Logical Checks

Validation steps (requires manual inspection of differences between previous and latest chart version):
- [ ] Ensure no RC images are included.
- [ ] Ensure all mirrored images include the right prefix.
- [ ] Ensure any new images have `repository` and `tag` on the same level to ensure the rancher-images.txt is generated correctly for it for airgap scenarios.

**Comment by aiyengar2** [comment]
```diff
diff -uNr charts/longhorn/100.2.1+up1.3.1/Chart.yaml to-be-released/longhorn/100.2.1+up1.3.1/Chart.yaml
--- charts/longhorn/100.2.1+up1.3.1/Chart.yaml	2022-09-01 15:27:21.000000000 -0700
+++ to-be-released/longhorn/100.2.1+up1.3.1/Chart.yaml	2022-09-01 15:23:17.000000000 -0700
@@ -6,7 +6,7 @@
   catalog.cattle.io/namespace: longhorn-system
   catalog.cattle.io/os: linux
   catalog.cattle.io/provides-gvr: longhorn.io/v1beta1
-  catalog.cattle.io/rancher-version: '>= 2.6.0-0 < 2.7.0-0'
+  catalog.cattle.io/rancher-version: < 2.6.0-0
   catalog.cattle.io/release-name: longhorn
   catalog.cattle.io/type: cluster-tool
   catalog.cattle.io/ui-component: longhorn
```

100.2.1+up1.3.1 changes LGTM.

**Comment by aiyengar2** [comment]
```diff
diff -uNr charts/longhorn/100.2.1+up1.3.1/Chart.yaml to-be-released/longhorn/100.2.2+up1.3.1/Chart.yaml
--- charts/longhorn/100.2.1+up1.3.1/Chart.yaml	2022-09-01 15:27:21.000000000 -0700
+++ to-be-released/longhorn/100.2.2+up1.3.1/Chart.yaml	2022-09-01 15:23:17.000000000 -0700
@@ -38,4 +38,4 @@
 - https://github.com/longhorn/longhorn-ui
 - https://github.com/longhorn/longhorn-tests
 - https://github.com/longhorn/backing-image-manager
-version: 100.2.1+up1.3.1
+version: 100.2.2+up1.3.1
diff -uNr charts/longhorn/100.2.1+up1.3.1/templates/validate-install-crd.yaml to-be-released/longhorn/100.2.2+up1.3.1/templates/validate-install-crd.yaml
--- charts/longhorn/100.2.1+up1.3.1/templates/validate-install-crd.yaml	2022-09-01 15:27:21.000000000 -0700
+++ to-be-released/longhorn/100.2.2+up1.3.1/templates/validate-install-crd.yaml	1969-12-31 16:00:00.000000000 -0800
@@ -1,30 +0,0 @@
-#{{- if gt (len (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "")) 0 -}}
-# {{- $found := dict -}}
-# {{- set $found "longhorn.io/v1beta1/BackingImageDataSource" false -}}
-# {{- set $found "longhorn.io/v1beta1/BackingImageManager" false -}}
-# {{- set $found "longhorn.io/v1beta1/BackingImage" false -}}
-# {{- set $found "longhorn.io/v1beta1/Backup" false -}}
-# {{- set $found "longhorn.io/v1beta1/BackupTarget" false -}}
-# {{- set $found "longhorn.io/v1beta1/BackupVolume" false -}}
-# {{- set $found "longhorn.io/v1beta1/EngineImage" false -}}
-# {{- set $found "longhorn.io/v1beta1/Engine" false -}}
-# {{- set $found "longhorn.io/v1beta1/InstanceManager" false -}}
-# {{- set $found "longhorn.io/v1beta1/Node" false -}}
-# {{- set $found "longhorn.io/v1beta2/Orphan" false -}}
-# {{- set $found "longhorn.io/v1beta1/RecurringJob" false -}}
-# {{- set $found "longhorn.io/v1beta1/Replica" false -}}
-# {{- set $found "longhorn.io/v1beta1/Setting" false -}}
-# {{- set $found "longhorn.io/v1beta1/ShareManager" false -}}
-# {{- set $found "longhorn.io/v1beta2/Snapshot" false -}}
-# {{- set $found "longhorn.io/v1beta1/Volume" false -}}
-# {{- range .Capabilities.APIVersions -}}
-# {{- if hasKey $found (toString .) -}}
-# 	{{- set $found (toString .) true -}}
-# {{- end -}}
-# {{- end -}}
-# {{- range $_, $exists := $found -}}
-# {{- if (eq $exists false) -}}
-# 	{{- required "Required CRDs are missing. Please install the corresponding CRD chart before installing this chart." "" -}}
-# {{- end -}}
-# {{- end -}}
-#{{- end -}}
\ No newline at end of file
```

@PhanLe1010 did you intend to remove the validate-install-crd file from the main chart for 100.2.2+up1.3.1?

**Comment by aiyengar2** [comment]
```diff
diff -uNr charts/longhorn-crd/100.2.1+up1.3.1/Chart.yaml to-be-released/longhorn-crd/100.2.2+up1.3.1/Chart.yaml
--- charts/longhorn-crd/100.2.1+up1.3.1/Chart.yaml	2022-09-01 15:27:21.000000000 -0700
+++ to-be-released/longhorn-crd/100.2.2+up1.3.1/Chart.yaml	2022-09-01 15:23:17.000000000 -0700
@@ -4,7 +4,8 @@
   catalog.cattle.io/namespace: longhorn-system
   catalog.cattle.io/release-name: longhorn-crd
 apiVersion: v1
+appVersion: v1.3.1
 description: Installs the CRDs for longhorn.
 name: longhorn-crd
 type: application
-version: 100.2.1+up1.3.1
+version: 100.2.2+up1.3.1
diff -uNr charts/longhorn-crd/100.2.1+up1.3.1/README.md to-be-released/longhorn-crd/100.2.2+up1.3.1/README.md
--- charts/longhorn-crd/100.2.1+up1.3.1/README.md	2022-09-01 15:27:21.000000000 -0700
+++ to-be-released/longhorn-crd/100.2.2+up1.3.1/README.md	2022-09-01 15:23:17.000000000 -0700
@@ -1,2 +1,2 @@
 # longhorn-crd
-A Rancher chart that installs the CRDs used by longhorn.
+A Rancher chart that installs the CRDs used by longhorn.
\ No newline at end of file
diff -uNr charts/longhorn-crd/100.2.1+up1.3.1/templates/_helpers.tpl to-be-released/longhorn-crd/100.2.2+up1.3.1/templates/_helpers.tpl
--- charts/longhorn-crd/100.2.1+up1.3.1/templates/_helpers.tpl	1969-12-31 16:00:00.000000000 -0800
+++ to-be-released/longhorn-crd/100.2.2+up1.3.1/templates/_helpers.tpl	2022-09-01 15:23:17.000000000 -0700
@@ -0,0 +1,66 @@
+{{/* vim: set filetype=mustache: */}}
+{{/*
+Expand the name of the chart.
+*/}}
+{{- define "longhorn.name" -}}
+{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
+{{- end -}}
+
+{{/*
+Create a default fully qualified app name.
+We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
+*/}}
+{{- define "longhorn.fullname" -}}
+{{- $name := default .Chart.Name .Values.nameOverride -}}
+{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
+{{- end -}}
+
+
+{{- define "longhorn.managerIP" -}}
+{{- $fullname := (include "longhorn.fullname" .) -}}
+{{- printf "http://%s-backend:9500" $fullname | trunc 63 | trimSuffix "-" -}}
+{{- end -}}
+
+
+{{- define "secret" }}
+{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.privateRegistry.registryUrl (printf "%s:%s" .Values.privateRegistry.registryUser .Values.privateRegistry.registryPasswd | b64enc) | b64enc }}
+{{- end }}
+
+{{- /*
+longhorn.labels generates the standard Helm labels.
+*/ -}}
+{{- define "longhorn.labels" -}}
+app.kubernetes.io/name: {{ template "longhorn.name" . }}
+helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
+app.kubernetes.io/managed-by: {{ .Release.Service }}
+app.kubernetes.io/instance: {{ .Release.Name }}
+app.kubernetes.io/version: {{ .Chart.AppVersion }}
+{{- end -}}
+
+
+{{- define "system_default_registry" -}}
+{{- if .Values.global.cattle.systemDefaultRegistry -}}
+{{- printf "%s/" .Values.global.cattle.systemDefaultRegistry -}}
+{{- else -}}
+{{- "" -}}
+{{- end -}}
+{{- end -}}
+
+{{- define "registry_url" -}}
+{{- if .Values.privateRegistry.registryUrl -}}
+{{- printf "%s/" .Values.privateRegistry.registryUrl -}}
+{{- else -}}
+{{ include "system_default_registry" . }}
+{{- end -}}
+{{- end -}}
+
+{{- /*
+ define the longhorn release namespace
+*/ -}}
+{{- define "release_namespace" -}}
+{{- if .Values.namespaceOverride -}}
+{{- .Values.namespaceOverride -}}
+{{- else -}}
+{{- .Release.Namespace -}}
+{{- end -}}
+{{- end -}}
diff -uNr charts/longhorn-crd/100.2.1+up1.3.1/templates/crds.yaml to-be-released/longhorn-crd/100.2.2+up1.3.1/templates/crds.yaml
--- charts/longhorn-crd/100.2.1+up1.3.1/templates/crds.yaml	2022-09-01 15:27:21.000000000 -0700
+++ to-be-released/longhorn-crd/100.2.2+up1.3.1/templates/crds.yaml	2022-09-01 15:23:17.000000000 -0700
@@ -4,10 +4,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: backingimagedatasources.longhorn.io
 spec:
@@ -174,10 +171,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: backingimagemanagers.longhorn.io
 spec:
@@ -358,10 +352,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: backingimages.longhorn.io
 spec:
@@ -371,7 +362,7 @@
       clientConfig:
         service:
           name: longhorn-conversion-webhook
-          namespace: longhorn-system
+          namespace: {{ include "release_namespace" . }}
           path: /v1/webhook/conversion
           port: 9443
       conversionReviewVersions:
@@ -532,10 +523,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: backups.longhorn.io
 spec:
@@ -724,10 +712,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: backuptargets.longhorn.io
 spec:
@@ -737,7 +722,7 @@
       clientConfig:
         service:
           name: longhorn-conversion-webhook
-          namespace: longhorn-system
+          namespace: {{ include "release_namespace" . }}
           path: /v1/webhook/conversion
           port: 9443
       conversionReviewVersions:
@@ -906,10 +891,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: backupvolumes.longhorn.io
 spec:
@@ -1069,20 +1051,18 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: engineimages.longhorn.io
 spec:
+  preserveUnknownFields: false
   conversion:
     strategy: Webhook
     webhook:
       clientConfig:
         service:
           name: longhorn-conversion-webhook
-          namespace: longhorn-system
+          namespace: {{ include "release_namespace" . }}
           path: /v1/webhook/conversion
           port: 9443
       conversionReviewVersions:
@@ -1107,7 +1087,7 @@
       jsonPath: .spec.image
       name: Image
       type: string
-    - description: Number of volumes are using the engine image
+    - description: Number of resources using the engine image
       jsonPath: .status.refCount
       name: RefCount
       type: integer
@@ -1149,7 +1129,7 @@
       jsonPath: .spec.image
       name: Image
       type: string
-    - description: Number of volumes are using the engine image
+    - description: Number of resources using the engine image
       jsonPath: .status.refCount
       name: RefCount
       type: integer
@@ -1259,10 +1239,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: engines.longhorn.io
 spec:
@@ -1579,10 +1556,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: instancemanagers.longhorn.io
 spec:
@@ -1748,20 +1722,18 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: nodes.longhorn.io
 spec:
+  preserveUnknownFields: false
   conversion:
     strategy: Webhook
     webhook:
       clientConfig:
         service:
           name: longhorn-conversion-webhook
-          namespace: longhorn-system
+          namespace: {{ include "release_namespace" . }}
           path: /v1/webhook/conversion
           port: 9443
       conversionReviewVersions:
@@ -1977,10 +1949,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: orphans.longhorn.io
 spec:
@@ -2241,10 +2210,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: replicas.longhorn.io
 spec:
@@ -2432,10 +2398,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: settings.longhorn.io
 spec:
@@ -2522,10 +2485,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: sharemanagers.longhorn.io
 spec:
@@ -2632,10 +2592,7 @@
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
   creationTimestamp: null
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: snapshots.longhorn.io
 spec:
@@ -2755,20 +2712,18 @@
 metadata:
   annotations:
     controller-gen.kubebuilder.io/version: v0.7.0
-  labels:
-    app.kubernetes.io/name: longhorn
-    app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.3.0
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
     longhorn-manager: ""
   name: volumes.longhorn.io
 spec:
+  preserveUnknownFields: false
   conversion:
     strategy: Webhook
     webhook:
       clientConfig:
         service:
           name: longhorn-conversion-webhook
-          namespace: longhorn-system
+          namespace: {{ include "release_namespace" . }}
           path: /v1/webhook/conversion
           port: 9443
       conversionReviewVersions:
```

longhorn-crd 100.2.2+up1.3.1 changes LGTM.

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
@PhanLe1010 the only concern is the removal of the validate-install-crd file called out in https://github.com/rancher/charts/pull/2058#issuecomment-1234853752.

**Comment by khushboo-rancher** [comment]
**Validation : PASS**

I validated this by adding chart repository on Rancher pointing to the ```repo: https://github.com/PhanLe1010/charts.git
branch: release-v2.6-longhorn-1.3.1```, It worked fine.

**Comment by PhanLe1010** [comment]
> @PhanLe1010 the only concern is the removal of the validate-install-crd file called out in https://github.com/rancher/charts/pull/2058#issuecomment-1234853752.

Yeah, I intend to remove it because there is no way to automatically generate it now that we removed the [crdOptions](https://github.com/rancher/charts/blob/dev-v2.6/docs/packages.md#:~:text=same%20as%20above-,crdOptions%3A,-%23%20Mutually%20exclusive%20with)

If we overlay it using the old validate-install-crd file I am worry that it might be outdated in the future when the CRDs are updated/removed ...

Is there any concern removing this validation functionality?

**Comment by PhanLe1010** [comment]
> my recommendation would be to keep the validate-install-crd file and manually maintain it, but keeping the file does introduce additional maintenance burden on the Longhorn team to keep that up-to-date per release

This is from @aiyengar2 

Ok. I will update the PR to bring it back

**Comment by aiyengar2** [comment]
@khushboo-rancher do we need to re-QA the chart once updates have been made?

**Comment by innobead** [comment]
Thanks @PhanLe1010 @aiyengar2 @khushboo-rancher @yangchiu 👍 

cc @rebeccazzzz

**Pull request merged**
