### PR TITLE
upgrading artifactory charts, artifactory version, postgresql version, supported k8s version

### PR DESCRIPTION
**Pull request by vinayagg**
charts are now version 1.0.0, artifactory version is updated to 6.13.1, postgresql helm charts version has been updated from version 0.9.5 to version 6.5.3, this upgrades postgres from version 9.6.2 to version 11.5.0, charts now work with k8s 1.16

### CODE REVIEW

**Comment by guangbochen** [comment]
@vinayagg we have changed to use a specific version of folder naming instead of `latest`, can u please help to redo the commits with following steps:
1. base-copy the `latest` folder to `0.12.16` and `1.0.0` folders.
2. update the commit changes in folder `1.0.0`
Thanks!

**Comment by vinayagg** [comment]
@guangbochen done, please review again.

**Comment by guangbochen** [comment]
@vinayagg thanks, just a small twist with squashing the last commit and the total commits would be 2, then we would be fine to merge, thanks.

**Comment by vinayagg** [comment]
@guangbochen done

**Comment by guangbochen** [comment]
The total commits are 5 now, can u please help to double-check it, thanks.

**Comment by vinayagg** [comment]
@guangbochen sorry for the oversight. Fixed again.

**Comment by deniseschannon** [comment]
https://github.com/rancher/rancher/issues/23532

**Pull request merged**
