### PR TITLE
Add Longhorn 1.3.3 chart with dev-2.6

### PR DESCRIPTION
**Pull request by weizhe0422**
[Longhorn 5581](https://github.com/longhorn/longhorn/issues/5581)

Signed-off-by: Ray Chang [ray.chang@suse.com]

Tests
 - Successful to install on Rancher v2.6.11
   截圖 2023-04-21 上午11 10 06

cc @innobead @PhanLe1010 @khushboo-rancher

### CODE REVIEW

**Review by rohitsakala — APPROVED** [review]

**Comment by innobead** [comment]
@rohitsakala We should wait for QA  verification before merging.

cc @khushboo-rancher

**Comment by khushboo-rancher** [comment]
Verified the chart on the dev-v2.6 branch - **LGTM**

Validated installation, uninstallation, upgrade (1.3.2->1.3.3) and P0 cases.

**Comment by khushboo-rancher** [comment]
@rohitsakala No need to revert the changes, things are looking good.

**Comment by rohitsakala** [comment]
@khushboo-rancher  ok Thanks

**Review by PhanLe1010 — COMMENTED** [review]
LTGM.

Sorry for the late review

**Pull request merged**
