### PR TITLE
Longhorn v1.1.2 release 

### PR DESCRIPTION
**Pull request by shuo-wu**
longhorn/longhorn#2724

### CODE REVIEW

**Comment by innobead** [comment]
cc @khushboo-rancher

**Review by innobead — DISMISSED** [review]
LGTM.

@khushboo-rancher Please also help verify this before merging. Thanks.

@cbron & @aiyengar2 Please help review. Thank you.

**Comment by khushboo-rancher** [comment]
Verified with `shuo-wu-master` branch, the longhorn deployment works fine, checked the P0 cases also.

Validation - **Pass**

**Comment by innobead** [comment]
@cbron @nickgerace Please help review and merge soon if no problems. Thank you.

**Comment by PennyScissors** [comment]
Just ran ct-lint on this chart (what the broken CI here is supposed to do), and everything looks good so it's safe to force merge once approved.
```
------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 longhorn => (version: "1.1.2", path: "charts/longhorn/latest")
 longhorn => (version: "1.1.1", path: "charts/longhorn/v1.1.1")
------------------------------------------------------------------------------------------------------------------------

Linting chart 'longhorn => (version: "1.1.2", path: "charts/longhorn/latest")'
Checking chart 'longhorn => (version: "1.1.2", path: "charts/longhorn/latest")' for a version bump...
Old chart version: 1.1.1
New chart version: 1.1.2
Chart version ok.
Validating /rancher-charts/charts/longhorn/latest/Chart.yaml...
Validation success! 👍
==> Linting charts/longhorn/latest

1 chart(s) linted, 0 chart(s) failed
Linting chart 'longhorn => (version: "1.1.1", path: "charts/longhorn/v1.1.1")'
Checking chart 'longhorn => (version: "1.1.1", path: "charts/longhorn/v1.1.1")' for a version bump...
Unable to find chart on master. New chart detected.
Validating /rancher-charts/charts/longhorn/v1.1.1/Chart.yaml...
Validation success! 👍
==> Linting charts/longhorn/v1.1.1

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ longhorn => (version: "1.1.2", path: "charts/longhorn/latest")
 ✔︎ longhorn => (version: "1.1.1", path: "charts/longhorn/v1.1.1")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

**Review by PennyScissors — APPROVED** [review]

**Review by nickgerace — APPROVED** [review]

**Review by cbron — APPROVED** [review]

**Pull request merged**
