### PR TITLE
Update istio version to include the upstream version

### PR DESCRIPTION
**Pull request by cbron**

### CODE REVIEW

**Review by brendarearden — DISMISSED** [review]
lgtm

**Comment by jiaqiluo** [comment]
@cbron  @brendarearden 
What is the story behind this PR? Will it be a general rule for all `100.0.0` charts in 2.6 ?

**Comment by cbron** [comment]
@jiaqiluo The only 100's without an `+up...` in 2.6.0 are istio and alerting drivers. Since alerting drivers is local chart with multiple underlying charts there isn't an upstream version. But for istio there is a definite upstream version and only way to figure out which actual istio version you are installing is to hit install and look at the values.yaml.

**Review by jiaqiluo — DISMISSED** [review]
LGTM

**Comment by cbron** [comment]
Forgot to delete the old asset

**Review by jiaqiluo — APPROVED** [review]

**Review by brendarearden — APPROVED** [review]

**Pull request merged**
