### PR TITLE
Updating NeuVector Helm Chart

### PR DESCRIPTION
**Pull request by selvamt94**
Updating NeuVector Rancher Catalog with new version 1.5.1 of helm chart.

### CODE REVIEW

**Comment by PennyScissors** [comment]
Can you take me through the steps to deploy the chart? 
I tried deploying it, but I ran into the following error:
`ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: pull access denied for neuvector/controller, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by selvamt94** [comment]
You need to create a secret in the k8s platform for accessing the docker hub to pull our images. Can you please share with us your docker hub id, so that we can add our repository to you to download our images. If you do not have one, please create one on hub.docker.com with your official email id. Thanks Selvam

**Comment by PennyScissors** [comment]
@selvamt70 No problem, my docker hub ID is `pennyscissors`.

**Comment by selvamt94** [comment]
We have added your docker id, please check. Given below command to create secret. Thanks Selvam.
kubectl create secret docker-registry regsecret -n neuvector --docker-server=https://index.docker.io/v1/ --docker-username=your-name --docker-password=your-pword --docker-email=your-email

**Comment by PennyScissors** [comment]
Thanks for providing me the command to create the secret! It was helpful. I got it to deploy successfully, and overall looks good to me.

**Comment by selvamt94** [comment]
@PennyScissors Thanks for approving our pull request. How long will take to merge our checkin into rancher/charts. I do not see our new version here https://github.com/rancher/charts/neuvector. Thanks Selvam

**Comment by selvamt70** [comment]
Hi,

Can you please review our new pull request.
https://github.com/rancher/charts/pull/771

Thanks
Selvam

**Pull request merged**
