### PR TITLE
stable(openebs): update 1.7.0 release version

### PR DESCRIPTION
**Pull request by prateekpandey14**
- Updated README
- Updated questions.yaml
- Updated values.yaml

Signed-off-by: prateekpandey14 <prateek.pandey@openebs.io>

### CODE REVIEW

**Comment by prateekpandey14** [comment]
cc @guangbochen

**Comment by prateekpandey14** [comment]
@guangbochen @deniseschannon can you please help to get this PR merge. thanks

**Comment by guangbochen** [comment]
@prateekpandey14   can u please help to split this PR into 2 commits so it's easier to review

1. 1st commit: Copy the older version to a new folder
2. 2nd commit: Changes made to the older version to update it.

**Comment by prateekpandey14** [comment]
@guangbochen done PTAL.

**Comment by guangbochen** [comment]
LGTM, thanks

**Pull request merged**
