### PR TITLE
[dev-v2.8] rancher-monitoring 103.1.0-rc1+up45.31.1 update

### PR DESCRIPTION
**Pull request by ericpromislow**
## Problem
Bump the chart to move prometheus dependency from 2.42. to 2.45 (the latest LTS version)

## Backporting considerations
This is the backport version of Issue #44605, which made the same change on dev-v2.9

### CODE REVIEW

**Review by adamkpickering — APPROVED** [review]
LGTM. Just perform the validation steps above and this should be good to go.

**Review by alexandreLamarre — COMMENTED** [review]
@joshmeranda Do we want to wait until after 2.8.3 to merge this?

**Comment by joshmeranda** [comment]
@alexandreLamarre we can merge now

**Review by lucasmlp — DISMISSED** [review]
You need to add the monitoring package to `release.yaml` so that the CI will pass

**Comment by prachidamle** [comment]
This PR is for the issue https://github.com/rancher/rancher/issues/44606

**Review by alexandreLamarre — APPROVED** [review]

**Review by nicholasSUSE — DISMISSED** [review]
Please resolve conflicts.

---

Hello, we have improved the Charts documentation regarding Pull Request Rules.

Please take a look at it before making any new Pull Requests.
We are still approving Pull Requests and starting to inform all teams, soon we will require the standard in the documentation.

https://github.com/rancher/charts?tab=readme-ov-file#pull-request-rules

**Review by alexandreLamarre — APPROVED** [review]

**Review by alexandreLamarre — APPROVED** [review]

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Pull request merged**
