### PR TITLE
[dev-v2.8] bump harvester-csi-driver v0.1.17 and update kube-version

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
Issue: https://github.com/rancher/rancher/issues/43749

### CODE REVIEW

**Comment by nicholasSUSE** [comment]
Hello @Vicente-Cheng 
Is this Pull Request still relevant?
Can I close it?

**Comment by nicholasSUSE** [comment]
Unresponsive, closing.

**Comment by rebeccazzzz** [comment]
Hi @nicholasSUSE. Reopening this to give @Vicente-Cheng a chance to respond since it was a major holiday in Taiwan this past week.

**Comment by nicholasSUSE** [comment]
> Hi @nicholasSUSE. Reopening this to give @Vicente-Cheng a chance to respond since it was a major holiday in Taiwan this past week.

Ok thank you @rebeccazzzz 
@Vicente-Cheng 
Please review this opened PR. 
I am doing some cleaning on this repository. 
If this is not relevant anymore, please close it.

**Comment by Vicente-Cheng** [comment]
Thanks @rebeccazzzz, for helping to take care of this.

Hi @nicholasSUSE,
I rebase PR again.

This PR is related to the issue https://github.com/rancher/rancher/issues/43749.
Could you please help to review it?

Thanks!

**Comment by Vicente-Cheng** [comment]
Hi @nicholasSUSE, @w13915984028, could you help review this PR? Many thanks!

**Review by w13915984028 — APPROVED** [review]
LGTM, thanks.

**Review by nicholasSUSE — APPROVED** [review]

**Pull request merged**
