### PR TITLE
Update fleet to v0.3.9-rc2

### PR DESCRIPTION
**Pull request by rohitsakala**
Pulls in changes from [rancher/fleet#597](https://github.com/rancher/fleet/pull/695) so that Rancher can see it.

Related Issue: rancher/rancher#35501

### CODE REVIEW

**Review by aiyengar2 — APPROVED** [review]

**Comment by prachidamle** [comment]
We need to delete the assets and entries in index.yaml for the v0.3.9-rc1

**Comment by aiyengar2** [comment]
> We need to delete the assets and entries in index.yaml for the v0.3.9-rc1

@rohitsakala the easiest way to do this is to run and commit:

```bash
CHART=fleet VERSION=v0.3.9-rc1 make remove
CHART=fleet-crd VERSION=v0.3.9-rc1 make remove
CHART=fleet-agent VERSION=v0.3.9-rc1 make remove
```

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
nit: rename last commit to `Run make remove`

**Comment by rohitsakala** [comment]
> nit: rename last commit to `Run make remove`

Done.

**Review by aiyengar2 — APPROVED** [review]

**Review by prachidamle — APPROVED** [review]

**Pull request merged**
