### PR TITLE
Chart version 1.0.24

### PR DESCRIPTION
**Pull request by dlbock**
Changes included:
- Updated README to include install and uninstall instructions for both Helm 2 and Helm 3
- Please note that this chart is still 100% compatible with Helm 2 and can be deployed with Helm 2 indefinitely.

### CODE REVIEW

**Comment by dlbock** [comment]
cc @guangbochen @deniseschannon Please review and merge as soon as you can.

**Comment by dlbock** [comment]
Bumping this again

**Comment by dlbock** [comment]
To clarify - this is almost exactly the same as the previously closed PR: https://github.com/rancher/charts/pull/379. We just redid the change to include install/uninstall instructions for helm 2 and helm 3 in the README.

**Comment by dlbock** [comment]
@guangbochen @deniseschannon We've been waiting for about 3 weeks to get this merged. Could someone please help us out?

**Comment by guangbochen** [comment]
LGMT, thanks @deniseschannon

**Comment by dlbock** [comment]
Thank you both

**Pull request merged**
