### PR TITLE
Add rebase script

### PR DESCRIPTION
**Pull request by aiyengar2**
This script powered https://github.com/rancher/charts/pull/1072, which rebased 5 charts.

Related Issue: https://github.com/rancher/charts-build-scripts/issues/31

### CODE REVIEW

**Comment by cbron** [comment]
Waiting to review until 2.5.8 calms down

**Review by aiyengar2 — COMMENTED** [review]
This PR needs to be moved to the dev-v2.5 branch as the dev-v2.5-source branch is now deprecated.

The easiest way to do this would be to create a new local branch from the `dev-v2.5` branch, cherry-pick your commits from the branch this PR points to to that new branch, and then run `make charts` to generate the charts/ and assets/ as part of the new provisioning workflow.

More details on the new workflow can be found in https://github.com/rancher/charts/blob/dev-v2.5/packages/README.md#common-workflow. Feel free to find me on Slack / RocketChat or email me at arvind.iyengar@suse.com for any questions.

**Comment by cbron** [comment]
Isn't this one closed now ? I thought we removed

**Comment by aiyengar2** [comment]
Updated base to dev-v2.5

**Comment by cbron** [comment]
Is this still a thing ? 😆

**Comment by aiyengar2** [comment]
> Is this still a thing ? 😆

Yup, still should be valid. Going to be using it soon for rebasing Monitoring

**Comment by aiyengar2** [comment]
Pushed some modifications to this script due to needing to have support for rebasing charts that have an excludes directory.

**Comment by aiyengar2** [comment]
Closing in favor of rebased PR in https://github.com/rancher/charts/pull/1936

**Pull request closed without merging**
