### PR TITLE
[master] Hide longhorn in legacy catalog

### PR DESCRIPTION
**Pull request by PennyScissors**
Issue: https://github.com/rancher/rancher/issues/36176

### CODE REVIEW

**Comment by innobead** [comment]
cc @khushboo-rancher @kaxing @cchien816 @meldafrawi

**Comment by PennyScissors** [comment]
> LGTM Does this mean that Longhorn installation will be hidden on the Cluster Manager App page since Rancher v2.6.4?

Yes, that's correct

**Review by shuo-wu — APPROVED** [review]

**Comment by PennyScissors** [comment]
@innobead No, this only prevents new installations in Rancher >= 2.6.4. This is how we hid all the other charts in the catalog as well.

**Comment by PennyScissors** [comment]
@shuo-wu Oops, I mistakenly re-requested a review, please re-approve and I will get this merged.

**Review by shuo-wu — APPROVED** [review]

**Review by aiyengar2 — APPROVED** [review]

**Comment by PennyScissors** [comment]
This PR is currently on standby until the Longhorn team figures out what they would like to do regarding the upgrade path once charts are hidden. https://github.com/rancher/rancher/issues/36176#issuecomment-1059189404

**Comment by innobead** [comment]
cc @jenting

**Pull request closed without merging**
