### PR TITLE
Bump Epinio to 1.6.1 (2.6 dev)

### PR DESCRIPTION
**Pull request by andreas-kupries**
Ref https://github.com/epinio/epinio/issues/2036

Requires image-mirror PR.

### CODE REVIEW

**Comment by thehejik** [comment]
### QA report
#### Testing environment
Rancher `v2.6.9` on top of a single-node `v1.24.6+k3s1` cluster with incorporated traefik lb. Helm chart git repository for Epinio Rancher App installation https://github.com/epinio/charts.git and branch `epinio-1.6.1-d26`

#### Tested
• Adding the custom repository for this PR
• Installation of `Epinio  (100.0.4+up1.6.1)` App helm chart in Rancher (local k3s cluster) by using default values (+entered base epinio domain) - `epinio` and `epinio-crd` apps were successfully deployed in `cattle-epinio-system` namespace
• All the input boxed for values were ok
• All the relevant resources like pods are in `Ready` state
• Accessed `epinio-ui` over ingress, login by using default credentials
• Created epinio `workspace` namespace for its applications
• Deployment of sample-app phpinfo() app stored in local folder
• Accessing the sample-app over provided URL in epinio-ui
• All resources still ok
• Images and tags from https://github.com/rancher/image-mirror/pull/338 match with the deployed ones
• KNOWN skopeo is missing due to image format incompatability
• KNOWN export the application over epinio 1.6.1 CLI - user will get only values.yaml, it doesn't return chart neither image ref. https://github.com/epinio/epinio/issues/1965
• Uninstallation (`epinio` and then `epinio-crd`) ok

App export is still not working but the rest is working as expected. Also there is a way to disable DEX (via Edit YAML only)  and AWS/S3 access key values are not mandatory when S3 is enabled.

**Review by thehejik — APPROVED** [review]

**Comment by olblak** [comment]
@andreas-kupries They are conflict here as well

**Review by thehejik — CHANGES_REQUESTED** [review]
values.yaml should point to `rancher/mirrored-skopeo-skopeo:v1.10.0`

**Review by thehejik — CHANGES_REQUESTED** [review]
values.yaml should point to `rancher/mirrored-skopeo-skopeo:v1.10.0`

**Comment by andreas-kupries** [comment]
Fixed issue with skopeo image. Used bad version tag (needed `v1.10.0`, not `v1.10`). This hopefully fixes the issues reported by QA.

**Review by thehejik — APPROVED** [review]
Successfully revalidated, skopeo image v1.10.0 exists but the export doesn't work still.

**Review by olblak — APPROVED** [review]

**Pull request merged**
