### PR TITLE
[dev-v2.7] Bump rancher-aks-operator v1.1.0-rc2

### PR DESCRIPTION
**Pull request by mjura**
Bug fixes for:
      - AKS Updating AgentPools with custom route table is not allowed
        https://github.com/rancher/rancher/issues/40087

### CODE REVIEW

**Comment by a-blender** [comment]
@mjura,

There were 2 commits in my [example PR](https://github.com/rancher/charts/pull/2121/commits), one was for make charts

* Run a `make charts` and add it as a separate commit to update the artifact for the aks-operator and aks-operator crd charts.
* Run `make validate` locally. This checks the tracked charts in your local branch against upstream and verifies that your branch can be merged. I like to do this before I request reviews.
* Add a brief description saying why you are bumping. I would _at least_ mention the bug fixes for https://github.com/rancher/aks-operator/pull/77 https://github.com/rancher/aks-operator/pull/76 since having these available in rancher 2.7 is critical priority.

**Comment by mjura** [comment]
@annablender thank you for suggestion, I have included them into this PR

**Review by a-blender — CHANGES_REQUESTED** [review]
@mjura It looks like `Chart.yaml` for all of the aks-operator-crd and some of the aks-operator charts got removed the charts/folder. We want to remove `101.1.0+up1.0.8-rc1` and update `101.1.1+upv1.1.0-rc1 -> 101.0.1+upv1.1.0-rc2` but none of the other versions should be touched besides these two. Just remove the folders for those two charts in charts/ like you removed the binaries in assets/

**Review by a-blender — CHANGES_REQUESTED** [review]
Could you combine commits 1, 2, and 4 into one commit and then run `make charts` as your second commit? Then it will be ready to merge, thank you

**Comment by mjura** [comment]
> Could you combine commits 1, 2, and 4 into one commit and then run `make charts` as your second commit? Then it will be ready to merge, thank you

Done, please review it once again

**Review by a-blender — APPROVED** [review]

**Comment by a-blender** [comment]
Nit: It may be more helpful to name your feature branch `bump-aks-operator-v1.1.0-rc2` with the version number so it aligns with the changes made

**Review by alexander-demicev — APPROVED** [review]

**Pull request merged**
