### PR TITLE
Chart version 1.0.23

### PR DESCRIPTION
**Pull request by dlbock**
Changes included:
- Update README for Helm 3

### CODE REVIEW

**Comment by dlbock** [comment]
cc @guangbochen 
cc @wiggzz

**Comment by wiggzz** [comment]
LGTM

**Comment by dlbock** [comment]
@guangbochen Anyone able to review and merge this soon? Many thanks

**Comment by guangbochen** [comment]
LGTM, thanks

**Comment by dlbock** [comment]
@guangbochen @deniseschannon Can we get this merged soon? 😄

**Comment by deniseschannon** [comment]
@dlbock Is this a Helm 3 chart?

**Comment by wiggzz** [comment]
> @dlbock Is this a Helm 3 chart?

Yes, this chart is now supporting Helm 3.

**Comment by guangbochen** [comment]
@deniseschannon this chart is also compatible with helm v2, so I think it is good to merge.

**Comment by deniseschannon** [comment]
@wiggzz Does this chart require any Helm3 specific features. 

Rancher will only be able to leverage Helm3 specific features by adding charts into a catalog designated to be Helm3 as Helm3 is not fully backwards compatible. If this chart is okay to be deployed using Helm2 only for now and forever, then we can merge it in. If you want it to be managed by  Helm3, then you'll to add it into github.com/rancher/helm3-charts.

**Comment by dlbock** [comment]
@deniseschannon The chart itself is compatible with both Helm 2 and Helm 3.

This specific change is only in the installation instructions in the README to support installing the chart in Helm 3. If it's helpful, we can include installation and uninstallation instructions for both Helm 2 and Helm 3 in the README.

**Comment by dlbock** [comment]
@deniseschannon @guangbochen Closing this PR and opening a new one to include install/uninstall instructions for both Helm 2 and Helm 3.

Just a heads up that we will have to skip Chart version 1.0.23 and go to 1.0.24 as our equivalent Chart version 1.0.23 on  [github.com/helm](https://github.com/helm/charts/tree/master/stable/instana-agent) has already been released as it comes from the same canonical source.

**Comment by deniseschannon** [comment]
@dlbock if you want this to be deployed with helm3, you will need to add it to our github.com/rancher/helm3-charts repo. Due to helm3 not being completely backwards compatible, we have 2 repos that support charts. This repo will be dedicated to using helm2 to deploy the helm charts.

**Comment by dlbock** [comment]
@deniseschannon We understand that this repo is only for Helm 2 charts and it can stay that way for the foreseeable future. This chart itself is compatible with _both_ Helm 2 _and_ Helm 3. The only update we had to add was for the installation and uninstallation instructions and since we have the same canonical source for our chart, we'd rather not create separate READMEs for Helm 2 and Helm 3 because it will get very difficult to manage. 

We can however create a PR to add this same chart to github.com/rancher/helm3-charts.

**Pull request closed without merging**
