### PR TITLE
Fix portworx lighthouse image location

### PR DESCRIPTION
**Pull request by cryptk**
I'm not sure what the contribution policy is for this repo, but this PR creates a v1.0.1 for portworx.  The only difference is that it has a corrected image configuration for lighthouse so that the chart can actually install lighthouse.

### CODE REVIEW

**Comment by cryptk** [comment]
The linter is failing for the same reason as in the original PR (https://github.com/rancher/charts/pull/48) it's due to the required value (https://github.com/helm/helm/issues/2347).

I am unsure if you want me to do anything else in this PR to address that, or if the failure is expected/ok

**Comment by cryptk** [comment]
@guangbochen done

**Comment by harsh-px** [comment]
This can be closed as #77 has incorporated these fixes.

**Comment by guangbochen** [comment]
close of duplicate #77.

**Pull request closed without merging**
