### PR TITLE
Neuvector: Add NeuVector chart version 2.4.0

### PR DESCRIPTION
**Pull request by selvamt94**

### CODE REVIEW

**Review by crobby — DISMISSED** [review]
lgtm, working for me.

**Review by maxsokolovsky — DISMISSED** [review]

**Comment by selvamt94** [comment]
I have resumbited the PR and given below validation result
`INFO[1021] index.yaml is up-to-date
INFO[1021] Doing a final check to ensure Git is clean
INFO[1025] Successfully validated current repository!
neuvector@ubuntu1604-Helm:~/scripts/rancher/charts$
`

**Review by crobby — DISMISSED** [review]
lgtm;
I've tried it out and it seems to work well.

**Review by maxsokolovsky — DISMISSED** [review]

**Review by crobby — APPROVED** [review]
still lgtm

**Review by maxsokolovsky — APPROVED** [review]

**Pull request merged**
