### PR TITLE
Add Istio 1.11.8

### PR DESCRIPTION
**Pull request by rayandas**

### CODE REVIEW

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
LGTM, but need final merges of images before I can approve this PR. Once the image-mirror and istio-installer PRs are merged, I can do a final review to merge.

**Comment by rayandas** [comment]
After https://github.com/rancher/rancher/issues/37218 (Istio `1.12.6`) we might not need Istio `1.11.8` PR to be merged. So waiting for Istio `1.12.6` changes to be fully tested before closing this PR. 
cc: @aiyengar2

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
Need to avoid modifying the same package back and forth, should just split to multiple release lines.

In dev-v2.6, the charts-build-scripts version we use natively supports this. See comment below and https://github.com/rancher/charts-build-scripts/issues/61

**Comment by rayandas** [comment]
Closing this PR in favour of https://github.com/rancher/charts/pull/1906 (which is already merged and release.)

**Pull request closed without merging**
