### PR TITLE
Release istio 1.9.6

### PR DESCRIPTION
**Pull request by brendarearden**
This is an out-of-band release for Istio v1.9.6
This PR only adds a new version of istio and a regenerate index.yaml to include the new version of istio. 
This version of istio uses the existing kiali release that is already in production.

### CODE REVIEW

**Comment by brendarearden** [comment]
I closed a previous release pr and opened this one. https://github.com/rancher/charts/pull/1304 << caleb did have a few comments, but they are resolved with this new PR since we are not doing anything with kiali.

**Review by jiaqiluo — APPROVED** [review]
LGTM

**Review by aiyengar2 — APPROVED** [review]
LGTM. @brendarearden can you confirm the CRD chart version is correct on the index.yaml annotation? It looks good to me

**Comment by brendarearden** [comment]
@aiyengar2 `catalog.cattle.io/auto-install: rancher-kiali-server-crd=1.32.100` from the index.yaml - its the non +up version and matches what is already available in the assets dir https://github.com/rancher/charts/tree/release-v2.5/assets/rancher-kiali-server

**Pull request merged**
