### PR TITLE
Updating rancher-webhook to include new version with tolerations

### PR DESCRIPTION
**Pull request by MbolotSuse**

### CODE REVIEW

**Comment by MbolotSuse** [comment]
Related to https://github.com/rancher/rancher/issues/34159. This is my first PR affecting this repo, so it's possible that I missed one of the steps to get this put together properly. Please let me know if that is case and I'd be happy to make any corrections necessary.

**Review by genexpr — APPROVED** [review]

**Review by thedadams — APPROVED** [review]

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
@MbolotSuse can you bump to `v0.2.4-rc6`? Need it as part of https://github.com/rancher/rancher/issues/33724.

Also, for this PR the general workflow w.r.t. commits should be:
- Commit 1 - "Update rancher-webhook to include new version with tolerations": just the changes to `packages/` and the `release.yaml`
- Commit 2 - "Remove older version of chart": Output of running `CHART=rancher-webhook VERSION=1.0.3+up0.2.4-rc4 make remove` (should modify `index.yaml`, `charts/`, and `assets`/ changes)
- Commit 2 - "make charts": Output of running `make charts` (should modify `index.yaml`, `charts/`, and `assets`/ changes)

**Comment by MbolotSuse** [comment]
> @MbolotSuse can you bump to `v0.2.4-rc6`? Need it as part of [rancher/rancher#33724](https://github.com/rancher/rancher/issues/33724).
> 
> Also, for this PR the general workflow w.r.t. commits should be:
> 
> * Commit 1 - "Update rancher-webhook to include new version with tolerations": just the changes to `packages/` and the `release.yaml`
> * Commit 2 - "Remove older version of chart": Output of running `CHART=rancher-webhook VERSION=1.0.3+up0.2.4-rc4 make remove` (should modify `index.yaml`, `charts/`, and `assets`/ changes)
> * Commit 2 - "make charts": Output of running `make charts` (should modify `index.yaml`, `charts/`, and `assets`/ changes)

@aiyengar2 I've made the requested changes. Let me know if there's anything else you'd like me to do on this PR.

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Review by maxsokolovsky — APPROVED** [review]

**Pull request merged**
