### PR TITLE
Add Longhorn 1.2.6 chart with master for cluster manager

### PR DESCRIPTION
**Pull request by weizhe0422**
Signed-off-by: Ray Chang <ray.chang@suse.com>

cc @innobead @PhanLe1010

### CODE REVIEW

**Comment by innobead** [comment]
cc @khushboo-rancher

**Comment by weizhe0422** [comment]
I try to specify using Helm V3 in Catalogs setting, and it pass the KubeVersion validation and installation works fine. 

I will look into the difference between V2 and V3 when Helm does KubeVersion validation, and also update result on the comment.

     截圖 2022-11-07 下午1 30 05
     截圖 2022-11-07 下午1 36 07

**Comment by weizhe0422** [comment]
Reference https://github.com/helm/helm/issues/9371#issuecomment-780650794, the `kubeVersion` range version should be like `>= 1.18.0-0, < 1.25.0-0` both on Helm v2 and v3.

**Comment by khushboo-rancher** [comment]
Verified the chart with Rancher 2.5.15 and Rancher 2.6.9 - LGTM

Validated installation, uninstallation, upgrade(1.2.4->1.2.6) and P0 cases.

**Comment by PennyScissors** [comment]
Please make this PR to `dev` instead of `master`.

**Comment by PhanLe1010** [comment]
@PennyScissors This one is for the old rancher app catalog UI. Are you sure that we should PR into `dev` instead of `master`?

**Comment by PennyScissors** [comment]
@PhanLe1010 Yes, I know this is how it was done in the past, but the process was updated to prevent accidental releases.
https://github.com/rancher/charts/issues/1820

**Comment by PennyScissors** [comment]
The branches have the same content currently, so I think you can change the base branch to `dev` through the Github UI and it will work.

**Review by PhanLe1010 — CHANGES_REQUESTED** [review]
Could we:
1. Change commit name from `Add longhorn v1.2.4 as the latest` to `Add longhorn v1.2.6 as the latest`
2. The image tags in `questions.yaml` are not correct. 

@weizhe0422

**Comment by PennyScissors** [comment]
@PhanLe1010 @innobead Are there still plans to stop supporting this chart in the old catalog and hide it? We have [this](https://github.com/rancher/rancher/issues/36176) issue open for it, but I'm not sure what's the status on it from the longhorn side.

**Comment by weizhe0422** [comment]
@PennyScissors I have change the base branch to `dev` from `master`. 

@PhanLe1010 Commit message and `question.yaml` have been fixed. 

Thank you.

**Comment by PhanLe1010** [comment]
> @PhanLe1010 @innobead Are there still plans to stop supporting this chart in the old catalog and hide it? We have [this](https://github.com/rancher/rancher/issues/36176) issue open for it, but I'm not sure what's the status on it from the longhorn side.

Based on [this comment](https://github.com/rancher/rancher/issues/36176#issuecomment-1058691003), I think no, we don't want to hide this chart because doing so would prevent StoneX from upgrading to this chart. This destroys the original goal of this PR.

**Review by PhanLe1010 — DISMISSED** [review]
LGTM

**Comment by PennyScissors** [comment]
LGTM, but looks like you might need to rebase to get rid of that first merge commit.

**Comment by weizhe0422** [comment]
@PennyScissors Thanks for great help on Slack channel.😃 The redundant commit was remove from PR commit history now. Thanks a lot!

**Review by PennyScissors — APPROVED** [review]

**Comment by khushboo-rancher** [comment]
Final check of Longhorn installation, upgrade, uninstallation and P0 test cases - **Passed**

**Comment by prachidamle** [comment]
Merging in this PR:
-  as there is no actual CI anymore running on this repository which is deprecated. More context here: https://github.com/rancher/charts/issues/1820
- Longhorn is the only  chart being released and is validated and signed off by Longhorn QA https://github.com/rancher/charts/pull/2196#issuecomment-1309652226

**Pull request merged**
