### PR TITLE
Release Istio 1.9.500 and 1.8.600 (OOB)

### PR DESCRIPTION
**Pull request by aiyengar2**
This OOB release was manually generated since the `make stage-release` process is broken in dev-v2.5 as of now. We won't be prioritizing a fix for this process since it will soon be deprecated as soon as we migrate to v0.2.0 of the scripts, so we are just taking manual measures execute this release.

Once this PR was made, I did the following steps while on my branch / fork:

```bash
cp -R charts/rancher-istio-1.9/rancher-istio/1.9.500 .
cp -R charts/rancher-istio-1.8/rancher-istio/1.8.600 .
git checkout dev-v2.5
git pull upstream dev-v2.5 --rebase (updating to the latest from upstream)
cp -R charts/rancher-istio-1.9/rancher-istio/1.9.500-rc01 .
cp -R charts/rancher-istio-1.8/rancher-istio/1.8.600-rc01
diff -uNr 1.8.600-rc01 1.8.600 > istio_1_8_6.diff
diff -uNr 1.9.500-rc01 1.9.500 > istio_1_9_5.diff
```

The diffs produced were

```diff
diff -uNr 1.8.600-rc01/Chart.yaml 1.8.600/Chart.yaml
--- 1.8.600-rc01/Chart.yaml	2021-05-12 13:44:18.000000000 -0700
+++ 1.8.600/Chart.yaml	2021-05-12 13:43:23.000000000 -0700
@@ -1,5 +1,5 @@
 annotations:
-  catalog.cattle.io/auto-install: rancher-kiali-server-crd=1.32.100-rc01
+  catalog.cattle.io/auto-install: rancher-kiali-server-crd=1.32.100
   catalog.cattle.io/certified: rancher
   catalog.cattle.io/display-name: Istio
   catalog.cattle.io/namespace: istio-system
@@ -18,4 +18,4 @@
 - networking
 - infrastructure
 name: rancher-istio
-version: 1.8.600-rc01
+version: 1.8.600

```

```diff
diff -uNr 1.9.500-rc01/Chart.yaml 1.9.500/Chart.yaml
--- 1.9.500-rc01/Chart.yaml	2021-05-12 13:43:54.000000000 -0700
+++ 1.9.500/Chart.yaml	2021-05-12 13:43:03.000000000 -0700
@@ -1,5 +1,5 @@
 annotations:
-  catalog.cattle.io/auto-install: rancher-kiali-server-crd=1.32.100-rc01
+  catalog.cattle.io/auto-install: rancher-kiali-server-crd=1.32.100
   catalog.cattle.io/certified: rancher
   catalog.cattle.io/display-name: Istio
   catalog.cattle.io/namespace: istio-system
@@ -18,4 +18,4 @@
 - networking
 - infrastructure
 name: rancher-istio
-version: 1.9.500-rc01
+version: 1.9.500

```

### CODE REVIEW

**Review by brendarearden — APPROVED** [review]
LGTM

**Comment by aiyengar2** [comment]
On the current branch:
```bash
$ diff -uNr charts/rancher-istio-1.8/rancher-istio/1.8.600/ charts/rancher-istio-1.8/rancher-istio/1.8.500/ > istio_1_8_5_and_1_8_6.diff
arvindiyengar: ~/Rancher/charts/src/github.com/rancher/charts 
$ diff -uNr charts/rancher-istio-1.9/rancher-istio/1.9.300 charts/rancher-istio-1.9/rancher-istio/1.9.500 > istio_1_9_3_and_1_9_5.diff
```

```diff
diff -uNr charts/rancher-istio-1.8/rancher-istio/1.8.600/Chart.yaml charts/rancher-istio-1.8/rancher-istio/1.8.500/Chart.yaml
--- charts/rancher-istio-1.8/rancher-istio/1.8.600/Chart.yaml	2021-05-12 15:01:27.000000000 -0700
+++ charts/rancher-istio-1.8/rancher-istio/1.8.500/Chart.yaml	2021-05-12 15:01:27.000000000 -0700
@@ -10,7 +10,7 @@
   catalog.cattle.io/requests-memory: 2314Mi
   catalog.cattle.io/ui-component: istio
 apiVersion: v1
-appVersion: 1.8.6
+appVersion: 1.8.5
 description: A basic Istio setup that installs with the istioctl. Refer to https://istio.io/latest/
   for details.
 icon: https://charts.rancher.io/assets/logos/istio.svg
@@ -18,4 +18,4 @@
 - networking
 - infrastructure
 name: rancher-istio
-version: 1.8.600
+version: 1.8.500
diff -uNr charts/rancher-istio-1.8/rancher-istio/1.8.600/values.yaml charts/rancher-istio-1.8/rancher-istio/1.8.500/values.yaml
--- charts/rancher-istio-1.8/rancher-istio/1.8.600/values.yaml	2021-05-12 15:01:27.000000000 -0700
+++ charts/rancher-istio-1.8/rancher-istio/1.8.500/values.yaml	2021-05-12 15:01:27.000000000 -0700
@@ -1,11 +1,11 @@
 overlayFile: ""
-tag: 1.8.6
+tag: 1.8.5
 ##Setting forceInstall: true will remove the check for istio version < 1.6.x and will not analyze your install cluster prior to install
 forceInstall: false
 
 installer:
   repository: rancher/istio-installer
-  tag: 1.8.6-rancher1
+  tag: 1.8.5-rancher1
 
 ##Deprecated as of 1.8 and unsupported in 1.9, native support provided by enabling `dns.enabled=true`
 istiocoredns:
@@ -27,7 +27,7 @@
 cni:
   enabled: false
   repository: rancher/mirrored-istio-install-cni
-  tag: 1.8.6
+  tag: 1.8.5
   logLevel: info
   excludeNamespaces:
   - istio-system
@@ -47,7 +47,7 @@
 pilot:
   enabled: true
   repository: rancher/mirrored-istio-pilot
-  tag: 1.8.6
+  tag: 1.8.5
 
 telemetry:
   enabled: true
@@ -59,10 +59,10 @@
     systemDefaultRegistry: ""
   proxy:
     repository: rancher/mirrored-istio-proxyv2
-    tag: 1.8.6
+    tag: 1.8.5
   proxy_init:
     repository: rancher/mirrored-istio-proxyv2
-    tag: 1.8.6
+    tag: 1.8.5
   defaultPodDisruptionBudget:
     enabled: true
   rbac:
```

```diff
diff -uNr charts/rancher-istio-1.9/rancher-istio/1.9.300/Chart.yaml charts/rancher-istio-1.9/rancher-istio/1.9.500/Chart.yaml
--- charts/rancher-istio-1.9/rancher-istio/1.9.300/Chart.yaml	2021-05-12 15:01:27.000000000 -0700
+++ charts/rancher-istio-1.9/rancher-istio/1.9.500/Chart.yaml	2021-05-12 15:01:27.000000000 -0700
@@ -10,7 +10,7 @@
   catalog.cattle.io/requests-memory: 2314Mi
   catalog.cattle.io/ui-component: istio
 apiVersion: v1
-appVersion: 1.9.3
+appVersion: 1.9.5
 description: A basic Istio setup that installs with the istioctl. Refer to https://istio.io/latest/
   for details.
 icon: https://charts.rancher.io/assets/logos/istio.svg
@@ -18,4 +18,4 @@
 - networking
 - infrastructure
 name: rancher-istio
-version: 1.9.300
+version: 1.9.500
diff -uNr charts/rancher-istio-1.9/rancher-istio/1.9.300/values.yaml charts/rancher-istio-1.9/rancher-istio/1.9.500/values.yaml
--- charts/rancher-istio-1.9/rancher-istio/1.9.300/values.yaml	2021-05-12 15:01:27.000000000 -0700
+++ charts/rancher-istio-1.9/rancher-istio/1.9.500/values.yaml	2021-05-12 15:01:27.000000000 -0700
@@ -1,11 +1,11 @@
 overlayFile: ""
-tag: 1.9.3
+tag: 1.9.5
 ##Setting forceInstall: true will remove the check for istio version < 1.6.x and will not analyze your install cluster prior to install
 forceInstall: false
 
 installer:
   repository: rancher/istio-installer
-  tag: 1.9.3-rancher2
+  tag: 1.9.5-rancher1
 
 ##Native support for dns added in 1.8
 dns:
@@ -17,7 +17,7 @@
 cni:
   enabled: false
   repository: rancher/mirrored-istio-install-cni
-  tag: 1.9.3
+  tag: 1.9.5
   logLevel: info
   excludeNamespaces:
   - istio-system
@@ -37,7 +37,7 @@
 pilot:
   enabled: true
   repository: rancher/mirrored-istio-pilot
-  tag: 1.9.3
+  tag: 1.9.5
 
 telemetry:
   enabled: true
@@ -49,10 +49,10 @@
     systemDefaultRegistry: ""
   proxy:
     repository: rancher/mirrored-istio-proxyv2
-    tag: 1.9.3
+    tag: 1.9.5
   proxy_init:
     repository: rancher/mirrored-istio-proxyv2
-    tag: 1.9.3
+    tag: 1.9.5
   defaultPodDisruptionBudget:
     enabled: true
   rbac:
```

cc: @brendarearden

**Review by StrongMonkey — COMMENTED** [review]
@aiyengar2 Looks like timestamp have been changed on all the charts. Also the file mode is changed on index.yaml. Do we care about these changes?

**Comment by aiyengar2** [comment]
> @aiyengar2 Looks like timestamp have been changed on all the charts. Also the file mode is changed on index.yaml. Do we care about these changes?

Don't think it makes a difference. The index.yaml is always re-generated and the timestamp change is due to a constraint with the way `helm repo index` works as documented in https://github.com/helm/helm/issues/7363.

**Review by cbron — APPROVED** [review]

**Pull request merged**
