### PR TITLE
Update fleet to v0.3.2-rc1, operator to v0.1.2-rc1

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
@cbron rancher-operator is tagged wrong by darren(it should be v0.1.2-rc1) . I think it is fine, once it is verified by qa we can bump to v0.1.2.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/29696

**Review by cbron — DISMISSED** [review]
lgtm other than operator version. @StrongMonkey can you make sure that version and its assets gets removed from dev eventually. I don't want anyone down the line to install it and get confused. Also can you make sure there is an issue in 2.5.3 milestone for both of these charts.

**Comment by StrongMonkey** [comment]
@cbron Actually I am going get a new tag for it.

**Review by cbron — APPROVED** [review]

**Pull request merged**
