### PR TITLE
[dev-v2.7] rancher-logging rke2 patch kubelet logs volume mount to follow rotates

### PR DESCRIPTION
**Pull request by alexandreLamarre**
## Issue: 

https://jira.suse.com/browse/SURE-7276

## Problem

fluentbit cannot follow log rotates for the hostpath `/var/lib/rancher/rke2/agent/logs/kubelet.log` on rke2

## Solution

Mount the hostpath directory `/var/lib/rancher/rke2/agent/logs` to prevent the volume bind from locking the file `kubelet.log` so that fluentbit can follow file changes

### Manual Testing

logging on rke2 collects kubelet logs and sends them to a remote source. `/var/lib/rancher/rke2/agent/logs/kubelet.log` in the rancher-aggregator pod should not grow too large, >100Mb

### Automated Testing

N/A

## QA Testing Considerations

rancher-logging on rke2 should collect logs from kubelet 

### Regressions Considerations

N/A

### CODE REVIEW

**Review by mallardduck — APPROVED** [review]
LGTM

**Comment by MKlimuszka** [comment]
This got reverted, and has to be reintroduced.

**Comment by pankajsqe** [comment]
I created a rancher server and installed logging chart. Once It is completed I look for disk space occupied by kubelet.log which is around 15G - 16G. (Devs are looking into this.
Screenshot 2024-04-16 at 2 29 30 PM
)

Installed Rancher 2.7-head
Initial cluster : v1.24.17+rke2r1
After upgrade v1.26.13+rke2r1
Logging : rancher-logging:102.0.3-rc1+up3.17.10

_LOG size on : v1.24.17+rke2r1
ip-10-0-0-77:~ # df -h  /var/lib/rancher/rke2/agent/logs/kubelet.log
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p3   40G   15G   26G  36% /_

_LOG size on: v1.26.13+rke2r1
ip-10-0-0-77:/home/ec2-user # df -h  /var/lib/rancher/rke2/agent/logs/kubelet.log
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p3   40G   19G   22G  46% /_

**Comment by pankajsqe** [comment]
I created another rancher server on v2.7.13-rc5 and installed logging chart. Once It is completed I look for disk space occupied by kubelet.log which is around 15G - 19G.

Screenshot 2024-05-16 at 12 26 27 PM


Installed Rancher 2.7.13-rc5
Initial cluster : v1.24.17+rke2r1
After upgrade v1.26.13+rke2r1
Logging : rancher-logging:102.0.3+up3.17.10

LOG size on : v1.24.17+rke2r1
ip-10-0-0-44:/home/ec2-user # df -h /var/lib/rancher/rke2/agent/logs/kubelet.log
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p3   40G   15G   26G  37% /

LOG size on: v1.26.13+rke2r1
ip-10-0-0-44:/home/ec2-user # df -h /var/lib/rancher/rke2/agent/logs/kubelet.log
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p3   40G   19G   22G  46% /

**Comment by MKlimuszka** [comment]
We are not planning to spend the time to fix this in 2.7, but it is fixed in 2.8 and 2.9.

**Pull request merged**
