### PR TITLE
Longhorn 1.2.3 & 1.1.3 for v2.6

### PR DESCRIPTION
**Pull request by innobead**
Signed-off-by: David Ko <dko@suse.com>

After approvals, need QA (@khushboo-rancher ) to do the final verification.

### CODE REVIEW

**Comment by innobead** [comment]
After approvals, need QA (@khushboo-rancher ) to do the final verification.

**Comment by khushboo-rancher** [comment]
I'm having problem in pulling the image `rancher/mirrored-longhornio-longhorn-share-manager:v1_20211020`. pod is stuck in `Imagepullbackoff ` state.

**Comment by khushboo-rancher** [comment]
`share-manager:v1_20211020` is merged.

Validated the chart v1.2.3 - **LGTM**
Chart v1.1.3 - **LGTM**

Validated installation, uninstallation, upgrade and P0 checks. 

One observation on upgrade test, on installing v1.2.2 (previous release) Rancher is not showing upgrade icon in the installed App. Same for upgrade from v1.1.2 to v1.1.3
Screen Shot 2021-12-16 at 11 03 00 AM

**Review by jiaqiluo — APPROVED** [review]
LGTM

**Review by aiyengar2 — APPROVED** [review]
Ran the following script:

```bash
mkdir -p 1.1.2
tar xvzf assets/longhorn-1.1/longhorn-100.0.0+up1.1.2.tgz -C 1.1.2

mkdir -p 1.1.3
tar xvzf assets/longhorn-1.1/longhorn-100.0.1+up1.1.3.tgz -C 1.1.3

diff -uNr 1.1.2 1.1.3 > diff.diff
```

```diff
diff -uNr 1.1.2/longhorn/Chart.yaml 1.1.3/longhorn/Chart.yaml
--- 1.1.2/longhorn/Chart.yaml	2021-09-17 09:19:03.000000000 -0700
+++ 1.1.3/longhorn/Chart.yaml	2021-12-16 02:13:05.000000000 -0800
@@ -2,6 +2,7 @@
   catalog.cattle.io/auto-install: longhorn-crd=match
   catalog.cattle.io/certified: rancher
   catalog.cattle.io/display-name: Longhorn
+  catalog.cattle.io/kube-version: '>= v1.16.0-0, < v1.22.0-0'
   catalog.cattle.io/namespace: longhorn-system
   catalog.cattle.io/os: linux
   catalog.cattle.io/provides-gvr: longhorn.io/v1beta1
@@ -9,8 +10,9 @@
   catalog.cattle.io/release-name: longhorn
   catalog.cattle.io/type: cluster-tool
   catalog.cattle.io/ui-component: longhorn
+  catalog.cattle.io/upstream-version: 1.1.3
 apiVersion: v1
-appVersion: v1.1.2
+appVersion: v1.1.3
 description: Longhorn is a distributed block storage system for Kubernetes.
 home: https://github.com/longhorn/longhorn
 icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/longhorn/icon/color/longhorn-icon-color.png
@@ -22,7 +24,7 @@
 - device
 - iscsi
 - nfs
-kubeVersion: '>=v1.16.0-r0'
+kubeVersion: '>= v1.16.0-0, < v1.22.0-0'
 maintainers:
 - email: maintainers@longhorn.io
   name: Longhorn maintainers
@@ -37,4 +39,4 @@
 - https://github.com/longhorn/longhorn-ui
 - https://github.com/longhorn/longhorn-tests
 - https://github.com/longhorn/backing-image-manager
-version: 100.0.0+up1.1.2
+version: 100.0.1+up1.1.3
diff -uNr 1.1.2/longhorn/questions.yml 1.1.3/longhorn/questions.yml
--- 1.1.2/longhorn/questions.yml	2021-09-17 09:19:03.000000000 -0700
+++ 1.1.3/longhorn/questions.yml	2021-12-16 02:13:05.000000000 -0800
@@ -17,7 +17,7 @@
     label: Longhorn Manager Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.manager.tag
-    default: v1.1.2
+    default: v1.1.3
     description: "Specify Longhorn Manager Image Tag"
     type: string
     label: Longhorn Manager Image Tag
@@ -29,7 +29,7 @@
     label: Longhorn Engine Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.engine.tag
-    default: v1.1.2
+    default: v1.1.3
     description: "Specify Longhorn Engine Image Tag"
     type: string
     label: Longhorn Engine Image Tag
@@ -41,7 +41,7 @@
     label: Longhorn UI Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.ui.tag
-    default: v1.1.2
+    default: v1.1.3
     description: "Specify Longhorn UI Image Tag"
     type: string
     label: Longhorn UI Image Tag
@@ -53,7 +53,7 @@
     label: Longhorn Instance Manager Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.instanceManager.tag
-    default: v1_20210621
+    default: v1_20211210
     description: "Specify Longhorn Instance Manager Image Tag"
     type: string
     label: Longhorn Instance Manager Image Tag
@@ -65,7 +65,7 @@
     label: Longhorn Share Manager Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.shareManager.tag
-    default: v1_20210416
+    default: v1_20210416_patch1
     description: "Specify Longhorn Share Manager Image Tag"
     type: string
     label: Longhorn Share Manager Image Tag
@@ -77,7 +77,7 @@
     label: Longhorn Backing Image Manager Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.backingImageManager.tag
-    default: v1_20210422
+    default: v1_20210422_patch1
     description: "Specify Longhorn Backing Image Manager Image Tag"
     type: string
     label: Longhorn Backing Image Manager Image Tag
@@ -326,7 +326,7 @@
     default: "true"
   - variable: defaultSettings.replicaZoneSoftAntiAffinity
     label: Replica Zone Level Soft Anti-Affinity
-    description: "Allow scheduling new Replicas of Volume to the Nodes in the same Zone as existing healthy Replicas. Nodes don't belong to any Zone will be treated as in the same Zone. By default true."
+    description: "Allow scheduling new Replicas of Volume to the Nodes in the same Zone as existing healthy Replicas. Nodes don't belong to any Zone will be treated as in the same Zone. Notice that Longhorn relies on label `topology.kubernetes.io/zone=<Zone name of the node>` in the Kubernetes node object to identify the zone. By default true."
     group: "Longhorn Default Settings"
     type: boolean
     default: "true"
diff -uNr 1.1.2/longhorn/templates/services.yaml 1.1.3/longhorn/templates/services.yaml
--- 1.1.2/longhorn/templates/services.yaml	1969-12-31 16:00:00.000000000 -0800
+++ 1.1.3/longhorn/templates/services.yaml	2021-12-16 02:13:05.000000000 -0800
@@ -0,0 +1,24 @@
+---
+apiVersion: v1
+kind: Service
+metadata:
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
+  name: longhorn-engine-manager
+  namespace: longhorn-system
+spec:
+  clusterIP: None
+  selector:
+    longhorn.io/component: instance-manager
+    longhorn.io/instance-manager-type: engine
+---
+apiVersion: v1
+kind: Service
+metadata:
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
+  name: longhorn-replica-manager
+  namespace: longhorn-system
+spec:
+  clusterIP: None
+  selector:
+    longhorn.io/component: instance-manager
+    longhorn.io/instance-manager-type: replica
diff -uNr 1.1.2/longhorn/values.yaml 1.1.3/longhorn/values.yaml
--- 1.1.2/longhorn/values.yaml	2021-09-17 09:19:03.000000000 -0700
+++ 1.1.3/longhorn/values.yaml	2021-12-16 02:13:05.000000000 -0800
@@ -9,22 +9,22 @@
   longhorn:
     engine:
       repository: rancher/mirrored-longhornio-longhorn-engine
-      tag: v1.1.2
+      tag: v1.1.3
     manager:
       repository: rancher/mirrored-longhornio-longhorn-manager
-      tag: v1.1.2
+      tag: v1.1.3
     ui:
       repository: rancher/mirrored-longhornio-longhorn-ui
-      tag: v1.1.2
+      tag: v1.1.3
     instanceManager:
       repository: rancher/mirrored-longhornio-longhorn-instance-manager
-      tag: v1_20210621
+      tag: v1_20211210
     shareManager:
       repository: rancher/mirrored-longhornio-longhorn-share-manager
-      tag: v1_20210416
+      tag: v1_20210416_patch1
     backingImageManager:
       repository: rancher/mirrored-longhornio-backing-image-manager
-      tag: v1_20210422
+      tag: v1_20210422_patch1
   csi:
     attacher:
       repository: rancher/mirrored-longhornio-csi-attacher
```

---

Ran the following script:

```bash
mkdir -p 1.1.2-crd
tar xvzf assets/longhorn-1.1/longhorn-crd-100.0.0+up1.1.2.tgz -C 1.1.2-crd

mkdir -p 1.1.3-crd
tar xvzf assets/longhorn-1.1/longhorn-crd-100.0.1+up1.1.3.tgz -C 1.1.3-crd

diff -uNr 1.1.2-crd 1.1.3-crd > diff.diff
```

```diff
diff -uNr 1.1.2-crd/longhorn-crd/Chart.yaml 1.1.3-crd/longhorn-crd/Chart.yaml
--- 1.1.2-crd/longhorn-crd/Chart.yaml	2021-09-17 09:19:03.000000000 -0700
+++ 1.1.3-crd/longhorn-crd/Chart.yaml	2021-12-16 02:13:05.000000000 -0800
@@ -7,4 +7,4 @@
 description: Installs the CRDs for longhorn.
 name: longhorn-crd
 type: application
-version: 100.0.0+up1.1.2
+version: 100.0.1+up1.1.3
diff -uNr 1.1.2-crd/longhorn-crd/templates/crds.yaml 1.1.3-crd/longhorn-crd/templates/crds.yaml
--- 1.1.2-crd/longhorn-crd/templates/crds.yaml	2021-09-17 09:19:03.000000000 -0700
+++ 1.1.3-crd/longhorn-crd/templates/crds.yaml	2021-12-16 02:13:05.000000000 -0800
@@ -1,12 +1,13 @@
+---
 apiVersion: apiextensions.k8s.io/v1
 kind: CustomResourceDefinition
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.1.2
+    helm.sh/chart: longhorn-1.1.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.1.2
+    app.kubernetes.io/version: v1.1.3
     longhorn-manager: Engine
   name: engines.longhorn.io
 spec:
@@ -59,10 +60,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.1.2
+    helm.sh/chart: longhorn-1.1.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.1.2
+    app.kubernetes.io/version: v1.1.3
     longhorn-manager: Replica
   name: replicas.longhorn.io
 spec:
@@ -119,10 +120,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.1.2
+    helm.sh/chart: longhorn-1.1.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.1.2
+    app.kubernetes.io/version: v1.1.3
     longhorn-manager: Setting
   name: settings.longhorn.io
 spec:
@@ -156,10 +157,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.1.2
+    helm.sh/chart: longhorn-1.1.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.1.2
+    app.kubernetes.io/version: v1.1.3
     longhorn-manager: Volume
   name: volumes.longhorn.io
 spec:
@@ -216,10 +217,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.1.2
+    helm.sh/chart: longhorn-1.1.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.1.2
+    app.kubernetes.io/version: v1.1.3
     longhorn-manager: EngineImage
   name: engineimages.longhorn.io
 spec:
@@ -272,10 +273,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.1.2
+    helm.sh/chart: longhorn-1.1.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.1.2
+    app.kubernetes.io/version: v1.1.3
     longhorn-manager: Node
   name: nodes.longhorn.io
 spec:
@@ -324,10 +325,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.1.2
+    helm.sh/chart: longhorn-1.1.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.1.2
+    app.kubernetes.io/version: v1.1.3
     longhorn-manager: InstanceManager
   name: instancemanagers.longhorn.io
 spec:
@@ -376,10 +377,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.1.2
+    helm.sh/chart: longhorn-1.1.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.1.2
+    app.kubernetes.io/version: v1.1.3
     longhorn-manager: ShareManager
   name: sharemanagers.longhorn.io
 spec:
@@ -424,10 +425,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.1.2
+    helm.sh/chart: longhorn-1.1.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.1.2
+    app.kubernetes.io/version: v1.1.3
     longhorn-manager: BackingImage
   name: backingimages.longhorn.io
 spec:
@@ -437,7 +438,7 @@
     listKind: BackingImageList
     plural: backingimages
     shortNames:
-      - lhbi
+    - lhbi
     singular: backingimage
   scope: Namespaced
   versions:
@@ -468,10 +469,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.1.2
+    helm.sh/chart: longhorn-1.1.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.1.2
+    app.kubernetes.io/version: v1.1.3
     longhorn-manager: BackingImageManager
   name: backingimagemanagers.longhorn.io
 spec:
@@ -481,7 +482,7 @@
     listKind: BackingImageManagerList
     plural: backingimagemanagers
     shortNames:
-      - lhbim
+    - lhbim
     singular: backingimagemanager
   scope: Namespaced
   versions:
```

---

Ran the following script:

```bash
mkdir -p 1.2.2
tar xvzf assets/longhorn-1.2/longhorn-100.1.0+up1.2.2.tgz -C 1.2.2

mkdir -p 1.2.3
tar xvzf assets/longhorn-1.2/longhorn-100.1.1+up1.2.3.tgz -C 1.2.3

diff -uNr 1.2.2 1.2.3 > diff.diff
```

```diff
diff -uNr 1.2.2/longhorn/Chart.yaml 1.2.3/longhorn/Chart.yaml
--- 1.2.2/longhorn/Chart.yaml	2021-10-07 11:14:07.000000000 -0700
+++ 1.2.3/longhorn/Chart.yaml	2021-12-16 02:50:17.000000000 -0800
@@ -2,6 +2,7 @@
   catalog.cattle.io/auto-install: longhorn-crd=match
   catalog.cattle.io/certified: rancher
   catalog.cattle.io/display-name: Longhorn
+  catalog.cattle.io/kube-version: '>=1.18.0-0'
   catalog.cattle.io/namespace: longhorn-system
   catalog.cattle.io/os: linux
   catalog.cattle.io/provides-gvr: longhorn.io/v1beta1
@@ -9,8 +10,9 @@
   catalog.cattle.io/release-name: longhorn
   catalog.cattle.io/type: cluster-tool
   catalog.cattle.io/ui-component: longhorn
+  catalog.cattle.io/upstream-version: 1.2.3
 apiVersion: v1
-appVersion: v1.2.2
+appVersion: v1.2.3
 description: Longhorn is a distributed block storage system for Kubernetes.
 home: https://github.com/longhorn/longhorn
 icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/longhorn/icon/color/longhorn-icon-color.png
@@ -36,4 +38,4 @@
 - https://github.com/longhorn/longhorn-ui
 - https://github.com/longhorn/longhorn-tests
 - https://github.com/longhorn/backing-image-manager
-version: 100.1.0+up1.2.2
+version: 100.1.1+up1.2.3
diff -uNr 1.2.2/longhorn/questions.yml 1.2.3/longhorn/questions.yml
--- 1.2.2/longhorn/questions.yml	2021-10-07 11:14:07.000000000 -0700
+++ 1.2.3/longhorn/questions.yml	2021-12-16 02:50:17.000000000 -0800
@@ -17,7 +17,7 @@
     label: Longhorn Manager Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.manager.tag
-    default: v1.2.2
+    default: v1.2.3
     description: "Specify Longhorn Manager Image Tag"
     type: string
     label: Longhorn Manager Image Tag
@@ -29,7 +29,7 @@
     label: Longhorn Engine Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.engine.tag
-    default: v1.2.2
+    default: v1.2.3
     description: "Specify Longhorn Engine Image Tag"
     type: string
     label: Longhorn Engine Image Tag
@@ -41,7 +41,7 @@
     label: Longhorn UI Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.ui.tag
-    default: v1.2.2
+    default: v1.2.3
     description: "Specify Longhorn UI Image Tag"
     type: string
     label: Longhorn UI Image Tag
@@ -53,7 +53,7 @@
     label: Longhorn Instance Manager Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.instanceManager.tag
-    default: v1_20210731
+    default: v1_20211210
     description: "Specify Longhorn Instance Manager Image Tag"
     type: string
     label: Longhorn Instance Manager Image Tag
@@ -65,7 +65,7 @@
     label: Longhorn Share Manager Image Repository
     group: "Longhorn Images Settings"
   - variable: image.longhorn.shareManager.tag
-    default: v1_20210914
+    default: v1_20211020
     description: "Specify Longhorn Share Manager Image Tag"
     type: string
     label: Longhorn Share Manager Image Tag
diff -uNr 1.2.2/longhorn/templates/services.yaml 1.2.3/longhorn/templates/services.yaml
--- 1.2.2/longhorn/templates/services.yaml	1969-12-31 16:00:00.000000000 -0800
+++ 1.2.3/longhorn/templates/services.yaml	2021-12-16 02:50:17.000000000 -0800
@@ -0,0 +1,24 @@
+---
+apiVersion: v1
+kind: Service
+metadata:
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
+  name: longhorn-engine-manager
+  namespace: longhorn-system
+spec:
+  clusterIP: None
+  selector:
+    longhorn.io/component: instance-manager
+    longhorn.io/instance-manager-type: engine
+---
+apiVersion: v1
+kind: Service
+metadata:
+  labels: {{- include "longhorn.labels" . | nindent 4 }}
+  name: longhorn-replica-manager
+  namespace: longhorn-system
+spec:
+  clusterIP: None
+  selector:
+    longhorn.io/component: instance-manager
+    longhorn.io/instance-manager-type: replica
diff -uNr 1.2.2/longhorn/values.yaml 1.2.3/longhorn/values.yaml
--- 1.2.2/longhorn/values.yaml	2021-10-07 11:14:07.000000000 -0700
+++ 1.2.3/longhorn/values.yaml	2021-12-16 02:50:17.000000000 -0800
@@ -9,19 +9,19 @@
   longhorn:
     engine:
       repository: rancher/mirrored-longhornio-longhorn-engine
-      tag: v1.2.2
+      tag: v1.2.3
     manager:
       repository: rancher/mirrored-longhornio-longhorn-manager
-      tag: v1.2.2
+      tag: v1.2.3
     ui:
       repository: rancher/mirrored-longhornio-longhorn-ui
-      tag: v1.2.2
+      tag: v1.2.3
     instanceManager:
       repository: rancher/mirrored-longhornio-longhorn-instance-manager
-      tag: v1_20210731
+      tag: v1_20211210
     shareManager:
       repository: rancher/mirrored-longhornio-longhorn-share-manager
-      tag: v1_20210914
+      tag: v1_20211020
     backingImageManager:
       repository: rancher/mirrored-longhornio-backing-image-manager
       tag: v2_20210820
```

---

Ran the following script:

```bash
mkdir -p 1.2.2-crd
tar xvzf assets/longhorn-1.2/longhorn-crd-100.1.0+up1.2.2.tgz -C 1.2.2-crd

mkdir -p 1.2.3-crd
tar xvzf assets/longhorn-1.2/longhorn-crd-100.1.1+up1.2.3.tgz -C 1.2.3-crd

diff -uNr 1.2.2-crd 1.2.3-crd > diff.diff
```

```diff
diff -uNr 1.2.2-crd/longhorn-crd/Chart.yaml 1.2.3-crd/longhorn-crd/Chart.yaml
--- 1.2.2-crd/longhorn-crd/Chart.yaml	2021-10-07 11:14:07.000000000 -0700
+++ 1.2.3-crd/longhorn-crd/Chart.yaml	2021-12-16 02:50:17.000000000 -0800
@@ -7,4 +7,4 @@
 description: Installs the CRDs for longhorn.
 name: longhorn-crd
 type: application
-version: 100.1.0+up1.2.2
+version: 100.1.1+up1.2.3
diff -uNr 1.2.2-crd/longhorn-crd/templates/crds.yaml 1.2.3-crd/longhorn-crd/templates/crds.yaml
--- 1.2.2-crd/longhorn-crd/templates/crds.yaml	2021-10-07 11:14:07.000000000 -0700
+++ 1.2.3-crd/longhorn-crd/templates/crds.yaml	2021-12-16 02:50:17.000000000 -0800
@@ -3,10 +3,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: Engine
   name: engines.longhorn.io
 spec:
@@ -59,10 +59,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: Replica
   name: replicas.longhorn.io
 spec:
@@ -119,10 +119,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: Setting
   name: settings.longhorn.io
 spec:
@@ -156,10 +156,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: Volume
   name: volumes.longhorn.io
 spec:
@@ -216,10 +216,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: EngineImage
   name: engineimages.longhorn.io
 spec:
@@ -272,10 +272,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: Node
   name: nodes.longhorn.io
 spec:
@@ -324,10 +324,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: InstanceManager
   name: instancemanagers.longhorn.io
 spec:
@@ -376,10 +376,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: ShareManager
   name: sharemanagers.longhorn.io
 spec:
@@ -424,10 +424,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: BackingImage
   name: backingimages.longhorn.io
 spec:
@@ -468,10 +468,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: BackingImageManager
   name: backingimagemanagers.longhorn.io
 spec:
@@ -528,10 +528,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: BackingImageDataSource
   name: backingimagedatasources.longhorn.io
 spec:
@@ -584,10 +584,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: BackupTarget
   name: backuptargets.longhorn.io
 spec:
@@ -641,10 +641,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: BackupVolume
   name: backupvolumes.longhorn.io
 spec:
@@ -694,10 +694,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: Backup
   name: backups.longhorn.io
 spec:
@@ -751,10 +751,10 @@
 metadata:
   labels:
     app.kubernetes.io/name: longhorn
-    helm.sh/chart: longhorn-1.2.0
+    helm.sh/chart: longhorn-1.2.3
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/instance: longhorn
-    app.kubernetes.io/version: v1.2.0
+    app.kubernetes.io/version: v1.2.3
     longhorn-manager: RecurringJob
   name: recurringjobs.longhorn.io
 spec:
```

---

Upstream version and kubeVersion added. No other issues noted.

LGTM

**Comment by khushboo-rancher** [comment]
Created a bug for the upgrade icon not appearing in Rancher installed Apps as mentioned [here](https://github.com/rancher/charts/pull/1660#issuecomment-996151993) -  https://github.com/rancher/dashboard/issues/4786

Validation of chart - **LGTM**

**Review by khushboo-rancher — APPROVED** [review]

**Pull request merged**
