### PR TITLE
Longhorn v0.5.0 release

### PR DESCRIPTION
**Pull request by shuo-wu**

### CODE REVIEW

**Comment by guangbochen** [comment]
@shuo-wu can u rebase to the latest dev to address CI failure, thanks

**Comment by shuo-wu** [comment]
CI requires me to modify the version. Hence this pr may be merged in next Longhorn release.

**Comment by yasker** [comment]
@shuo-wu You can create a new Longhorn chart for v0.5.0 and put fixes there.

**Comment by yasker** [comment]
Add `Synchronized from github.com/rancher/longhorn/chart` in the commit message

**Comment by yasker** [comment]
@guangbochen What's going on with CI? It's failed due to other charts.

```
✖︎ charts/artifactory-ha/latest > Chart version not ok. Needs a version bump!
--
115 | ✖︎ charts/artifactory-ha/v0.8.3 > Chart version not ok. Needs a version bump!
116 | ✖︎ charts/openebs/latest > Chart version not ok. Needs a version bump!
117 | ✔︎ proposed/longhorn/latest
118 | ✔︎ proposed/longhorn/v0.4.1
119 | ✖︎ proposed/storageos-operator > Chart version not ok. Needs a version bump!
```

**Comment by yasker** [comment]
@guangbochen I unintentionally merged the PR to the dev branch. Feel free to revert the change.

**Pull request merged**
