### PR TITLE
[rancher-logging] support for logging resource specific serviceaccount annotation, e.g. for AWS STS / IRSA

### PR DESCRIPTION
**Pull request by wombelix**
## Problem

To avoid usage of long-lived credentials or EC2 Instance Profiles and to narrow down the granted permissions, it's best practice for AWS customers to use IAM Roles for Service Accounts (IRSA). In `kube-logging` and the plugin `fluent-plugin-cloudwatch-logs` this is in general supported but requires an appropriate `serviceAccount` annotation in the `Logging` resource. Every logging resource has it's own service account and therefore requires individual annotations.
Adding them after deploying `rancher-logging` is possible but more complicated and has the risk to be changed or override with the next Helm run.

In addition, I also did some minor changes, rename from Banzai to Kube and update of outdated or broken links in the app readme.

## Solution

I added a new value `loggingServiceAccountAnnotations` to add annotations based on the logging resource, usage:
```
## Syntax ##
#  <logging-name>:
#    <key>: <value>
#
## Example ##
#
#  root:
#    eks.amazonaws.com/role-arn: <RoleARN>
#
## Result - added to the Logging resource ##
#
#  spec:
#    fluentd:
#      serviceAccount:
#        metadata:
#          annotations:
#            eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/my-iam-role
#
```

My use case is limited to Amazon EKS, therefore I only added logic for the `root` and `eks` logging to use the values configured via `loggingServiceAccountAnnotations`. But for sure, this can be extended if required.

The created chart is not yet part of the PR, I would run a fresh `make charts` and push it as soon you are fine with the proposal and ready to merge.

### Manual Testing

I configured a Rancher test instance manually with the necessary annotations to push logs to CloudWatch. Then I compared my working configuration with an output of `helm template` which was identical. Full output as reference at the end of the PR.

### Automated Testing

n/a

## QA Testing Considerations

No existing logic was changed, only a new value added, I can't think of a side effect, if someone is not using the value, nothing is different to the existing behavior.

### Regressions Considerations

n/a

## Backporting considerations

I would vote for a backport to Rancher 2.6 which is still the default when Customer use `Rancher Setup` to deploy on AWS.

## Appendix

helm lint charts/rancher-logging/102.0.1+up3.17.10
```
==> Linting charts/rancher-logging/102.0.1+up3.17.10

1 chart(s) linted, 0 chart(s) failed
```

helm template output
```
---
# Source: rancher-logging/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-rancher-logging
  namespace: default
  labels:
    app.kubernetes.io/name: rancher-logging
    helm.sh/chart: rancher-logging-102.0.1_up3.17.10
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.17.10"
    app.kubernetes.io/managed-by: Helm
---
# Source: rancher-logging/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: release-name-rancher-logging
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - nodes
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - use
  - watch
- apiGroups:
  - logging-extensions.banzaicloud.io
  resources:
  - eventtailers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging-extensions.banzaicloud.io
  resources:
  - eventtailers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging-extensions.banzaicloud.io
  resources:
  - hosttailers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging-extensions.banzaicloud.io
  resources:
  - hosttailers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - clusterflows
  - clusteroutputs
  - flows
  - loggings
  - outputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - clusterflows/status
  - clusteroutputs/status
  - flows/status
  - loggings/status
  - outputs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
# Source: rancher-logging/templates/userroles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "logging-admin"
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - "logging.banzaicloud.io"
    resources:
      - flows
      - outputs
    verbs:
      - "*"
---
# Source: rancher-logging/templates/userroles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "logging-view"
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - "logging.banzaicloud.io"
    resources:
      - flows
      - outputs
      - clusterflows
      - clusteroutputs
    verbs:
      - get
      - list
      - watch
---
# Source: rancher-logging/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-rancher-logging
  labels:
    app.kubernetes.io/name: rancher-logging
    helm.sh/chart: rancher-logging-102.0.1_up3.17.10
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.17.10"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: release-name-rancher-logging
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-rancher-logging
---
# Source: rancher-logging/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-rancher-logging
  namespace: default
  labels:
    app.kubernetes.io/name: rancher-logging
    helm.sh/chart: rancher-logging-102.0.1_up3.17.10
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.17.10"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: rancher-logging
    app.kubernetes.io/instance: release-name
---
# Source: rancher-logging/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-rancher-logging
  namespace: default
  labels:
    app.kubernetes.io/name: rancher-logging
    helm.sh/chart: rancher-logging-102.0.1_up3.17.10
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.17.10"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rancher-logging
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rancher-logging
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: rancher-logging
          image: "rancher/mirrored-banzaicloud-logging-operator:3.17.10"
          args:
            - -enable-leader-election=true
          imagePullPolicy: IfNotPresent
          resources:
            {}
          ports:
            - name: http
              containerPort: 8080
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          key: cattle.io/os
          operator: Equal
          value: linux
      serviceAccountName: release-name-rancher-logging
---
# Source: rancher-logging/templates/validate-install-crd.yaml
#
---
# Source: rancher-logging/templates/validate-install.yaml
#
---
# Source: rancher-logging/templates/validate-psp-install.yaml
#
---
# Source: rancher-logging/templates/loggings/eks/logging.yaml
####### map[apiVersion:logging.banzaicloud.io/v1beta1 kind:Logging metadata:map[labels:map[app.kubernetes.io/instance:release-name app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:rancher-logging app.kubernetes.io/version:3.17.10 helm.sh/chart:rancher-logging-102.0.1_up3.17.10] namespace:default] spec:map[controlNamespace:default fluentbit:map[image:map[repository:rancher/mirrored-fluent-fluent-bit tag:1.9.5] nodeSelector:map[kubernetes.io/os:linux] tolerations:[map[effect:NoSchedule key:cattle.io/os operator:Equal value:linux] map[effect:NoSchedule key:node-role.kubernetes.io/controlplane value:true] map[effect:NoExecute key:node-role.kubernetes.io/etcd value:true]]] fluentd:map[configReloaderImage:map[repository:rancher/mirrored-jimmidyson-configmap-reload tag:v0.4.0] disablePvc:true image:map[repository:rancher/mirrored-banzaicloud-fluentd tag:v1.14.6-alpine-5] livenessProbe:map[initialDelaySeconds:30 periodSeconds:15 tcpSocket:map[port:24240]] nodeSelector:map[kubernetes.io/os:linux] security:map[podSecurityContext:map[runAsUser:100]] tolerations:[map[effect:NoSchedule key:cattle.io/os operator:Equal value:linux]]]]]

apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rancher-logging
    app.kubernetes.io/version: 3.17.10
    helm.sh/chart: rancher-logging-102.0.1_up3.17.10
  name: release-name-eks
  namespace: default
spec:
  controlNamespace: default
  fluentbit:
    disableKubernetesFilter: true
    extraVolumeMounts:
    - destination: /var/log/messages
      readOnly: true
      source: /var/log/messages
    image:
      repository: rancher/mirrored-fluent-fluent-bit
      tag: 1.9.5
    inputTail:
      Parser: syslog
      Path: /var/log/messages
      Tag: eks
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: "true"
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: "true"
  fluentd:
    configReloaderImage:
      repository: rancher/mirrored-jimmidyson-configmap-reload
      tag: v0.4.0
    disablePvc: true
    image:
      repository: rancher/mirrored-banzaicloud-fluentd
      tag: v1.14.6-alpine-5
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 15
      tcpSocket:
        port: 24240
    nodeSelector:
      kubernetes.io/os: linux
    security:
      podSecurityContext:
        runAsUser: 100
    serviceAccount:
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/my-iam-role-for-logging-eks
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
---
# Source: rancher-logging/templates/loggings/root/logging.yaml
####### map[apiVersion:logging.banzaicloud.io/v1beta1 kind:Logging metadata:map[labels:map[app.kubernetes.io/instance:release-name app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:rancher-logging app.kubernetes.io/version:3.17.10 helm.sh/chart:rancher-logging-102.0.1_up3.17.10] namespace:default] spec:map[controlNamespace:default fluentbit:map[image:map[repository:rancher/mirrored-fluent-fluent-bit tag:1.9.5] nodeSelector:map[kubernetes.io/os:linux] tolerations:[map[effect:NoSchedule key:cattle.io/os operator:Equal value:linux] map[effect:NoSchedule key:node-role.kubernetes.io/controlplane value:true] map[effect:NoExecute key:node-role.kubernetes.io/etcd value:true]]] fluentd:map[configReloaderImage:map[repository:rancher/mirrored-jimmidyson-configmap-reload tag:v0.4.0] disablePvc:true image:map[repository:rancher/mirrored-banzaicloud-fluentd tag:v1.14.6-alpine-5] livenessProbe:map[initialDelaySeconds:30 periodSeconds:15 tcpSocket:map[port:24240]] nodeSelector:map[kubernetes.io/os:linux] security:map[podSecurityContext:map[runAsUser:100]] tolerations:[map[effect:NoSchedule key:cattle.io/os operator:Equal value:linux]]]]]

apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rancher-logging
    app.kubernetes.io/version: 3.17.10
    helm.sh/chart: rancher-logging-102.0.1_up3.17.10
  name: release-name-root
  namespace: default
spec:
  controlNamespace: default
  fluentbit:
    image:
      repository: rancher/mirrored-fluent-fluent-bit
      tag: 1.9.5
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: "true"
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: "true"
  fluentd:
    configReloaderImage:
      repository: rancher/mirrored-jimmidyson-configmap-reload
      tag: v0.4.0
    disablePvc: true
    image:
      repository: rancher/mirrored-banzaicloud-fluentd
      tag: v1.14.6-alpine-5
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 15
      tcpSocket:
        port: 24240
    nodeSelector:
      kubernetes.io/os: linux
    security:
      podSecurityContext:
        runAsUser: 100
    serviceAccount:
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/my-iam-role-for-logging-root
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
```

### CODE REVIEW

**Comment by wombelix** [comment]
During SUSECON 23 I met @k0da and learned that he create a similar PR last year October (https://github.com/rancher/charts/pull/2176). 
I didn't had time yet to try his approach and to identify which one should be followed to get the feature implemented. 
I would love the see some input and feedback from one of the rancher charts maintainers about it.

**Comment by kevinayres** [comment]
Who is monitoring and reviewing these PR's?

**Comment by nicholasSUSE** [comment]
Hello @wombelix @aiyengar2 
Is this Pull Request still relevant? 
Can I close it?

**Comment by wombelix** [comment]
> Hello @wombelix @aiyengar2 
> Is this Pull Request still relevant? 
> Can I close it?

Yes the PR is still relevant, as you can see, no one reviewed it or provided feedback yet.

**Comment by k0da** [comment]
@wombelix Mine got closed already :D

**Comment by nicholasSUSE** [comment]
@MKlimuszka 
I think rancher-logging is a chart from your team. 
Can you assign someone to review this PR?

**Comment by recena** [comment]
@nicholasSUSE According to the `CODEOWNER` definition, @joshmeranda is the only one who can review and approved it.

**Review by joshmeranda — CHANGES_REQUESTED** [review]
HI @wombelix thanks for your contribution!

I like the fix for this, I would definitely like to get these annotations in. Sounds like they will be useful!

I have a few thoughts:
1. I don't want to change the README for anything other than new values and the like, to help keep us as close to the original chart as possible and avoid confusion. Plus from what I can tell any searching for "banzaicloud logging operator" will pull up the docs for kube-logging anyway. So I'd prefer to remove the first commit (`fcb8bf1`).
2. It is easier for us to backport than it is to forwardport. Can you update the PR to point to the `dev-v2.9` branch? (sorry I get this is annoying since its out of date because no-one approved it earlier).

**Comment by wombelix** [comment]
> HI @wombelix thanks for your contribution!
> 
> I like the fix for this, I would definitely like to get these annotations in. Sounds like they will be useful!
> 
> I have a few thoughts:
> 
> 1. I don't want to change the README for anything other than new values and the like, to help keep us as close to the original chart as possible and avoid confusion. Plus from what I can tell any searching for "banzaicloud logging operator" will pull up the docs for kube-logging anyway. So I'd prefer to remove the first commit (`fcb8bf1`).
> 2. It is easier for us to backport than it is to forwardport. Can you update the PR to point to the `dev-v2.9` branch? (sorry I get this is annoying since its out of date because no-one approved it earlier).

Thanks @joshmeranda , I'm going to remove the doc related commit and rebase the other one, please ignore that I now pushed all commits since this PR was created, looked OK on my machine, let me sort that out quickly.

**Comment by wombelix** [comment]
@joshmeranda ok changing the PR base to `dev-v2.9` did the trick. Any other thoughts about the suggested change? Anything that could / should be improved from a naming / implementation perspective?

**Comment by joshmeranda** [comment]
Looks pretty solid to me. Good conditionals, name is fine (maybe a tad long but thats just a nit), and an example in values.yaml. We don't have to worry about bumping version for dev-v2.9. LGTM (obviously once `make charts` and `make validate` are run)

**Comment by wombelix** [comment]
> Looks pretty solid to me. Good conditionals, name is fine (maybe a tad long but thats just a nit), and an example in values.yaml. We don't have to worry about bumping version for dev-v2.9. LGTM (obviously once `make charts` and `make validate` are run)

Thank you, I can change the name if you have a Idea for a shorter one :D 
I did a `make charts` and `make validate` on my dev machine, no errors.
Are any other tests or updates required from me?

**Comment by wombelix** [comment]
@joshmeranda now I've got what you meant, sorry, had to check the development guide again after such a long time. I updated the patch, also created and committed the package. Let me know if anything else is needed to merge.

**Comment by kevinayres** [comment]
@joshmeranda can you please take a look at this? Thanks.

**Review by joshmeranda — APPROVED** [review]

**Comment by wombelix** [comment]
Thank you @joshmeranda! Is there anything else needed to merge the PR? All CI checks seem to be fine.
And do you know if it will be backported into 2.8?

**Comment by joshmeranda** [comment]
Sorry got pulled away on something else! No immediate plans to backport just due to higher priority things in the pipeline, but not out of the question.

**Pull request merged**
