### PR TITLE
Epinio bump to 1.10.0

### LINKED ISSUE #2612: Epinio `v1.10.0` Rancher Marketplace update
We need to bump the latest Epinio version in the Rancher Marketplace.

### PR DESCRIPTION
**Pull request by andreas-kupries**
## Issue:

Fix https://github.com/epinio/epinio/issues/2612

## Problem

Add Epinio 1.10.0 to the set of charts.

:warning: This PR depends on https://github.com/rancher/image-mirror/pull/475.
:warning: The image-mirror PR has to be merged before testing this one becomes possible.

## Testing

to come

### CODE REVIEW

**Comment by andreas-kupries** [comment]
@thehejik Testing should be possible now - https://github.com/rancher/image-mirror/pull/475 was merged today

**Review by thehejik — APPROVED** [review]
## QA report
#### Testing setup:
• git repo: `https://github.com/epinio/charts.git` branch: `epinio2612-bump-to-1.10.0`
• Installation of Epinio `103.0.2+up1.10.0` in Rancher `v2.8.0-alpha2` with Kubernetes version `v1.27.6+k3s1`

#### Main checks:
• App helm chart in Rancher (local k3s cluster) by using default values (+entered base epinio domain) - epinio and epinio-crd apps were successfully deployed in cattle-epinio-system namespace
• All the input boxed for values were ok (Ingress class for the server, dex and for apps were added), **new `letsencrypt-staging` issuer present**
• No k8s API Deprecation messages present in the helm install log
• All the relevant resources like pods are in Ready state
• Accessed epinio-ui over ingress, login by using default credentials
• Login by using local Auth Provider over DEX

#### Specific checks once Epinio is deployed on MinIO as default storage:
• Created epinio workspace namespace for its applications
• Accessing the sample-app over provided URL in epinio-ui
• Deployment of sample-app phpinfo() app stored in local folder
• Bind of mysql-dev service to app
• Deployment of gitlab application both UI and CLI - **used private suse gitlab instance and epinio gitconfig** for accessing it (gitlab provider in CLI, generic git provider in UI)
• Checked export app images using UI and working fine. (no trace of manifest-undefined file)
• All resources still ok

#### Other checks:
• Tested as well deployment of Epinio with s3gw, application installation, simple app push and uninstall
• Upgrade of the release Epinio `103.0.1+up1.9.0` to `103.0.2+up1.10.0` with working app
• Uninstallation (epinio and then epinio-crd)

**Comment by andreas-kupries** [comment]
@olblak This is approved now, and could be merged.

I am two minds what to do about the CI failures here.
The `container images` issue may go away on a retrigger, now that images-mirror is merged and done.
Do not have the ability to retrigger anything however.
I do not understand the issue with the `bot validation` at all.
So, not sure if these are things which have to be fixed before we can merge, or not.

**Comment by olblak** [comment]
> I do not understand the issue with the `bot validation` at all.

 
image

**Review by olblak — APPROVED** [review]

**Pull request merged**
