### PR TITLE
Csp adapter bump 2.0.3 rc1

### PR DESCRIPTION
**Pull request by mbelur**
## Problem:
Support for k8s 1.27

## Testing:

-  Built the rancher image locally with the changes that support k8s 1.27 and installed this on EKS K8s 1.27 cluster
-  Install the CSP adapter with these changes on an EKS Kubernetes (K8s) 1.27 cluster.
-  Created a downstream EKS cluster with 21 nodes (with 1 entitlement) to trigger out-of-compliance message. When the downstream cluster was destroyed, validate that the out-of-compliance message is no longer displayed.
-  Validate that the support config

### CODE REVIEW

**Review by MbolotSuse — APPROVED** [review]

**Comment by recena** [comment]
According to the `CODEOWNER` [definition](https://github.com/rancher/charts/blob/dev-v2.9/.github/CODEOWNER#L39), this PR can be approved by:

- @rancher/mapps (team)
- @rancher/socket (team)

And @MbolotSuse is not part of those teams.

**Comment by jeremy-moffitt** [comment]
@guangyee @chajain please review Meeras PR, thanks!

**Comment by jeremy-moffitt** [comment]
> According to the `CODEOWNER` [definition](https://github.com/rancher/charts/blob/dev-v2.9/.github/CODEOWNER#L39), this PR can be approved by:
> 
> * @rancher/mapps (team)
> * @rancher/socket (team)
> 
> And @MbolotSuse is not part of those teams.

Thanks! We took this over from Michael and he's been helping us through the process. We'll get someone within the team to do a review.

**Review by guangyee — APPROVED** [review]
looks good to me

**Comment by recena** [comment]
@jeremy-moffitt Thank you so much! I can merge it but I think it is better if the changes are reviewed by the proper engineers.

**Comment by recena** [comment]
@mbelur For upcoming pull request, you can add @rancher/socket (team) as reviewer.

**Comment by mbelur** [comment]
> @mbelur For upcoming pull request, you can add @rancher/socket (team) as reviewer.

sure will do. thanks

**Comment by jeremy-moffitt** [comment]
@recena Meera can't add anyone as a reviewer, and Guang (who can) isnt seeing our team in the dropdown... guessing I need to file an eio ticket around permissions?

**Comment by jeremy-moffitt** [comment]
looks like its fixed, thank you @recena !! really appreciate the assist on this

**Review by jeremy-moffitt — APPROVED** [review]

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Pull request merged**
