### PR TITLE
[dev-v2.10] longhorn 1.7.2 add

### PR DESCRIPTION
**Pull request by mantissahz**
Release Longhorn v1.7.2 into Rancher 2.10

Longhorn https://github.com/longhorn/longhorn/issues/9603

cc @innobead @derekbit @rebeccazzzz @PhanLe1010 @khushboo-rancher @roger-ryao

### CODE REVIEW

**Comment by khushboo-rancher** [comment]
@roger-ryao Could you please help with the testing?

**Comment by roger-ryao** [comment]
> @roger-ryao Could you please help with the testing?

**Test Conditions:**
- Rancher : `v2.10.0`

**Verify is passed as follows step**
- [x] Fresh installation `105.1.0+up1.7.2`
- [X] Deploy workloads with volume
- [x] Scale down/up workload
- [x] Trigger replica rebuilding
- [x] Uninstallation

**Comment by PhanLe1010** [comment]
> > @roger-ryao Could you please help with the testing?
> 
> **Test Conditions:**
> 
> * Rancher : `v2.10.0`
> 
> **Verify is passed as follows step**
> 
> * [x]  Fresh installation `105.1.0+up1.7.2`
> * [x]  Deploy workloads with volume
> * [x]  Scale down/up workload
> * [x]  Trigger replica rebuilding
> * [x]  Uninstallation

Can you help to verify Rancher Prime with default Prime registry @roger-ryao ?

**Review by PhanLe1010 — COMMENTED** [review]
cc @mantissahz  Same as https://github.com/rancher/charts/pull/4782#pullrequestreview-2460378064

**Comment by mantissahz** [comment]
>Can we remove:
>- ./packages/longhorn/longhorn/longhorn-1.5
>- ./packages/longhorn-crd/longhorn-1.5

Hi @PhanLe1010, packages/longhorn/longhorn*/longhorn-1.5 are removed.

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by PhanLe1010** [comment]
After mergin the PR https://github.com/rancher/charts/pull/4782, there are conflict. Could you please help to resolve it? @mantissahz Thank you

**Review by PhanLe1010 — APPROVED** [review]

**Pull request merged**
