### PR TITLE
[release-v2.9] Restrict when to show the validation suggestion 

### PR DESCRIPTION
**Pull request by nicholasSUSE**
This was just a `cherry-pick` from Pull Request: https://github.com/rancher/charts/pull/3441

- Realized an extra step was needed since we can't use the `paths` filter on `pull_request_review` events. 
- Added extra logic using JavaScript to check the modified files and halt job execution.

### CODE REVIEW

**Comment by nicholasSUSE** [comment]
canceling release-v2.9 because of the build lacking maintenance.

**Review by recena — APPROVED** [review]

**Review by lucasmlp — CHANGES_REQUESTED** [review]
We should add the same filters in the Validation Check workflow. Otherwise it'll block PRs because the CI would be checking for a comment that doesn't exist, like this:
https://github.com/rancher/charts/pull/3492#issuecomment-1956777009

**Review by lucasmlp — COMMENTED** [review]
Testing filter with modification outside specified folders

**Review by lucasmlp — APPROVED** [review]
Great work @nicholasSUSE 
Thank you 🚀

**Pull request merged**
