### PR TITLE
[dev-v2.9] rancher-provisioning-capi 104.0.0+up0.3.0-rc.1 add

### PR DESCRIPTION
**Pull request by chiukapoor**
## Update
- Add rancher-provisioning-capi 104.0.0+up0.3.0-rc.1 chart with the latest provisioning commit https://github.com/rancher/provisioning/commit/0382fa7ef8c430b455b58327512d67523a53ddd6.

## Related
- https://github.com/rancher/rancher/issues/45089

### CODE REVIEW

**Review by snasovich — APPROVED** [review]

**Review by kinarashah — APPROVED** [review]

**Review by Oats87 — CHANGES_REQUESTED** [review]
I'm unsure of why we're updating a chart that is now in `dev-v2.9` ... seems the upstream chart version should have been bumped when we updated the CAPI version.

**Comment by chiukapoor** [comment]
> I'm unsure of why we're updating a chart that is now in `dev-v2.9` ... seems the upstream chart version should have been bumped when we updated the CAPI version.

Bumped the upstream chart `0.3.0-rc.1` and added rancher-provisioning-capi `104.0.0+up0.3.0-rc.1` chart

**Review by snasovich — CHANGES_REQUESTED** [review]
@chiukapoor , thank you for updating the versioning.
However, we don't want to release both `104.0.0+up0.3.0-rc.1` and `104.0.0+up0.2.0` charts. `104.0.0+up0.3.0-rc.1` should basically replace `104.0.0+up0.2.0`.

**Comment by chiukapoor** [comment]
> @chiukapoor , thank you for updating the versioning. However, we don't want to release both `104.0.0+up0.3.0-rc.1` and `104.0.0+up0.2.0` charts. `104.0.0+up0.3.0-rc.1` should basically replace `104.0.0+up0.2.0`.

Removed chart `104.0.0+up0.2.0` in https://github.com/rancher/charts/pull/4107/commits/d03e9abe6bbd601c603f8124a68a0a016be3df38

**Review by snasovich — APPROVED** [review]

**Review by Oats87 — APPROVED** [review]

**Pull request merged**
