### PR TITLE
Add fleet v0.3.5 chart back

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Review by jiaqiluo — CHANGES_REQUESTED** [review]
I see fleet 0.3.500 in the release-v2.5 branch https://github.com/rancher/charts/tree/release-v2.5/assets/fleet

should we add 0.3.500 instead of 0.3.500+up0.3.5?

**Comment by StrongMonkey** [comment]
@jiaqiluo Not sure if it is possible given the current chart build script version. But.. I can manually pick changes from previous version, not sure if this matters.

**Comment by jiaqiluo** [comment]
@StrongMonkey  we can get the release-v2.6 synced with the release-v2.5 first, then you just need to run `make validate` to get the 0.3.500 in your branch.

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
@strongmonkey, as discussed offline the fix to add back in this chart will be done in https://github.com/rancher/charts/pull/1281.

Can you close out this PR in favor of that (unless there are any other concerns?)

**Pull request closed without merging**
