### PR TITLE
Portworx release 0.1

### LINKED ISSUE #307: Fix default kvdb URL in the Portworx chart
Commit https://github.com/rancher/charts/commit/0818be1901a94a64fb91c7e29e4fe0fb199e4cea added 192.168.70.90 as the default etcd for all Portworx clusters. 

Since this is an etcd instance that doesn't exist, all PX installs are now failing.

@guangbochen can you please help revert this commit?

### PR DESCRIPTION
**Pull request by trierra**
* Done improvements to the storage section in the portworx rancher catalog.
* Added AWS, GKE, and onprem support
* Added support kubernetes v1.6 
* Closes #307

Notes: 

lint is failing because of required error in portworx-ds.yaml L102

### CODE REVIEW

**Comment by harsh-px** [comment]
@guangbochen can you help review this?

**Comment by guangbochen** [comment]
@harsh-px  @trierra  This is LGTM, but for CI lint failure you can add a new file under `portworx/v1.0.x/ci/test-values.yaml` with the following content like:
```YAML
etcdType: Built-in                        # KVDB type
````
and it should make the link test passed, thanks.

**Comment by trierra** [comment]
@guangbochen please see the updates

**Comment by guangbochen** [comment]
LGTM, thanks.

**Pull request merged**
