### PR TITLE
[dev-v2.9] Restrict branch creation

### PR DESCRIPTION
**Pull request by lucasmlp**
This PR restricts the branch creation in this repository to the members of @rancher/mapps 
If a user outside the Mapps team creates a branch in this repo, it will be removed by the enforce-branch-creation-policy workflow.

### CODE REVIEW

**Comment by adamkpickering** [comment]
I think this is possible through the repo config. See Settings > Branches > Restrict who can push to matching branches > Restrict pushes that create matching branches. Alternatively, I believe a branch ruleset (Settings > Rules > Rulesets) can do the same thing, and I get the impression that rulesets are easier to understand.

**Comment by recena** [comment]
> I think this is possible through the repo config. See Settings > Branches > Restrict who can push to matching branches > Restrict pushes that create matching branches. Alternatively, I believe a branch ruleset (Settings > Rules > Rulesets) can do the same thing, and I get the impression that rulesets are easier to understand.

@lucasmlp Have we evaluated what @adamkpickering proposes?

**Comment by lucasmlp** [comment]
@recena looking into it now

**Comment by lucasmlp** [comment]
@adamkpickering thanks for the amazing tip. I created a ruleset for it Closing this PR as it's not necessary anymore

**Pull request closed without merging**
