### PR TITLE
[dev-v2.7] Add Longhorn 1.5.4 chart

### PR DESCRIPTION
**Pull request by mantissahz**
Release Longhorn v1.5.4 into Rancher 2.7

Longhorn https://github.com/longhorn/longhorn/issues/7878
Rancher https://github.com/rancher/rancher/issues/43676

Signed-off-by: James Lu [james.lu@suse.com](mailto:james.lu@suse.com)

cc @innobead @PhanLe1010 @khushboo-rancher @roger-ryao

Waiting for Longhorn 1.5.4 images merged into the Rancher image-mirror list.

### CODE REVIEW

**Comment by roger-ryao** [comment]
Prerequisites:
- Set the Concurrent Automatic Engine Upgrade Per Node Limit to a value greater than 0.
- `LONGHORN_REPO` is set to `longhornio`.
- Rancher : v2.7.10

Verify is passed as follows step
- [x] Fresh installation
- [x] Uninstallation
- [x] Upgrade from `v1.5.3` - > `v1.5.4`
- [x] Upgrade from `v1.4.4` - > `v1.5.4`

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by PhanLe1010** [comment]
This PR is blocked by the PR https://github.com/rancher/image-mirror/pull/584

**Comment by PhanLe1010** [comment]
Image PR is ready at https://github.com/rancher/image-mirror/pull/585

**Comment by PhanLe1010** [comment]
Image PR was merged. This PR is ready for merging.

Can you git commit amend and force push to retrigger the PR validation pipeline @mantissahz ?

**Comment by PhanLe1010** [comment]
From the [error](https://github.com/rancher/charts/actions/runs/8181256527/job/22370733735?pr=3539#:~:text=3147-,time%3D%222024%2D03%2D07T01%3A10%3A37Z%22%20level%3Derror%20msg%3D%22The%20following,ui%2Dplugin%2Doperator%3A%5B102.0.3%2Bup0.2.1%5D%20ui%2Dplugin%2Doperator%2Dcrd%3A%5B102.0.3%2Bup0.2.1%5D%5D%22,-3148):

`time="2024-03-07T01:10:37Z" level=error msg="The following released assets have been removed: map[prometheus-federator:[3.0.1+up0.3.3] rancher-alerting-drivers:[102.1.1] rancher-backup:[102.0.3+up3.1.3] rancher-backup-crd:[102.0.3+up3.1.3] rancher-cis-benchmark:[4.3.0] rancher-cis-benchmark-crd:[4.3.0] rancher-csp-adapter:[2.0.4] rancher-gatekeeper:[102.1.1+up3.13.0] rancher-gatekeeper-crd:[102.1.1+up3.13.0] rancher-monitoring:[102.0.3+up40.1.2] rancher-monitoring-crd:[102.0.3+up40.1.2] rancher-project-monitoring:[3.0.1+up0.3.3] rancher-pushprox:[102.0.2] rancher-vsphere-cpi:[102.2.0+up1.6.0] rancher-vsphere-csi:[102.2.0+up3.0.2-rancher1] rancher-webhook:[2.0.7+up0.3.7] sriov:[102.2.0+up0.1.0] sriov-crd:[102.2.0+up0.1.0] system-upgrade-controller:[102.2.0+up0.6.0] ui-plugin-operator:[102.0.3+up0.2.1] ui-plugin-operator-crd:[102.0.3+up0.2.1]]"`

Looks like we the dev-2.7 branch is very far away from the release-v2.7 branch so validation CI is yelling that a lots of charts are missing (being removed). I am thinking if Rancher team changed the policy and start working on dev-v2.7.11 branch instead of dev-2.7 branch?

dev-2.7.11 branch is closer to release-v2.7 https://github.com/rancher/charts/tree/dev-v2.7.11/charts

**Comment by mantissahz** [comment]
After dev-v2.7.11 is synced to dev-v2.7 (https://github.com/rancher/charts/pull/3559)

**Review by nicholasSUSE — APPROVED** [review]
LGTM

**Review by PhanLe1010 — APPROVED** [review]

**Review by shuo-wu — APPROVED** [review]

**Pull request merged**
