### PR TITLE
[dev-v2.5] cut rancher-backup and rancher-backup-crd 1.0.5-rc1

### PR DESCRIPTION
**Pull request by jiaqiluo**
Backport of https://github.com/rancher/charts/pull/1214

Issues:
https://github.com/rancher/backup-restore-operator/issues/81
https://github.com/rancher/backup-restore-operator/issues/90
https://github.com/rancher/backup-restore-operator/issues/104

### CODE REVIEW

**Comment by cbron** [comment]
This goes straight into the divergence convo, but I think this should go into dev-v2.6

**Comment by jiaqiluo** [comment]
> This goes straight into the divergence convo, but I think this should go into dev-v2.6, or at least both, and make backport issues.

Agree. 
I will rename this to a backport PR and make a new PR to the dev-2.6 branch once this one is reviewed and ready to go.

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Comment by aiyengar2** [comment]
> This goes straight into the divergence convo, but I think this should go into dev-v2.6, or at least both and make backport issues.

Based on the divergence convo now, this PR should get merged before 2.6. Since we want to make sure any version that showed up in dev-v2.5 is also available in dev-v2.6.

**Comment by cbron** [comment]
Yes, we need to do a sweep for that in general, that all 2.5 versions are in 2.6. Made issue: https://github.com/rancher/rancher/issues/32842

**Comment by cbron** [comment]
That being said, looking at all 3 of the issues attached for this, I'm not sure we need to backport (sorry for confusion). I think we should just put all 3 in 2.6 (especially aks) and then if a user really needs the s3 one we can backport that specifically to 1.0.5. The 2.6 PR should be 1.1.1 now, based on our discussion.

**Comment by jiaqiluo** [comment]
Close this PR. 
no need to go to the dev-v2.5 branch.

**Comment by philomory** [comment]
Aw, it would have been kinda nice to have the ServiceAccount annotations one available for 2.5.

**Comment by jiaqiluo** [comment]
The ServiceAccount annotations will be available in the new rancher-backup chart in v2.5.10

**Pull request closed without merging**
