### PR TITLE
Generate asset on different branch

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/28711

**Comment by StrongMonkey** [comment]
https://github.com/StrongMonkey/git-auto-commit-action/commit/505389d146760a6e0721ff81fd856b583d5ad84e forked github action to create an orphan branch if branch doesn't exist.

**Comment by StrongMonkey** [comment]
@cbron We also need to fork this action under rancher org if it is approved.

**Review by cbron — APPROVED** [review]
lgtm, just need to get into rancher org like you said.

**Comment by StrongMonkey** [comment]
@cbron The original author actually merged my PR, so we can use upstream now. Pr is updated.

**Comment by StrongMonkey** [comment]
https://github.com/stefanzweifel/git-auto-commit-action/pull/95

**Review by cbron — APPROVED** [review]
Sweet, that makes this much easier.

**Pull request merged**
