### PR TITLE
Remove rancher-wins-upgrader chart from 2.7

### PR DESCRIPTION
**Pull request by doflamingo721**
Linked issue:
https://github.com/rancher/rancher/issues/38965

Reverting commits https://github.com/rancher/charts/commit/c9c69d662f9c89b77e2962155ef178624d90e049 and https://github.com/rancher/charts/commit/4f6845e3949e1a5e9e454bfbe1b963debafb3472 since rke1 windows is no longer supported and rke2 does not need this chart.

### CODE REVIEW

**Review by mitulshah-suse — DISMISSED** [review]

**Comment by prachidamle** [comment]
@aiyengar2 We should be fine to remove this chart from packages as well if this chart is not going to be supported in 2.7.0? Refer to this question here https://github.com/rancher/rancher/issues/38965#issuecomment-1264088263

**Comment by aiyengar2** [comment]
> @aiyengar2 We should be fine to remove this chart from packages as well if this chart is not going to be supported in 2.7.0? Refer to this question here [rancher/rancher#38965 (comment)](https://github.com/rancher/rancher/issues/38965#issuecomment-1264088263)

yes, we should remove it from packages. @mitulshah-suse can you make the corresponding changes?

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
package should be deleted too, as commented above

**Comment by doflamingo721** [comment]
@aiyengar2 @prachidamle , I have removed the chart from packages as well. Can you please review it again? TIA!

**Review by aiyengar2 — DISMISSED** [review]

**Comment by kinarashah** [comment]
@doflamingo721 Looks like there's a conflict in release.yaml, could you fix it today? I'll re-approve and merge later.

**Comment by doflamingo721** [comment]
@kinarashah I have resolved the conflicts. Can you please review the PR?

**Review by mitulshah-suse — APPROVED** [review]

**Pull request merged**
