### PR TITLE
    Updated to OpenEBS v2.5.0 release and set rancher max version to 2.5.6

### PR DESCRIPTION
**Pull request by nareshdesh**
Updated to v2.5.0 release
      updated README.md
      updated values.yaml
      updated Chart.yaml
      updated questions.yml
   Added rancher_max_version to 2.5.6 in questions.yml

### CODE REVIEW

**Comment by nareshdesh** [comment]
Linted the chart manually with the following commands

```
docker run -v $(pwd):/rancher-helm2-charts:Z -w /rancher-helm2-charts quay.io/helmpack/chart-testing:latest ct lint --remote rancher-helm2-charts --target-branch master --validate-maintainers=false --chart-dirs charts/openebs
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Linting charts...

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")
------------------------------------------------------------------------------------------------------------------------

Linting chart 'openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")'
Checking chart 'openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")' for a version bump...
Unable to find chart on master. New chart detected.
Validating /rancher-helm2-charts/charts/openebs/v2.5.0/Chart.yaml...
Validation success! 👍
==> Linting charts/openebs/v2.5.0

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully

[k8s@dev-centos charts]$ git remote -v
origin  https://github.com/nareshdesh/charts.git (fetch)
origin  https://github.com/nareshdesh/charts.git (push)
rancher-helm2-charts    https://github.com/rancher/charts.git (fetch)
rancher-helm2-charts    https://github.com/rancher/charts.git (push)

```

**Comment by PennyScissors** [comment]
@nareshdesh Looks good, but if I understand correctly the idea is to switch from rancher/charts to rancher/helm3-charts so that you don't need to maintain the chart in both repositories. If that's the case, you need to add the `rancher_max_version: 2.5.6` constraint to all the other openebs charts in rancher/charts so they don't show up in the helm2 catalog in Rancher v2.5.6+.

**Comment by nareshdesh** [comment]
@PennyScissors , thank you for pointing it out. Have made the changes in all versions.
Following is the lint output post these changes 

```
docker run -v $(pwd):/rancher-helm2-charts:Z -w /rancher-helm2-charts quay.io/helmpack/chart-testing:latest ct lint --remote rancher-helm2-charts --target-branch master --validate-maintainers=false --chart
-dirs charts/openebs
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Linting charts...

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 openebs => (version: "0.6.0", path: "charts/openebs/v0.6")
 openebs => (version: "0.8.3", path: "charts/openebs/v0.8.3")
 openebs => (version: "0.9.0", path: "charts/openebs/v0.9.0")
 openebs => (version: "1.0.0", path: "charts/openebs/v1.0.0")
 openebs => (version: "1.1.0", path: "charts/openebs/v1.1.0")
 openebs => (version: "1.10.0", path: "charts/openebs/v1.10.0")
 openebs => (version: "1.11.0", path: "charts/openebs/v1.11.0")
 openebs => (version: "1.12.0", path: "charts/openebs/v1.12.0")
 openebs => (version: "1.2.0", path: "charts/openebs/v1.2.0")
 openebs => (version: "1.3.0", path: "charts/openebs/v1.3.0")
 openebs => (version: "1.4.0", path: "charts/openebs/v1.4.0")
 openebs => (version: "1.5.0", path: "charts/openebs/v1.5.0")
 openebs => (version: "1.6.0", path: "charts/openebs/v1.6.0")
 openebs => (version: "1.7.0", path: "charts/openebs/v1.7.0")
 openebs => (version: "1.8.0", path: "charts/openebs/v1.8.0")
 openebs => (version: "1.9.0", path: "charts/openebs/v1.9.0")
 openebs => (version: "2.0.0", path: "charts/openebs/v2.0.0")
 openebs => (version: "2.1.0", path: "charts/openebs/v2.1.0")
 openebs => (version: "2.2.0", path: "charts/openebs/v2.2.0")
 openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")
------------------------------------------------------------------------------------------------------------------------

Linting chart 'openebs => (version: "0.6.0", path: "charts/openebs/v0.6")'
Checking chart 'openebs => (version: "0.6.0", path: "charts/openebs/v0.6")' for a version bump...
Old chart version: 0.6.0
New chart version: 0.6.0
Linting chart 'openebs => (version: "0.8.3", path: "charts/openebs/v0.8.3")'
Checking chart 'openebs => (version: "0.8.3", path: "charts/openebs/v0.8.3")' for a version bump...
Old chart version: 0.8.3
New chart version: 0.8.3
Linting chart 'openebs => (version: "0.9.0", path: "charts/openebs/v0.9.0")'
Checking chart 'openebs => (version: "0.9.0", path: "charts/openebs/v0.9.0")' for a version bump...
Old chart version: 0.9.0
New chart version: 0.9.0
Linting chart 'openebs => (version: "1.0.0", path: "charts/openebs/v1.0.0")'
Checking chart 'openebs => (version: "1.0.0", path: "charts/openebs/v1.0.0")' for a version bump...
Old chart version: 1.0.0

New chart version: 1.0.0                                                                                                                                                                                                            [26/1992]
Linting chart 'openebs => (version: "1.1.0", path: "charts/openebs/v1.1.0")'
Checking chart 'openebs => (version: "1.1.0", path: "charts/openebs/v1.1.0")' for a version bump...
Old chart version: 1.1.0
New chart version: 1.1.0
Linting chart 'openebs => (version: "1.10.0", path: "charts/openebs/v1.10.0")'
Checking chart 'openebs => (version: "1.10.0", path: "charts/openebs/v1.10.0")' for a version bump...
Old chart version: 1.10.0
New chart version: 1.10.0
Linting chart 'openebs => (version: "1.11.0", path: "charts/openebs/v1.11.0")'
Checking chart 'openebs => (version: "1.11.0", path: "charts/openebs/v1.11.0")' for a version bump...
Old chart version: 1.11.0
New chart version: 1.11.0
Linting chart 'openebs => (version: "1.12.0", path: "charts/openebs/v1.12.0")'
Checking chart 'openebs => (version: "1.12.0", path: "charts/openebs/v1.12.0")' for a version bump...
Old chart version: 1.12.0
New chart version: 1.12.0
Linting chart 'openebs => (version: "1.2.0", path: "charts/openebs/v1.2.0")'
Checking chart 'openebs => (version: "1.2.0", path: "charts/openebs/v1.2.0")' for a version bump...
Old chart version: 1.2.0
New chart version: 1.2.0
Linting chart 'openebs => (version: "1.3.0", path: "charts/openebs/v1.3.0")'
Checking chart 'openebs => (version: "1.3.0", path: "charts/openebs/v1.3.0")' for a version bump...
Old chart version: 1.3.0
New chart version: 1.3.0
Linting chart 'openebs => (version: "1.4.0", path: "charts/openebs/v1.4.0")'
Checking chart 'openebs => (version: "1.4.0", path: "charts/openebs/v1.4.0")' for a version bump...
Old chart version: 1.4.0
New chart version: 1.4.0
Linting chart 'openebs => (version: "1.5.0", path: "charts/openebs/v1.5.0")'
Checking chart 'openebs => (version: "1.5.0", path: "charts/openebs/v1.5.0")' for a version bump...
Old chart version: 1.5.0
New chart version: 1.5.0
Linting chart 'openebs => (version: "1.6.0", path: "charts/openebs/v1.6.0")'
Checking chart 'openebs => (version: "1.6.0", path: "charts/openebs/v1.6.0")' for a version bump...
Old chart version: 1.6.0
New chart version: 1.6.0
Linting chart 'openebs => (version: "1.7.0", path: "charts/openebs/v1.7.0")'
Checking chart 'openebs => (version: "1.7.0", path: "charts/openebs/v1.7.0")' for a version bump...
Old chart version: 1.7.0
New chart version: 1.7.0
Linting chart 'openebs => (version: "1.8.0", path: "charts/openebs/v1.8.0")'
Checking chart 'openebs => (version: "1.8.0", path: "charts/openebs/v1.8.0")' for a version bump...
Old chart version: 1.8.0
New chart version: 1.8.0
Linting chart 'openebs => (version: "1.9.0", path: "charts/openebs/v1.9.0")'
Checking chart 'openebs => (version: "1.9.0", path: "charts/openebs/v1.9.0")' for a version bump...
Old chart version: 1.9.0
New chart version: 1.9.0
Linting chart 'openebs => (version: "2.0.0", path: "charts/openebs/v2.0.0")'
Checking chart 'openebs => (version: "2.0.0", path: "charts/openebs/v2.0.0")' for a version bump...
Old chart version: 2.0.0
New chart version: 2.0.0
Linting chart 'openebs => (version: "2.1.0", path: "charts/openebs/v2.1.0")'
Checking chart 'openebs => (version: "2.1.0", path: "charts/openebs/v2.1.0")' for a version bump...
Old chart version: 2.1.0
New chart version: 2.1.0
Linting chart 'openebs => (version: "2.2.0", path: "charts/openebs/v2.2.0")'
Checking chart 'openebs => (version: "2.2.0", path: "charts/openebs/v2.2.0")' for a version bump...
Old chart version: 2.2.0
New chart version: 2.2.0
Linting chart 'openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")'
Checking chart 'openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")' for a version bump...
Unable to find chart on master. New chart detected.
Validating /rancher-helm2-charts/charts/openebs/v2.5.0/Chart.yaml...
Validation success! 👍
==> Linting charts/openebs/v2.5.0



1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✖︎ openebs => (version: "0.6.0", path: "charts/openebs/v0.6") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "0.8.3", path: "charts/openebs/v0.8.3") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "0.9.0", path: "charts/openebs/v0.9.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.0.0", path: "charts/openebs/v1.0.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.1.0", path: "charts/openebs/v1.1.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.10.0", path: "charts/openebs/v1.10.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.11.0", path: "charts/openebs/v1.11.0") > Chart version not ok. Needs a version bump!
 ✖︎ opene     bs => (version: "1.12.0", path: "charts/openebs/v1.12.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.2.0", path: "charts/openebs/v1.2.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.3.0", path: "charts/openebs/v1.3.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.4.0", path: "charts/openebs/v1.4.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.5.0", path: "charts/openebs/v1.5.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.6.0", path: "charts/openebs/v1.6.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.7.0", path: "charts/openebs/v1.7.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.8.0", path: "charts/openebs/v1.8.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.9.0", path: "charts/openebs/v1.9.0") > Chart version not ok. Needs a versio     n bump!
 ✖︎ openebs => (version: "2.0.0", path: "charts/openebs/v2.0.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "2.1.0", path: "charts/openebs/v2.1.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "2.2.0", path: "charts/openebs/v2.2.0") > Chart version not ok. Needs a version bump!
 ✔︎ openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")
------------------------------------------------------------------------------------------------------------------------
Error linting charts: Error processing charts
Error: Error linting charts: Error processing charts

```
Is the above linting error for other versions, besides 2.5.0 is expected?

**Comment by nareshdesh** [comment]
@PennyScissors, can you please review this PR and approve it , if all looks good

**Comment by PennyScissors** [comment]
Hello @nareshdesh, could you please update the cutoff version from 2.5.6 to 2.5.7 since there was a recent emergency release? I'll make sure to review/approve as soon as you make the change to avoid having to do it again for the upcoming release. I apologize for the delay.

As for the lint errors, that's expected. It's complaining about changing the chart without bumping the version, but we don't want to bump it because the we are just hiding those charts and not introducing any potentially breaking changes.

**Comment by nareshdesh** [comment]
@PennyScissors 
Updated the version to 2.5.7  and ran the lint again. Can you check and approve it.  Thank you

```
 docker run -v $(pwd):/rancher-helm2-charts:Z -w /rancher-helm2-charts quay.io/helmpack/chart-testing:latest ct lint --remote
rancher-helm2-charts --target-branch master --validate-maintainers=false --chart-dirs charts/openebs
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Linting charts...

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:                                                                                                                            [90/1951]
------------------------------------------------------------------------------------------------------------------------
 openebs => (version: "0.6.0", path: "charts/openebs/v0.6")
 openebs => (version: "0.8.3", path: "charts/openebs/v0.8.3")
 openebs => (version: "0.9.0", path: "charts/openebs/v0.9.0")
 openebs => (version: "1.0.0", path: "charts/openebs/v1.0.0")
 openebs => (version: "1.1.0", path: "charts/openebs/v1.1.0")
 openebs => (version: "1.10.0", path: "charts/openebs/v1.10.0")
 openebs => (version: "1.11.0", path: "charts/openebs/v1.11.0")
 openebs => (version: "1.12.0", path: "charts/openebs/v1.12.0")
 openebs => (version: "1.2.0", path: "charts/openebs/v1.2.0")
 openebs => (version: "1.3.0", path: "charts/openebs/v1.3.0")
 openebs => (version: "1.4.0", path: "charts/openebs/v1.4.0")
 openebs => (version: "1.5.0", path: "charts/openebs/v1.5.0")
 openebs => (version: "1.6.0", path: "charts/openebs/v1.6.0")
 openebs => (version: "1.7.0", path: "charts/openebs/v1.7.0")
 openebs => (version: "1.8.0", path: "charts/openebs/v1.8.0")
 openebs => (version: "1.9.0", path: "charts/openebs/v1.9.0")
 openebs => (version: "2.0.0", path: "charts/openebs/v2.0.0")
 openebs => (version: "2.1.0", path: "charts/openebs/v2.1.0")
 openebs => (version: "2.2.0", path: "charts/openebs/v2.2.0")
 openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")
------------------------------------------------------------------------------------------------------------------------

Linting chart 'openebs => (version: "0.6.0", path: "charts/openebs/v0.6")'
Checking chart 'openebs => (version: "0.6.0", path: "charts/openebs/v0.6")' for a version bump...
Old chart version: 0.6.0
New chart version: 0.6.0
Linting chart 'openebs => (version: "0.8.3", path: "charts/openebs/v0.8.3")'
Checking chart 'openebs => (version: "0.8.3", path: "charts/openebs/v0.8.3")' for a version bump...
Old chart version: 0.8.3
New chart version: 0.8.3
Linting chart 'openebs => (version: "0.9.0", path: "charts/openebs/v0.9.0")'
Checking chart 'openebs => (version: "0.9.0", path: "charts/openebs/v0.9.0")' for a version bump...
Old chart version: 0.9.0
New chart version: 0.9.0
Linting chart 'openebs => (version: "1.0.0", path: "charts/openebs/v1.0.0")'
Checking chart 'openebs => (version: "1.0.0", path: "charts/openebs/v1.0.0")' for a version bump...
Old chart version: 1.0.0
New chart version: 1.0.0
Linting chart 'openebs => (version: "1.1.0", path: "charts/openebs/v1.1.0")'
Checking chart 'openebs => (version: "1.1.0", path: "charts/openebs/v1.1.0")' for a version bump...
Old chart version: 1.1.0
New chart version: 1.10.0                                                                                                                           [43/1951]
Linting chart 'openebs => (version: "1.11.0", path: "charts/openebs/v1.11.0")'
Checking chart 'openebs => (version: "1.11.0", path: "charts/openebs/v1.11.0")' for a version bump...
Old chart version: 1.11.0
New chart version: 1.11.0
Linting chart 'openebs => (version: "1.12.0", path: "charts/openebs/v1.12.0")'
Checking chart 'openebs => (version: "1.12.0", path: "charts/openebs/v1.12.0")' for a version bump...
Old chart version: 1.12.0
New chart version: 1.12.0
Linting chart 'openebs => (version: "1.2.0", path: "charts/openebs/v1.2.0")'
Checking chart 'openebs => (version: "1.2.0", path: "charts/openebs/v1.2.0")' for a version bump...
Old chart version: 1.2.0
New chart version: 1.2.0
Linting chart 'openebs => (version: "1.3.0", path: "charts/openebs/v1.3.0")'
Checking chart 'openebs => (version: "1.3.0", path: "charts/openebs/v1.3.0")' for a version bump...
Old chart version: 1.3.0
New chart version: 1.3.0
Linting chart 'openebs => (version: "1.4.0", path: "charts/openebs/v1.4.0")'
Checking chart 'openebs => (version: "1.4.0", path: "charts/openebs/v1.4.0")' for a version bump...
Old chart version: 1.4.0
New chart version: 1.4.0
Linting chart 'openebs => (version: "1.5.0", path: "charts/openebs/v1.5.0")'
Checking chart 'openebs => (version: "1.5.0", path: "charts/openebs/v1.5.0")' for a version bump...
Old chart version: 1.5.0
New chart version: 1.5.0
Linting chart 'openebs => (version: "1.6.0", path: "charts/openebs/v1.6.0")'
Checking chart 'openebs => (version: "1.6.0", path: "charts/openebs/v1.6.0")' for a version bump...
Old chart version: 1.6.0
New chart version: 1.6.0
Linting chart 'openebs => (version: "1.7.0", path: "charts/openebs/v1.7.0")'
Checking chart 'openebs => (version: "1.7.0", path: "charts/openebs/v1.7.0")' for a version bump...
Old chart version: 1.7.0
New chart version: 1.7.0
Linting chart 'openebs => (version: "1.8.0", path: "charts/openebs/v1.8.0")'
Checking chart 'openebs => (version: "1.8.0", path: "charts/openebs/v1.8.0")' for a version bump...
Old chart version: 1.8.0
New chart version: 1.8.0
Linting chart 'openebs => (version: "1.9.0", path: "charts/openebs/v1.9.0")'
Checking chart 'openebs => (version: "1.9.0", path: "charts/openebs/v1.9.0")' for a version bump...
Old chart version: 1.9.0
New chart version: 1.9.0
Linting chart 'openebs => (version: "2.0.0", path: "charts/openebs/v2.0.0")'
Checking chart 'openebs => (version: "2.0.0", path: "charts/openebs/v2.0.0")' for a version bump...
Old chart version: 2.0.0
New chart version: 2.0.0
Linting chart 'openebs => (version: "2.1.0", path: "charts/openebs/v2.1.0")'
Checking chart 'openebs => (version: "2.1.0", path: "charts/openebs/v2.1.0")' for a version bump...
Old chart version: 2.1.0
New chart version: 2.1.0
Linting chart 'openebs => (version: "2.2.0", path: "charts/openebs/v2.2.0")'
Checking chart 'openebs => (version: "2.2.0", path: "charts/openebs/v2.2.0")' for a version bump...
Old chart version: 2.2.0
New chart version: 2.2.0
Linting chart 'openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")'
Checking chart 'openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")' for a version bump...
Unable to find chart on master. New chart detected.
Validating /rancher-helm2-charts/charts/openebs/v2.5.0/Chart.yaml...
Validation success! 👍
==> Linting charts/openebs/v2.5.0

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✖︎ openebs => (version: "0.6.0", path: "charts/openebs/v0.6") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "0.8.3", path: "charts/openebs/v0.8.3") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "0.9.0", path: "charts/openebs/v0.9.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.0.0", path: "charts/openebs/v1.0.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.1.0", path: "charts/openebs/v1.1.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.10.0", path: "charts/openebs/v1.10.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.11.0", path: "charts/openebs/v1.11.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.12.0", path: "charts/openebs/v1.12.0") > Chart version n     ot ok. Needs a version bump!
 ✖︎ openebs => (version: "1.2.0", path: "charts/openebs/v1.2.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.3.0", path: "charts/openebs/v1.3.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.4.0", path: "charts/openebs/v1.4.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.5.0", path: "charts/openebs/v1.5.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.6.0", path: "charts/openebs/v1.6.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.7.0", path: "charts/openebs/v1.7.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.8.0", path: "charts/openebs/v1.8.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "1.9.0", path: "charts/openebs/v1.9.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "2.0.0", path: "charts/openebs/v2.0.0     ") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "2.1.0", path: "charts/openebs/v2.1.0") > Chart version not ok. Needs a version bump!
 ✖︎ openebs => (version: "2.2.0", path: "charts/openebs/v2.2.0") > Chart version not ok. Needs a version bump!
 ✔︎ openebs => (version: "2.5.1", path: "charts/openebs/v2.5.0")
------------------------------------------------------------------------------------------------------------------------
Error linting charts: Error processing charts
Error: Error linting charts: Error processing charts

```

**Review by PennyScissors — APPROVED** [review]

**Pull request merged**
