### PR TITLE
Bump Epinio to 1.6.1 (2.7 dev)

### PR DESCRIPTION
**Pull request by andreas-kupries**
Ref https://github.com/epinio/epinio/issues/2036

Requires image-mirror PR.

References to update when this is merged:

 - https://github.com/epinio/epinio/issues/2051
 - https://github.com/rancher/rancher/issues/40338

### CODE REVIEW

**Comment by thehejik** [comment]
### QA report
#### Testing environment
Rancher `v2.7.2-rc2` on top of a single-node `v1.25.5+k3s2` cluster with incorporated traefik lb. Helm chart git repository for Epinio Rancher App installation https://github.com/epinio/charts.git and branch `epinio-1.6.1`

#### Tested
* Adding the custom repository for this PR
* Installation of `Epinio  (101.0.3+up1.6.1)` App helm chart in Rancher (local k3s cluster) by using default values (+entered base epinio domain) - `epinio` and `epinio-crd` apps were successfully deployed in `cattle-epinio-system` namespace
* All the input boxed for values were ok (**Ingress class for the server and for apps were added**)
* **No k8s API Deprecation messages present in the helm install log**
* All the relevant resources like pods are in `Ready` state
* Accessed `epinio-ui` over ingress, login by using default credentials
* Created epinio `workspace` namespace for its applications
* Deployment of sample-app phpinfo() app stored in local folder
* Accessing the sample-app over provided URL in epinio-ui
* All resources still ok
* Images and tags from https://github.com/rancher/image-mirror/pull/338 match with the deployed ones
* KNOWN skopeo is missing due to image format incompatability
* KNOWN export the application over epinio 1.6.1 CLI - user will get only values.yaml, it doesn't return chart neither image ref. https://github.com/epinio/epinio/issues/1965
* Uninstallation (`epinio` and then `epinio-crd`) ok

App export is still not working but the rest is working as expected. Also there is a way to disable DEX (via Edit YAML only)  and AWS/S3 access key values are not mandatory when S3 is enabled.

**Review by thehejik — APPROVED** [review]

**Comment by olblak** [comment]
@andreas-kupries Apparently they are some file conflict, could you have a look?

**Review by thehejik — CHANGES_REQUESTED** [review]
values.yaml should point to `rancher/mirrored-skopeo-skopeo:v1.10.0`

**Comment by andreas-kupries** [comment]
Fixed issue with skopeo image. Used bad version tag (needed `v1.10.0`, not `v1.10`). This hopefully fixes the issues reported by QA.

**Comment by andreas-kupries** [comment]
@olblak Conflict resolved, the head of the branch reformatted the release.yaml a bit. Fix done as part of the skopeo image fix.

**Review by thehejik — DISMISSED** [review]
The chart is working ok, only known issue is the export part. (It doesn't reach that point for pulling skopeo when exporting but the v1.10.0 image exists).

**Review by thehejik — APPROVED** [review]
Retested with the latest PSP related commits.

### QA report
#### Testing environment
Rancher `v2.7.2-rc1` on top of a single-node `v1.25.6+k3s1` cluster with incorporated traefik lb. Helm chart git repository for Epinio Rancher App installation https://github.com/epinio/charts.git and branch `epinio-1.6.1`

#### Tested
* Adding the custom repository for this PR
* new description for 1.25+ about PSP in the chart info makes sense
* PSP disabled by default in questions (via a new section)
* If I enable PSP via the new PSP question the helm installation fail on 1.25 with following log message: 
```Error: execution error at (epinio/templates/validate-psp-install.yaml:4:5): The target cluster does not have the PodSecurityPolicy API resource. Please disable PSPs in this chart before proceeding.```
* Seems that PSP requirements are met
* Installation of `Epinio (102.0.0+up1.6.1)` App helm chart in Rancher (local k3s cluster) by using default values (+entered base epinio domain) - `epinio` and `epinio-crd` apps were successfully deployed in `cattle-epinio-system` namespace
* All the input boxed for values were ok (Ingress class for the server and for apps were added)
* No k8s API Deprecation messages present in the helm install log
* All the relevant resources like pods are in `Ready` state
* Accessed `epinio-ui` over ingress, login by using default credentials
* Created epinio `workspace` namespace for its applications
* Deployment of sample-app phpinfo() app stored in local folder
* Accessing the sample-app over provided URL in epinio-ui
* All resources still ok
* SKIPPED  (done in previous round) Images and tags check from https://github.com/rancher/image-mirror/pull/338 match with the deployed ones
* It is using correct rancher/mirrored-skopeo-skopeo:v1.10.0 (values.yaml)
* KNOWN (will be fixed in 1.6.2) export the application over epinio 1.6.1 CLI - user will get only values.yaml, it doesn't return chart neither image ref. https://github.com/epinio/epinio/issues/1965
* Uninstallation (`epinio` and then `epinio-crd`) ok

image

App export is still not working but the rest is working as expected. Also there is a way to disable DEX (via Edit YAML only)  and AWS/S3 access key values are not mandatory when S3 is enabled.

**Review by olblak — APPROVED** [review]

**Pull request merged**
