### PR TITLE
[v2.9] remove psp related hull tests and bump helm to v3.14.1

### PR DESCRIPTION
**Pull request by vardhaman22**
## Issue 

bumping helm to latest v3.14.1 version for tests

## Problem

 since helm v3.14.1 uses k8s libraries 0.29.x and psps are completely removed from those libraries,

## Solution

1.  psp related hull test cases are removed.
2.  coverage check is disabled since coverage will not be 100% after psp related test cases are removed.

### CODE REVIEW

**Comment by recena** [comment]
@vardhaman22 Instead of using the convention of `[WIP]` in the PR title, use the GH Draft feature. In this way, reviewers will receive the notifications when the PR is ready to be reviewed.

**Comment by adamkpickering** [comment]
@vardhaman22 what is the status of this PR? Still WIP?

**Comment by vardhaman22** [comment]
> @vardhaman22 what is the status of this PR? Still WIP?

@adamkpickering i faced an issue while trying to bump helm to v3.14.1 and raised a [PR](https://github.com/rancher/hull/pull/43) to fix it in hull. so we will not be able to merge this till that gets fixed. I have updated the PR description.

**Comment by vardhaman22** [comment]
hi @adamkpickering @recena since I am not sure who is going to review the hull PR for the fix, it used to be eliyam but he has left the org.. not sure who is maintaining hull repo now. So I have created a [PR](https://github.com/rancher/charts/pull/3516) to disable the hull tests, so that we can bump helm here for now.

**Comment by recena** [comment]
@vardhaman22 

> So I have created a https://github.com/rancher/charts/pull/3516 to disable the hull tests, so that we can bump helm here for now.

Why do you need to disable the test to upgrade Helm?

**Comment by vardhaman22** [comment]
> @vardhaman22
> 
> > So I have created a #3516 to disable the hull tests, so that we can bump helm here for now.
> 
> Why do you need to disable the test to upgrade Helm?

@recena  because of the helm upgrade there is an issue in parsing templates in hull. so that needs to be fixed in hull first and then only the tests will start passing. I have explained the issue in detail in [hull PR](https://github.com/rancher/hull/pull/43)

**Comment by recena** [comment]
I assume this PR is blocked by https://github.com/rancher/hull/pull/43, right?

**Comment by vardhaman22** [comment]
> I assume this PR is blocked by [rancher/hull#43](https://github.com/rancher/hull/pull/43), right?

yes

**Comment by adamkpickering** [comment]
@vardhaman22 https://github.com/rancher/hull/pull/43 is merged now. That unblocks this, right?

**Comment by vardhaman22** [comment]
> @vardhaman22 [rancher/hull#43](https://github.com/rancher/hull/pull/43) is merged now. That unblocks this, right?

yes @adamkpickering i have updated the description of the PR and also rebased it. The CI for hull tests also passed so now it is ready for review.

**Review by nicholasSUSE — APPROVED** [review]
LGTM

**Review by adamkpickering — APPROVED** [review]

**Review by chiukapoor — APPROVED** [review]

**Pull request merged**
