### PR TITLE
[dev-v2.7] Add Istio 1.16.3

### PR DESCRIPTION
**Pull request by rohitsakala**
This PR adds Istio 1.16.3 version along with latest Kiali server and Jaeger tracing versions.

Related issue: https://github.com/rancher/rancher/issues/40959

Depends on: https://github.com/rancher/image-mirror/pull/364 and https://github.com/rancher/istio-installer/pull/63

Adds:
```
kiali-server:v1.63.2
jaeger-tracing:v1.42.0
istio:102.1.0+up1.16.3 (contains distroless images)
```

### CODE REVIEW

**Comment by rohitsakala** [comment]
Installation and Uninstallation in AKS with 3 nodes.

Screenshot 2023-04-12 at 1 14 15 PM

Screenshot 2023-04-12 at 1 15 30 PM

**Review by mitulshah-suse — APPROVED** [review]
Please wait for review from @prachidamle as well, before merging this

**Comment by prachidamle** [comment]
@rohitsakala Can we also test upgrade case from istio 1.15.x version to these newer versions works?

**Comment by rohitsakala** [comment]
Testing upgrade from 1.15 to 1.16 

Screenshot 2023-04-14 at 9 17 29 AM

**Review by prachidamle — APPROVED** [review]

**Pull request merged**
