### PR TITLE
Adding fluentd and fluentbit monitoring into helm template

### PR DESCRIPTION
**Pull request by rpenugonda**
can we have something like this so that it has hooks into installing monitoring metrics

### CODE REVIEW

**Comment by aiyengar2** [comment]
@rpenugonda we don't directly merge fixes to release-v2.6. Please make the PR to dev-v2.6 by modifying the appropriate `Package`; please see https://github.com/rancher/charts/blob/dev-v2.6/packages/README.md#common-workflow for more information on how to contribute!

**Comment by tjanson** [comment]
This still seems very desirable to me -- being able to enable the service monitor for metrics if desired should definitely be an option, right? Would you accept this change if the PR were cleaned up? (@aiyengar2 @Jono-SUSE-Rancher ?)

**Comment by recena** [comment]
Closing since `2.5.x` is not supported.

**Comment by tjanson** [comment]
Just for the record, this same issue still applies to the current latest `dev-v2.9`: https://github.com/rancher/charts/blob/baf95653c8649e7f4ba7e112c5ba32b423fd26c0/charts/rancher-logging/104.0.0%2Bup3.17.10/templates/loggings/root/logging.yaml

**Pull request closed without merging**
