### PR TITLE
Bump gke-operator to 1.1.1-rc7

### PR DESCRIPTION
**Pull request by cmurphy**
https://github.com/rancher/rancher/issues/33406

### CODE REVIEW

**Review by thedadams — CHANGES_REQUESTED** [review]
The `charts/rancher-gke-operator{-crd}/rancher-gke-operator{-crd}/100.0.0+up1.1.1-rc6` directories should also be deleted.

**Comment by cmurphy** [comment]
@thedadams done

**Review by thedadams — DISMISSED** [review]

**Review by cbron — APPROVED** [review]

**Comment by cmurphy** [comment]
had to rebase

**Review by cbron — APPROVED** [review]
lgtm, wait for one more review

**Review by thedadams — APPROVED** [review]

**Pull request merged**
