### PR TITLE
Update storageos-operator to version 0.2.13

### PR DESCRIPTION
**Pull request by darkowlzz**

### CODE REVIEW

**Comment by darkowlzz** [comment]
There's nothing new in this version, it's the same as 0.2.12. It's needed to keep the storageos charts repo and rancher charts repo in sync.

**Comment by guangbochen** [comment]
you can update the `0.2.12`'s app version and folder name to `0.2.13` since the `0.2.12` version is only merged into `dev` and can be changed.

**Comment by darkowlzz** [comment]
Thanks. I've renamed the dir and the app version.

**Comment by guangbochen** [comment]
LGTM and merged.

**Pull request merged**
