### PR TITLE
[HOLD] Update after fix rancher/charts-build-scripts#22

### PR DESCRIPTION
**Pull request by jcaamano**
After fix rancher/charts-build-scripts#22, some charts require updates:

* Many `Chart.yaml.patch` which only purpose was to revert changes done
  charts-build-scripts are no longer needed and are removed.
* Set rancher-istio/charts/requirements.yaml to lexicographical map key
  order as generated by charts-build-scripts.
* Update package versions as required.

### CODE REVIEW

**Review by brendarearden — APPROVED** [review]
Looks good! It is fine to bump istio!

**Comment by aiyengar2** [comment]
FYI, once approvals are in, I will be cherry-picking these commits in a separate PR that will upgrade the charts-build-script version along with making these changes.

When I do so, I will close out this PR.

**Review by aiyengar2 — APPROVED** [review]
LGTM, tested out the changes based on the new stuff brought in by rancher/charts-build-scripts#22 and it works fine. Thanks @jcaamano !

**Review by cbron — COMMENTED** [review]
Seems fine, but sounds like we are cherry-picking commits to do official release/PR

**Comment by jcaamano** [comment]
> Seems fine, but sounds like we are cherry-picking commits to do official release/PR

I guess that I could add the version bump within in this PR, is that what you mean?

**Comment by cbron** [comment]
I mean are we merging this PR or is Arvind cherry-picking commits from this PR to different one.

**Comment by aiyengar2** [comment]
@cbron I'll cherry-pick. Don't want to bug @jcaamano every time the source branch goes out of date when other devs merge in changes, and I'm also running integration tests on it to make sure we don't break anything

**Comment by aiyengar2** [comment]
Closing this in favor of https://github.com/rancher/charts/pull/1045

**Pull request closed without merging**
