### PR TITLE
[release-v2.6] OOB release for vSphere CPI and CSI

### PR DESCRIPTION
**Pull request by PennyScissors**
Issue: https://github.com/rancher/rancher/issues/35378

**Additions in this PR are coming from checkouts directly from the `dev-v2.6-vsphere-release` branch, not `dev-v2.6`.**

New charts to be released OOB in 2.6:
_CPI_ 100.1.0+up1.0.100
**CSI** 100.0.1+up2.1.1
**CSI** 100.1.0+up2.3.0

Charts to be hidden in 2.6 as we no longer want users to use them:
_CPI_ 100.0.0
**CSI** 100.0.0

New 2.5 charts that were forward ported to 2.6 (hidden in 2.6):
_CPI_ 1.0.1
**CSI** 2.1.1

Previously released charts that were modified in 2.5 and changes were forwardported to 2.6:
_CPI_ 1.0.000
_CPI_ 1.0.100
**CSI** 2.1.000
**CSI** 2.3.0

### CODE REVIEW

**Comment by PennyScissors** [comment]
### Chart dir diffs between the branches `dev-v2.5-vsphere-release` and `dev-v2.6-vsphere-release`

CPI
```
# No diffs found
➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.000 dev-v2.6-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.000

# No diffs found
➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.1 dev-v2.6-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.1

# No diffs found
➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.100 dev-v2.6-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.100
```

CSI
```
# No diffs found
➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.1.000 dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.1.000

# No diffs found
➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.1.1 dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.1.1

# No diffs found
➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.3.0 dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.3.0
```

### Chart dir diffs between 2.5 charts and their 2.6 variant

CPI
```
# This results in a large diff so I omitted it, but it's expected because 1.0.000 and 100.0.0 were initially the same chart, but they diverged when a fix to support RKE2 was implemented in 100.0.0.

➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.000 dev-v2.6-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.0.0


=======================================
# This diff is expected. The appVersion was changed back to 1.0.1 here, but not in the 2.5 chart because the 2.5 chart has already been released.

➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.100 dev-v2.6-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.1.0+up1.0.100
diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.100/Chart.yaml dev-v2.6-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.1.0+up1.0.100/Chart.yaml
--- dev-v2.5-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.100/Chart.yaml  2021-11-18 15:34:09.000000000 -0800
+++ dev-v2.6-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.1.0+up1.0.100/Chart.yaml        2021-11-18 15:30:32.000000000 -0800
@@ -1,12 +1,12 @@
 annotations:
-  catalog.cattle.io/rancher-version: '>= 2.5.0-0 <= 2.5.99-0'
   catalog.cattle.io/certified: rancher
   catalog.cattle.io/display-name: vSphere CPI
   catalog.cattle.io/namespace: kube-system
   catalog.cattle.io/os: linux
+  catalog.cattle.io/rancher-version: '>= 2.6.0-0 <= 2.6.99-0'
   catalog.cattle.io/release-name: vsphere-cpi
 apiVersion: v1
-appVersion: 1.21.0
+appVersion: 1.0.1
 description: vSphere Cloud Provider Interface (CPI)
 icon: https://charts.rancher.io/assets/logos/vsphere-cpi.svg
 keywords:
@@ -18,4 +18,4 @@
 name: rancher-vsphere-cpi
 sources:
 - https://github.com/kubernetes/cloud-provider-vsphere
-version: 1.0.100
+version: 100.1.0+up1.0.100
diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.100/app-readme.md dev-v2.6-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.1.0+up1.0.100/app-readme.md
--- dev-v2.5-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/1.0.100/app-readme.md       2021-11-18 15:34:09.000000000 -0800
+++ dev-v2.6-vsphere-release/charts/rancher-vsphere-cpi/rancher-vsphere-cpi/100.1.0+up1.0.100/app-readme.md     2021-11-18 15:30:32.000000000 -0800
@@ -2,14 +2,6 @@
 
 [vSphere Cloud Provider Interface (CPI)](https://github.com/kubernetes/cloud-provider-vsphere) is responsible for running all the platform specific control loops that were previously run in core Kubernetes components like the KCM and the kubelet, but have been moved out-of-tree to allow cloud and infrastructure providers to implement integrations that can be developed, built and released independent of Kubernetes core. The official documentation and tutorials can be found [here](https://vsphere-csi-driver.sigs.k8s.io/driver-deployment/prerequisites.html).
 
-## Support Matrix
-
-| Rancher vSphere CPI | Minimum Kubernetes Release | Maximum Kubernetes Release |
-| ------------------- | -------------------------- | -------------------------- |
-| 1.0.100             | 1.18.x                     | 1.21.x                     |
-| 1.0.1               |                            | 1.17.x                     |
-| 1.0.000             |                            | 1.17.x                     |
-
 ## Prerequisites
 
 - vSphere 6.7 U3+
```

CSI
```
# This results in a large diff so I omitted it, but it's expected because 2.1.000 and 100.0.0 were initially the same chart, but they diverged when a fix to support RKE2 was implemented in 100.0.0.

➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.1.000/Chart.yaml dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.0.0/Chart.yaml


=======================================
# This diff is expected.

➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.1.1 dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.0.1+up2.1.1
diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.1.1/Chart.yaml dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.0.1+up2.1.1/Chart.yaml
--- dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.1.1/Chart.yaml    2021-11-18 15:34:09.000000000 -0800
+++ dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.0.1+up2.1.1/Chart.yaml  2021-11-18 15:34:24.000000000 -0800
@@ -3,7 +3,7 @@
   catalog.cattle.io/display-name: vSphere CSI
   catalog.cattle.io/namespace: kube-system
   catalog.cattle.io/os: linux
-  catalog.cattle.io/rancher-version: '>= 2.5.0-0 <= 2.5.99-0'
+  catalog.cattle.io/rancher-version: '>= 2.6.0-0 <= 2.6.99-0'
   catalog.cattle.io/release-name: vsphere-csi
 apiVersion: v1
 appVersion: 2.1.1
@@ -18,4 +18,4 @@
 name: rancher-vsphere-csi
 sources:
 - https://github.com/kubernetes-sigs/vsphere-csi-driver
-version: 2.1.1
+version: 100.0.1+up2.1.1
diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.1.1/app-readme.md dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.0.1+up2.1.1/app-readme.md
--- dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.1.1/app-readme.md 2021-11-18 15:34:09.000000000 -0800
+++ dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.0.1+up2.1.1/app-readme.md       2021-11-18 15:30:32.000000000 -0800
@@ -6,13 +6,6 @@
 
 The CSI driver for vSphere is `csi.vsphere.vmware.com`.
 
-## Support Matrix
-
-| Rancher vSphere CSI | Minimum Kubernetes Release | Maximum Kubernetes Release |
-| ------------------- | -------------------------- | -------------------------- |
-| 2.1.1               |                            | 1.19.x                     |
-| 2.1.000             |                            | 1.19.x                     |
-
 ## Prerequisites
 
 - vSphere 6.7 U3+


=======================================
# This diff is expected.

➜ diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.3.0 dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.1.0+up2.3.0
diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.3.0/Chart.yaml dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.1.0+up2.3.0/Chart.yaml
--- dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.3.0/Chart.yaml    2021-11-18 15:34:09.000000000 -0800
+++ dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.1.0+up2.3.0/Chart.yaml  2021-11-18 15:30:32.000000000 -0800
@@ -1,9 +1,9 @@
 annotations:
-  catalog.cattle.io/rancher-version: '>= 2.5.0-0 <= 2.5.99-0'
   catalog.cattle.io/certified: rancher
   catalog.cattle.io/display-name: vSphere CSI
   catalog.cattle.io/namespace: kube-system
   catalog.cattle.io/os: linux
+  catalog.cattle.io/rancher-version: '>= 2.6.0-0 <= 2.6.99-0'
   catalog.cattle.io/release-name: vsphere-csi
 apiVersion: v1
 appVersion: 2.3.0
@@ -18,4 +18,4 @@
 name: rancher-vsphere-csi
 sources:
 - https://github.com/kubernetes-sigs/vsphere-csi-driver
-version: 2.3.0
+version: 100.1.0+up2.3.0
diff -uNr dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.3.0/app-readme.md dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.1.0+up2.3.0/app-readme.md
--- dev-v2.5-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/2.3.0/app-readme.md 2021-11-18 15:34:09.000000000 -0800
+++ dev-v2.6-vsphere-release/charts/rancher-vsphere-csi/rancher-vsphere-csi/100.1.0+up2.3.0/app-readme.md       2021-11-18 15:30:32.000000000 -0800
@@ -6,14 +6,6 @@
 
 The CSI driver for vSphere is `csi.vsphere.vmware.com`.
 
-## Support Matrix
-
-| Rancher vSphere CSI | Minimum Kubernetes Release | Maximum Kubernetes Release |
-| ------------------- | -------------------------- | -------------------------- |
-| 2.3.0               | 1.19.x                     | 1.21.x                     |
-| 2.1.1               |                            | 1.19.x                     |
-| 2.1.000             |                            | 1.19.x                     |
-
 ## Prerequisites
 
 - vSphere 6.7 U3+
```

**Review by jiaqiluo — APPROVED** [review]
LGTM

**Comment by aiyengar2** [comment]
### Script

```bash
git fetch upstream
git fetch steven

mv assets 2.6-curr-assets
git checkout upstream/release-v2.6 -- assets
mv assets 2.6-old-assets
git checkout steven/relv25-vsphere -- assets
mv assets 2.5-new-assets

rm -rf cpi csi

for comp in cpi csi; do
    assetDir="2.6-curr-assets/rancher-vsphere-${comp}"
    destDir="${comp}/release-v2.6-new"
    for asset in $(ls ${assetDir}); do
        version=$(echo ${asset%.tgz} | cut -d'-' -f4)
        mkdir -p ${destDir}/${version}
        tar xvzf ${assetDir}/${asset} -C ${destDir}/${version} --strip-components=1
    done
done

for comp in cpi csi; do
    assetDir="2.6-old-assets/rancher-vsphere-${comp}"
    destDir="${comp}/release-v2.6-old"
    for asset in $(ls ${assetDir}); do
        version=$(echo ${asset%.tgz} | cut -d'-' -f4)
        mkdir -p ${destDir}/${version}
        tar xvzf ${assetDir}/${asset} -C ${destDir}/${version} --strip-components=1
    done
done

for comp in cpi csi; do
    assetDir="2.5-new-assets/rancher-vsphere-${comp}"
    destDir="${comp}/release-v2.5-new"
    for asset in $(ls ${assetDir}); do
        version=$(echo ${asset%.tgz} | cut -d'-' -f4)
        mkdir -p ${destDir}/${version}
        tar xvzf ${assetDir}/${asset} -C ${destDir}/${version} --strip-components=1
    done
done

# Expect no changes

diff -uNr cpi/release-v2.5-new/1.0.000 cpi/release-v2.6-new/1.0.000

diff -uNr cpi/release-v2.5-new/1.0.1 cpi/release-v2.6-new/1.0.1

diff -uNr cpi/release-v2.5-new/1.0.100 cpi/release-v2.6-new/1.0.100

# Expect some changes

# hidden
diff -uNr cpi/release-v2.6-old/100.0.0 cpi/release-v2.6-new/100.0.0

# rancher version modified, app version changed, support matrix removed
diff -uNr cpi/release-v2.6-old/1.0.100 cpi/release-v2.6-new/100.1.0+up1.0.100

# Expect chart to have rancher version < 2.6

yq e '.annotations' cpi/release-v2.6-new/100.0.0/Chart.yaml

# Check index.yaml

yq e '.entries.rancher-vsphere-cpi[] | {.version: {"annotations": .annotations, "kubeVersion": .kubeVersion}}' index.yaml

# Expect no changes

diff -uNr csi/release-v2.5-new/2.1.000 csi/release-v2.6-new/2.1.000

diff -uNr csi/release-v2.5-new/2.1.1 csi/release-v2.6-new/2.1.1

diff -uNr csi/release-v2.5-new/2.3.0 csi/release-v2.6-new/2.3.0

# Expect some changes

# hidden
diff -uNr csi/release-v2.6-old/100.0.0 csi/release-v2.6-new/100.0.0

# rancher version modified, support matrix removed
diff -uNr csi/release-v2.6-new/2.1.1 csi/release-v2.6-new/100.0.1+up2.1.1

# rancher version modified, support matrix removed
diff -uNr csi/release-v2.6-new/2.3.0 csi/release-v2.6-new/100.1.0+up2.3.0

# Expect chart to be hidden

yq e '.annotations' csi/release-v2.6-new/100.0.0/Chart.yaml

# Check index.yaml

yq e '.entries.rancher-vsphere-csi[] | {.version: {"annotations": .annotations, "kubeVersion": .kubeVersion}}' index.yaml
```

**Review by aiyengar2 — APPROVED** [review]
LGTM

**Review by cbron — APPROVED** [review]

**Pull request merged**
