### PR TITLE
Do not merge this PR.

### PR DESCRIPTION
**Pull request by rohitsakala**
This PR is for testing Github Action prime registry sync.

Start testing only after changing the credentials to Test Registry.

- [x] Dummy checkbox.

### CODE REVIEW

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
Testing branch protection

**Review by lucasmlp — APPROVED** [review]
Testing removal of regsync.yaml before committing it

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
Testing Rancher BOT credentials

**Review by lucasmlp — APPROVED** [review]
### commit credentials the same and using Rancher BOT credentials only in the push step

**Review by lucasmlp — APPROVED** [review]

**Review by lucasmlp — APPROVED** [review]
Testing rancherbot credentials on commit and push

**Review by lucasmlp — APPROVED** [review]
Testing rancherbot username

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Review by lucasmlp — APPROVED** [review]

**Review by lucasmlp — APPROVED** [review]

**Review by Hypertrophik — APPROVED** [review]

**Pull request closed without merging**
