### PR TITLE
[dev-v2.8] longhorn 103.3.0+up1.6.1 add

### PR DESCRIPTION
**Pull request by mantissahz**
Release Longhorn v1.6.1 into Rancher 2.8

Longhorn https://github.com/longhorn/longhorn/issues/8209
Rancher https://github.com/rancher/rancher/issues/44862

Signed-off-by: James Lu [james.lu@suse.com](mailto:james.lu@suse.com)

cc @innobead @PhanLe1010 @khushboo-rancher @roger-ryao

Waiting for Longhorn 1.6.1 images merged into the Rancher image-mirror list.

### CODE REVIEW

**Review by nicholasSUSE — APPROVED** [review]
Hello, we have improved the Charts documentation regarding Pull Request Rules.

Please take a look at it before making any new Pull Requests. 
We are still approving Pull Requests and starting to inform all teams, soon we will require the standard in the documentation. 
 
https://github.com/rancher/charts?tab=readme-ov-file#pull-request-rules

**Review by PhanLe1010 — COMMENTED** [review]
I have similar feedbacks as in https://github.com/rancher/charts/pull/3753#pullrequestreview-1987529863

**Comment by mantissahz** [comment]
>I have similar feedbacks as in https://github.com/rancher/charts/pull/3753#pullrequestreview-1987529863

Hi @PhanLe1010 
I have modified the PR as your feedbacks. Thanks

**Comment by roger-ryao** [comment]
Prerequisites:
- Set the Concurrent Automatic Engine Upgrade Per Node Limit to a value greater than 0.
- `LONGHORN_REPO` is set to `longhornio`.
- Rancher : `v2.8.3`

Verify is passed as follows step
- [x] Fresh installation
- [x] Uninstallation
- [x] Upgrade from `103.2.2+up1.5.4` - > `103.3.0+up1.6.1`

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by PhanLe1010** [comment]
@khushboo-rancher Because we have had significant modifications since the last test run, could we retest the PR? Once it passes, I will merge the PR

**Comment by khushboo-rancher** [comment]
Validation - Pass

Validated below cases:
1. Installation
2. uninstallation
3. upgrade
4. P0 cases of mounting volumes (Rwo, RWX), replica rebuilding

**Pull request merged**
