### PR TITLE
Add Longhorn 1.5.0 chart with dev-2.7

### PR DESCRIPTION
**Pull request by weizhe0422**
[Longhorn 6096](https://github.com/longhorn/longhorn/issues/6096)

https://github.com/rancher/rancher/issues/40489

Signed-off-by: Ray Chang [ray.chang@suse.com]

cc @innobead @PhanLe1010 @khushboo-rancher

### CODE REVIEW

**Comment by weizhe0422** [comment]
Try to install Longhorn `V1.5.0` via Rancher Apps but replace the image repository from rancher mirror: `rancher/mirrored-longhornio-` to `longhornio/, the installation is successful.
image


Still need wait QA further verification and mirror images release: https://github.com/rancher/image-mirror/pull/412.

**Comment by khushboo-rancher** [comment]
Validation - LGTM

Validated installation, upgrade (1.4.2->1.5.0) and uninstallation.
Screenshot 2023-07-07 at 1 01 28 PM

Note: I didn't enable SPDK and didn't deployed volume with v2 engine. I think that's not required for this PR testing. Let me know if additional testing is required.
cc: @innobead

**Comment by magicJie** [comment]
Looking forward to the upgrade of Longhorn-1.5 as some features are much needed!

**Comment by innobead** [comment]
@weizhe0422 As I mentioned, please close this one, because we will release 1.5.1 instead.

**Comment by weizhe0422** [comment]
Closing this PR and will having another PR for `v1.5.1` instead.

**Pull request closed without merging**
