### PR TITLE
[dev-v2.10] rancher-cis-benchmark 7.0.0-rc.1 update

### PR DESCRIPTION
**Pull request by chiukapoor**
### Updates

- rancher-cis-benchmark to `7.0.0-rc1`
- kubectl to `v1.30.5`
- cis-operator to `v1.0.16-rc.1`
- security-scan to `v0.2.18-rc.1`
- sonobuoy to `v0.57.2`
- kube-version to include k8s `v1.31`
- rancher-version to include `v2.10`
- remove cis-1.7

### Related

- https://github.com/rancher/rancher/issues/46843
- https://github.com/rancher/rancher/issues/47533

### CODE REVIEW

**Review by mitulshah-suse — APPROVED** [review]
LGTM

**Review by andypitcher — COMMENTED** [review]
@chiukapoor IMO we should get rid of the CIS-1.7 profiles (remove in README too), since it covers k8s 1.25.
We should proceed with the same approach for 2.9.

**Comment by mitulshah-suse** [comment]
@chiukapoor please raise a tracking issue for removal of older benchmarks and backports for older versions where necessary.

**Comment by chiukapoor** [comment]
> @chiukapoor please raise a tracking issue for removal of older benchmarks and backports for older versions where necessary.

- dev-v2.10: https://github.com/rancher/rancher/issues/47533
- dev-v2.9: https://github.com/rancher/rancher/issues/47534

**Review by andypitcher — APPROVED** [review]
LGTM, thanks for the update on CIS-1.7 profiles. We'll bring CIS-1.9 shortly.

**Pull request merged**
