### PR TITLE
Define a CODEOWNER file

### PR DESCRIPTION
**Pull request by recena**
This PR aims to start using `CODEOWNER` GitHub feature to simplify how we perform some engineering practices as code review.

⚠️ This PR does not affect to the core of this repository, the Helm Charts.

### CODE REVIEW

**Comment by recena** [comment]
✋ This is a DRAFT because we need to identify all owners.

**Comment by recena** [comment]
🤔 We can save some checkers if the PR only modifies certain paths.

**Review by nicholasSUSE — CHANGES_REQUESTED** [review]
The user for Nicholas is:

@nicholasSUSE

**Comment by recena** [comment]
> The user for Nicholas is:
> 
> @nicholasSUSE

@nicholasSUSE We are using the GH team for MAPPS.

**Review by rohitsakala — APPROVED** [review]

**Review by nicholasSUSE — APPROVED** [review]

**Comment by recena** [comment]
@rancher/mapps We will need to apply a similar PR against the rest of active branches (according to the branching strategy).

**Comment by cwayne18** [comment]
This has broken reviews for some charts, and should have had buyoff from the specific teams rather than just making guesses as to who owns what.

**Comment by Oats87** [comment]
cc: @mattfarina for visibility. process was seemingly not followed for this.

**Comment by recena** [comment]
> This has broken reviews for some charts, and should have had buyoff from the specific teams rather than just making guesses as to who owns what.

@cwayne18 Don't worry. GH allows to update files. If something is not 100% correct, we can fix it.

**Pull request merged**
