### PR TITLE
Release charts for v2.5.16

### PR DESCRIPTION
**Pull request by MbolotSuse**

### CODE REVIEW

**Review by rmweir — APPROVED** [review]
LGTM

**Comment by cbron** [comment]
We didn't assign a first-mate for 2.5.16 so adding some people from team-3.

**Review by cbron — COMMENTED** [review]
lgtm but let's wait for team 3.  Weird that both operator and webhook happen to be same version.

**Review by aiyengar2 — APPROVED** [review]
```
arvindiyengar: ~/Rancher/charts/src/github.com/rancher/charts 
$ ./bin/charts-build-scripts index    
INFO[0000] index.yaml is up-to-date  
```

index.yaml looks fine

---

On inspecting the diffs manually between previously released versions, everything looks fine to me. No RC versions and all images still have rancher/ in front of them.

---

LGTM

**Pull request merged**
