### PR TITLE
[dev-v2.7] Bump harvester-csi-driver to v0.1.15

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
Signed-off-by: Vicente Cheng <vicente.cheng@suse.com>

### CODE REVIEW

**Comment by eliyamlevy** [comment]
Hello @Vicente-Cheng, So the release yaml needs to be fixed (has merge conflicts) but we also need to switch the version from `v101.0.0+up0.1.15` to `v102.0.0+up0.1.15`.

**Comment by Vicente-Cheng** [comment]
hi @eliyamlevy,
Thanks for the reminder! Already updated.
Please help to recheck it. Thanks!!

**Review by eliyamlevy — APPROVED** [review]
LGTM

**Comment by Vicente-Cheng** [comment]
Hi @eliyamlevy,
I want to close this PR due to another bump PR #2450.
#2450 would fix some CVE issues. Could you help to recheck it? Thanks!

**Pull request closed without merging**
