### PR TITLE
Longhorn v1.2.4 for Cluster Manager/Catalog

### PR DESCRIPTION
**Pull request by innobead**
Signed-off-by: David Ko <dko@suse.com>

cc @khushboo-rancher @kaxing @meldafrawi @cchien816 @yangchiu

ref: https://github.com/rancher/rancher/issues/36796

### CODE REVIEW

**Review by PennyScissors — DISMISSED** [review]
LGTM except for the chart's version and image tags which I assume will be updated to non-rc versions once v1.2.4 is released.

Also, linted chart with helm's ct tool and it looks good:
```
Linting charts...
------------------------------------------------------------------------------------------------------------------------
 Configuration
------------------------------------------------------------------------------------------------------------------------
Remote: rancher-charts
TargetBranch: master
Since: HEAD
BuildId: 
LintConf: /etc/ct/lintconf.yaml
ChartYamlSchema: /etc/ct/chart_schema.yaml
ValidateMaintainers: false
ValidateChartSchema: true
ValidateYaml: true
AdditionalCommands: []
CheckVersionIncrement: true
ProcessAllCharts: false
Charts: []
ChartRepos: []
ChartDirs: [charts/longhorn]
ExcludedCharts: []
HelmExtraArgs: 
HelmRepoExtraArgs: []
Debug: false
Upgrade: false
SkipMissingValues: false
Namespace: 
ReleaseLabel: 
ExcludeDeprecated: false
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 longhorn => (version: "1.2.4-rc1", path: "charts/longhorn/latest")
 longhorn => (version: "1.2.3", path: "charts/longhorn/v1.2.3")
------------------------------------------------------------------------------------------------------------------------

Linting chart 'longhorn => (version: "1.2.4-rc1", path: "charts/longhorn/latest")'
Checking chart 'longhorn => (version: "1.2.4-rc1", path: "charts/longhorn/latest")' for a version bump...
Old chart version: 1.2.3
New chart version: 1.2.4-rc1
Chart version ok.
Validating /rancher-charts/charts/longhorn/latest/Chart.yaml...
Validation success! 👍
==> Linting charts/longhorn/latest
[WARNING] templates/psp.yaml: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

1 chart(s) linted, 0 chart(s) failed
Linting chart 'longhorn => (version: "1.2.3", path: "charts/longhorn/v1.2.3")'
Checking chart 'longhorn => (version: "1.2.3", path: "charts/longhorn/v1.2.3")' for a version bump...
Unable to find chart on master. New chart detected.
Validating /rancher-charts/charts/longhorn/v1.2.3/Chart.yaml...
Validation success! 👍
==> Linting charts/longhorn/v1.2.3
[WARNING] templates/psp.yaml: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ longhorn => (version: "1.2.4-rc1", path: "charts/longhorn/latest")
 ✔︎ longhorn => (version: "1.2.3", path: "charts/longhorn/v1.2.3")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

**Comment by khushboo-rancher** [comment]
Validated the chart v1.2.4-rc1 with repo `https://github.com/innobead/charts-1` and branch `longhorn-v1.2.4`.

Validation - Pass

Validated the installation, uninstallation, upgrade from v1.2.3->v1.2.4-rc1 and upgrade from v1.1.3->v1.2.4-rc1. Validated the basic p0 test cases as well like, RWO/RWX volume creation, data writing/reading, backup and recurring job.

**Comment by innobead** [comment]
@PennyScissors Please help review again, then merge after @khushboo-rancher verify the final update. Thank you.

**Review by PennyScissors — APPROVED** [review]
@innobead LGTM, and looks like it's ready for release. If the intention is to release this with the 2.6 chart as part of Rancher 2.6.4, we should wait until release day before merging this.

Lint results: passed
```
Linting charts...
------------------------------------------------------------------------------------------------------------------------
 Configuration
------------------------------------------------------------------------------------------------------------------------
Remote: rancher-charts
TargetBranch: master
Since: HEAD
BuildId: 
LintConf: /etc/ct/lintconf.yaml
ChartYamlSchema: /etc/ct/chart_schema.yaml
ValidateMaintainers: false
ValidateChartSchema: true
ValidateYaml: true
AdditionalCommands: []
CheckVersionIncrement: true
ProcessAllCharts: false
Charts: []
ChartRepos: []
ChartDirs: [charts/longhorn]
ExcludedCharts: []
HelmExtraArgs: 
HelmRepoExtraArgs: []
Debug: false
Upgrade: false
SkipMissingValues: false
Namespace: 
ReleaseLabel: 
ExcludeDeprecated: false
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 longhorn => (version: "1.2.4", path: "charts/longhorn/latest")
 longhorn => (version: "1.2.3", path: "charts/longhorn/v1.2.3")
------------------------------------------------------------------------------------------------------------------------

Linting chart 'longhorn => (version: "1.2.4", path: "charts/longhorn/latest")'
Checking chart 'longhorn => (version: "1.2.4", path: "charts/longhorn/latest")' for a version bump...
Old chart version: 1.2.3
New chart version: 1.2.4
Chart version ok.
Validating /rancher-charts/charts/longhorn/latest/Chart.yaml...
Validation success! 👍
==> Linting charts/longhorn/latest
[WARNING] templates/psp.yaml: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

1 chart(s) linted, 0 chart(s) failed
Linting chart 'longhorn => (version: "1.2.3", path: "charts/longhorn/v1.2.3")'
Checking chart 'longhorn => (version: "1.2.3", path: "charts/longhorn/v1.2.3")' for a version bump...
Unable to find chart on master. New chart detected.
Validating /rancher-charts/charts/longhorn/v1.2.3/Chart.yaml...
Validation success! 👍
==> Linting charts/longhorn/v1.2.3
[WARNING] templates/psp.yaml: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ longhorn => (version: "1.2.4", path: "charts/longhorn/latest")
 ✔︎ longhorn => (version: "1.2.3", path: "charts/longhorn/v1.2.3")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

**Comment by innobead** [comment]
> @innobead LGTM, and looks like it's ready for release. If the intention is to release this with the 2.6 chart as part of Rancher 2.6.4, we should wait until release day before merging this.
> 
Let's merge it until the 2.6.4 release. Thanks.

**Comment by PennyScissors** [comment]
@innobead Converting this to a draft to prevent accidental merges while we wait until release day. This chart is validated and ready to release so we can convert it back to a PR and merge once we are ready to release Rancher.

**Pull request merged**
