### PR TITLE
 Update storageos-operator to version 0.2.16

### PR DESCRIPTION
**Pull request by darkowlzz**

### CODE REVIEW

**Comment by croomes** [comment]
LGTM (StorageOS reviewer)

Lint fail is for unrelated chart.

**Comment by guangbochen** [comment]
This is LGTM, and @darkowlzz Can you please check out from the master branch and cherry-pick those two commits that you have added, thanks.

**Comment by guangbochen** [comment]
Update the base branch to master.

**Comment by darkowlzz** [comment]
Thanks, updated.

**Comment by guangbochen** [comment]
LGTM.

**Pull request merged**
