### PR TITLE
Updated questions.yml to fix rancher/rancher#23534

### PR DESCRIPTION
**Pull request by ChandanSagar**
- This change will fix https://github.com/rancher/rancher/issues/23534

Signed-off-by: ChandanSagar <chandan.pradhan@mayadata.io>

### CODE REVIEW

**Comment by ChandanSagar** [comment]
@guangbochen : Can you please take a look?

**Comment by guangbochen** [comment]
@ChandanSagar it is required to add a new version if a version bump is involved, but since you only changing the `questions.yml` here so I will help you to merge it without version bump, thanks.

**Comment by ChandanSagar** [comment]
@guangbochen Should I remove the version bump?

**Comment by guangbochen** [comment]
LGTM, since this PR only fixes typo in `questions.yml` so we can ignore the version bump failure from the CI.

**Comment by ChandanSagar** [comment]
@guangbochen Can we have this PR merged?

**Comment by guangbochen** [comment]
@deniseschannon can u PTAL and merge it, thanks.

**Comment by guangbochen** [comment]
@ChandanSagar can u please help to `rebase` the commits to latest master to resolve merge conflicts, thanks!

**Comment by ChandanSagar** [comment]
@guangbochen PTAL.

**Comment by guangbochen** [comment]
LGTM, thanks. @deniseschannon

**Pull request merged**
