### PR TITLE
[dev-v2.7.11] Bump harvester-cloud-provider 0.2.3

### PR DESCRIPTION
**Pull request by w13915984028**
## Problem

Bump harvester-cloud-provider to v0.2.3, add support of k8s v1.27

## Solution

https://github.com/rancher/rancher/issues/44121

### CODE REVIEW

**Review by lucasmlp — APPROVED** [review]
LGTM 🚀

**Comment by w13915984028** [comment]
FYI: When run `make validate` upon `dev-v2.7.11` branch directly, it simply failed. It blocks any new PR.

```
INFO[0177] Generated chart: charts/neuvector-crd/102.0.7+up2.7.1 
ERRO[0178] The following new assets have been introduced: map[] 
ERRO[0178] The following released assets have been removed: map[neuvector:[102.0.7+up2.7.1] neuvector-crd:[102.0.7+up2.7.1]] 
ERRO[0178] The following released assets have been modified: map[] 
ERRO[0178] If this was intentional, to allow validation to pass, these charts must be added to the release.yaml. 
INFO[0178] Dumping release.yaml tracking changes that have been introduced 
INFO[0178] Updating index.yaml                          
INFO[0179] Generated index.yaml                         
FATA[0179] Validation against upstream repository https://github.com/rancher/charts.git at branch release-v2.7 failed. 
make: *** [Makefile:17: validate] Error 1


/go/src/github.com/w13915984028/rancher-charts$ git log -1
commit 68ae6daf263c632bba6f8706ec6282995be96685 (HEAD -> dev-v2.7.11, origin/dev-v2.7.11)
Author: Tom Lebreux <tom.lebreux@suse.com>
Date:   Mon Feb 5 13:58:23 2024 -0500

    [v2.7.11] rancher-webhook k8s 1.27 support for 2.7.11 (#3411)
```

**Comment by lucasmlp** [comment]
@w13915984028  `make validate` fails due to OOB PRs being merged yesterday. I haven't finished the post-release work yet. It's taking more time than expected because we don't have a process in place to update branches created from the release branch i.e.: dev-v2.7.11
I expect to fix this today.

**Comment by w13915984028** [comment]
@lucasmlp Thanks very much !

**Pull request merged**
