### PR TITLE
Update storageos-operator to version 0.2.10

### PR DESCRIPTION
**Pull request by darkowlzz**

### CODE REVIEW

**Comment by guangbochen** [comment]
in order to help this PR get merged, please help to update with:
1. add a backup version of `1.2.0` in a separated folder(1 commit)
2. add the latest version `1.3.0` to a new folder(2 commits, 1, base copy 1.2.0 to 1.3.0  2, Update changes) - you can reference the folder structure from the other charts.
3. get people from `storageos` to sign-off as this is a partner maintained chart @croomes  
```
Signed-off-by: yourname you-org-email@com
```
Thanks.

**Comment by darkowlzz** [comment]
Hi,
Thanks for the instructions.
I've created a backup version of chart `0.2.0` and a new version `0.2.10` separately with separate incremental change commits, and signed off the commits with org email address.
Hope it's ready to be accepted now.

**Comment by croomes** [comment]
LGTM - thanks!

**Comment by guangbochen** [comment]
LGTM

**Pull request merged**
