### PR TITLE
[rancher-monitoring] Fix chart dependency links in app-README.md

### PR DESCRIPTION
**Pull request by bashofmann**
## Problem
The app-README references the old, deprecated helm/charts repository for chart dependencies like Grafana, kube-state-metrics, node-exporter, etc., even though these are not used by rancher-monitoring anymore.

## Solution
Fix chart dependency links in app-README.md to the ones that are actually used.

## Testing
README change only.

### CODE REVIEW

**Review by geethub97 — APPROVED** [review]

**Review by geethub97 — CHANGES_REQUESTED** [review]
the CI is failing, will take a look

**Comment by stormqueen1990** [comment]
It looks like this PR is missing the `make charts` commit.

**Comment by bashofmann** [comment]
Yes, I specifically did not run it, because I did not want to modify an already existing released version and I also did not want to create a new version just for a readme change. Or was this wrong?

**Comment by stormqueen1990** [comment]
> Yes, I specifically did not run it, because I did not want to modify an already existing released version and I also did not want to create a new version just for a readme change. Or was this wrong?

Hi @bashofmann 👋

Our `make validate` script relies on the assets generated by `make charts`, so I don't think we can make our CI pass without running `make charts`. It feels to me like this is OK to be a change to the current chart version.

@geethub97 how do you feel about updating the current version?

**Comment by stormqueen1990** [comment]
Just one update: I saw this PR is targeting `dev-v2.7` and the latest version of the rancher-monitoring chart in this branch is yet to be released.

**Comment by bashofmann** [comment]
Ah great. I just ran `make charts` then.

**Review by geethub97 — APPROVED** [review]

**Pull request merged**
