### PR TITLE
[v2.7] Add K8s v1.27 support in CIS-Benchmark

### PR DESCRIPTION
**Pull request by rayandas**
Related: https://github.com/rancher/rancher/issues/41787

### CODE REVIEW

**Comment by JonCrowther** [comment]
I think there is an issue with the branching of the charts? None of the 4.2.0-rc's made it to the 2.8 dev branch. This means we don't have any of the cis-benchmark 1.7 work.

**Comment by JonCrowther** [comment]
I was mistaken. The RC's do not carry over. Once the benchmark 1.7 changes are finalized in dev-2.7 I will create a new rc for dev-2.8 that contains those changes. In the mean time this change can go forward.

**Comment by rayandas** [comment]
Yeah. This is just to add 1.27 support.

**Review by JonCrowther — DISMISSED** [review]

**Comment by rayandas** [comment]
Fixed the conflict. @JonCrowther Could you please approve it again?

**Review by JonCrowther — DISMISSED** [review]

**Review by doflamingo721 — APPROVED** [review]

**Comment by rayandas** [comment]
Resolved conflicts. Merging it as it was approved by @JonCrowther twice.

**Pull request merged**
