### PR TITLE
Rancher helm charts for new CIC version v1.8.19, with updated CRD structure

### PR DESCRIPTION
**Pull request by tkonduri**

### CODE REVIEW

**Comment by tkonduri** [comment]
@PennyScissors Can you please review this PR? Thanks.

**Comment by guangbochen** [comment]
@tkonduri can u please help to rearrange this PR into 2 commits, 1st one to base the new version folder from the previous one without any changes and 2nd commit to adding those updates, thanks.

**Comment by tkonduri** [comment]
Hi @guangbochen, I have updated the PR with two commits as per your request. Please review and let me know if it looks fine? Thanks.

**Comment by guangbochen** [comment]
@tkonduri can u rebase the PR to master as current PR contains lots of unexpected commits, thanks.

**Pull request closed without merging**
