### PR TITLE
Bump rancher-gke-operator to 1.1.4

### PR DESCRIPTION
**Pull request by macedogm**
Bump executed to refresh base image and update its packages. No modifications were done to the chart itself.

### CODE REVIEW

**Comment by macedogm** [comment]
@annablender can you please review this PR again?

**Comment by annablender** [comment]
Pending question to @kinarashah about whether tagging a release version vs an rc is correct

**Review by annablender — CHANGES_REQUESTED** [review]
The base image change here is not a functional change, so it makes more sense to tag an rc instead of a release version. Tag `1.1.4-rc1`

**Comment by macedogm** [comment]
The bump was done https://github.com/rancher/charts/pull/1965.

**Pull request closed without merging**
