### PR TITLE
[dev-v2.9] Complete epinio removal

### PR DESCRIPTION
**Pull request by lucasmlp**
## Problem
Epinio will no longer be supported by SUSE and needs to be removed from the Rancher Marketplace and Apps.

## Solution

- Use `make remove` command to remove each `epinio` and `epinio-crd` chart version.
- Add the removed version to `release.yaml`
- Make separate commits for each version being removed.
- Remove epinio package folder in `packages/`

### CODE REVIEW

**Comment by recena** [comment]
@lucasmlp Don't forget to update `CODEOWNERS` file.

**Review by nicholasSUSE — CHANGES_REQUESTED** [review]
This CODEOWNERS file contains errors

**Review by andreas-kupries — APPROVED** [review]
The epinio removal looks good. including the CODEOWNERS. The error reported for the file looks to be unrelated, and was likely present before the changes from this PR.

**Comment by lucasmlp** [comment]
@nicholasSUSE 
> This CODEOWNERS file contains errors

Fixed in [rancher/charts#3666](https://github.com/rancher/charts/pull/3666) and rebased this PR.

**Review by nicholasSUSE — APPROVED** [review]

**Comment by troytop** [comment]
Maintenance and support for [Epinio](https://epinio.io/) is now provided by [Krumware](https://www.krum.io/). Epinio is still available from the [upstream Helm repo](https://epinio.github.io/helm-charts/).

**Pull request merged**
