### PR TITLE
Fleet v0.3.6 rc2

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
@StrongMonkey can you delete the older charts/ and assets/ (and entry in the index.yaml) as part of this change? Bumping an RC should show up as a just renaming files + a one line change to the version.

Easiest way to do this would be to delete [charts|assets]/[fleet|fleet-agent|fleet-crd]/* and the index.yaml and re-run `make validate` twice, committing in between. Then run `make validate` one more time to ensure that your PR is good to go.

**Comment by StrongMonkey** [comment]
@aiyengar2 Pushed and cleaned.

**Review by aiyengar2 — APPROVED** [review]
LGTM; thanks for cleaning!

**Comment by StrongMonkey** [comment]
@aiyengar2 Can you review this again? Rebased with the latest change.

**Review by jiaqiluo — APPROVED** [review]
LGTM

**Review by aiyengar2 — APPROVED** [review]

**Comment by StrongMonkey** [comment]
https://github.com/rancher/fleet/issues/395
https://github.com/rancher/rancher/issues/33163
https://github.com/rancher/rancher/issues/33131

**Pull request merged**
