### PR TITLE
Update rio version to be 0.8.000

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
Per darren's request updating chart version to 0.8.000 to match the actual app version.

**Review by cbron — DISMISSED** [review]
lgtm, after my pr is merged you can just rebase and it will pass CI

**Comment by StrongMonkey** [comment]
Close in favor of https://github.com/rancher/charts/pull/559

**Comment by mrajashree** [comment]
Closing as per @StrongMonkey [comment](https://github.com/rancher/charts/pull/542#issuecomment-675701145)

**Pull request closed without merging**
