### PR TITLE
[dev-v2.8] longhorn 1.7.2 add

### PR DESCRIPTION
**Pull request by mantissahz**
Release Longhorn v1.7.2 into Rancher 2.8

Longhorn https://github.com/longhorn/longhorn/issues/9603
Rancher https://github.com/rancher/rancher/issues/47739

cc @innobead @derekbit @rebeccazzzz @PhanLe1010 @khushboo-rancher @roger-ryao

### CODE REVIEW

**Comment by yangchiu** [comment]
Verification passed on rancher `v2.8.5`:
- [x] Fresh installation
- [x] Uninstallation
- [x] Upgrade from `103.3.2+up1.6.3` -> `103.4.1+up1.7.2`
- [x] Upgrade from `103.4.0+up1.7.1` -> `103.4.1+up1.7.2`

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by PhanLe1010** [comment]
@yangchiu Could you please also the chart is working ok on Rancher Prime with Rancher Prime image registry? We want to verify that it is working with Prime registry image by default. Ref https://github.com/rancher/charts/pull/4544#issuecomment-2412755469

PR has been merged so we can use `dev-v*` branch for testing

**Comment by yangchiu** [comment]
Verification passed on rancher prime `v2.8.9`:
- [x] Fresh installation
- [x] Uninstallation

**Pull request merged**
