### PR TITLE
Update rancher resource set

### PR DESCRIPTION
**Pull request by mrajashree**
- [x]  Exclude helm secrets

- [x]  Include rancher-operator

- [x]  Include fleet

https://github.com/rancher/backup-restore-operator/issues/30

Kinds and KindsRegexp fields can accept both the actual Kind (singular camelcase) or resource (plural)

### CODE REVIEW

**Comment by StrongMonkey** [comment]
Also need to add https://github.com/rancher/charts/tree/dev-v2.5/charts/rancher-webhook

**Comment by mrajashree** [comment]
@StrongMonkey added it in

**Review by StrongMonkey — DISMISSED** [review]

**Review by cbron — APPROVED** [review]

**Comment by mrajashree** [comment]
@StrongMonkey @cbron I squashed the commits and force-pushed and that dismissed the reviews

**Review by StrongMonkey — APPROVED** [review]

**Review by cbron — APPROVED** [review]

**Comment by cbron** [comment]
If you have time you could do version swap now, otherwise need to do in another PR.

**Pull request merged**
