### PR TITLE
Fix2505 v2.8 rancher-monitoring-crd installation issue

### PR DESCRIPTION
**Pull request by w13915984028**
## Issue: 

https://github.com/rancher/rancher/issues/43418

This new PR is to replace the origin PR https://github.com/rancher/charts/pull/2715.

## Problem

The rancher-monitoring-crd jobs uses kubectl replace -Rf /etc/crd || kubectl create -Rf /etc/crd;, but the RBAC has only verbs: ['create', 'get', 'patch', 'delete']

## Solution

Add update to RBAC

### Manual Testing

Install rancher-monitoring-crd `` in bootstrap stage (e.g. in Harvester), the prometheuses.monitoring.coreos.com` CRD is not correctly installed, and the error message is observed in both
https://github.com/rancher/rancher/issues/43418
and
https://github.com/harvester/harvester/issues/3969
and more

## Backporting considerations

Please note, at least 102.0.0+up40.1.2 and 102.0.1+up40.1.2 are affected, more releases need to be checked by the owner, thanks.

The origin PR is https://github.com/rancher/charts/pull/2715, but it took too long to review, and now we need to rebase on dev-v2.8 branch.

### CODE REVIEW

**Review by joshmeranda — CHANGES_REQUESTED** [review]
LGTM nust need conflicts to be addressed

**Comment by strowi** [comment]
please LGTM, still a problem with rancher-monitoring-crd-103.0.3+up45.31.1

**Comment by nicholasSUSE** [comment]
Hello @w13915984028 @joshmeranda 
Is this Pull Request still relevant?
Can I close it?

**Comment by joshmeranda** [comment]
Yes, we got these changes merged in another PR I can go through and close those out.

**Comment by joshmeranda** [comment]
@nicholasSUSE this is deprecated by https://github.com/rancher/charts/pull/3318. We can close

**Comment by abinet** [comment]
Hi guys, are you going to backport this somehow into 2.8?

**Pull request closed without merging**
