### PR TITLE
[rancher-monitoring] Fix deployment error when installing rancher-monitoring without grafana

### PR DESCRIPTION
**Pull request by bashofmann**
Fixes https://github.com/rancher/rancher/issues/39090

### CODE REVIEW

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
No new chart is being generated, you need to remove `doNotRelease` from the `package.yaml` and follow this commit up with a `make charts` commit to generate the new chart, update the assets, and update the index.yaml with that command.

**Comment by bashofmann** [comment]
Done.

I was not sure, if the `doNotRelease` flag was in there for a reason and there shouldn't be any chart releases in the 2.7 branch yet.

Is it correct to keep the `doNotRelease: true` flag in the `package.yaml` after the generation, or should I also remove it?

**Comment by bashofmann** [comment]
I don't understand what to do with the `release.yaml` to make the build run through:

The build fails, I run `make validate` locally, which changes the `release.yaml` to:

```
rancher-monitoring:
- 101.0.0+up19.0.3
rancher-monitoring-crd:
- 101.0.0+up19.0.3
```

Then I push this change, the release fails again, I run `make validate` locally again, which changes the `release.yaml` back to: 

```
rancher-aks-operator:
- 100.0.6+up1.0.7-rc1
rancher-aks-operator-crd:
- 100.0.6+up1.0.7-rc1
rancher-backup:
- 2.1.4-rc1
rancher-backup-crd:
- 2.1.4-rc1
rancher-cis-benchmark:
- 3.0.0-rc1
rancher-cis-benchmark-crd:
- 3.0.0-rc1
rancher-csp-adapter:
- 1.0.1
rancher-eks-operator:
- 100.0.4+up1.1.5-rc1
rancher-eks-operator-crd:
- 100.0.4+up1.1.5-rc1
rancher-webhook:
- 1.0.6+up0.2.7-rc4
```

**Comment by bashofmann** [comment]
I changed the file now manually to:

```
rancher-aks-operator:
- 100.0.6+up1.0.7-rc1
rancher-aks-operator-crd:
- 100.0.6+up1.0.7-rc1
rancher-backup:
- 2.1.4-rc1
rancher-backup-crd:
- 2.1.4-rc1
rancher-cis-benchmark:
- 3.0.0-rc1
rancher-cis-benchmark-crd:
- 3.0.0-rc1
rancher-csp-adapter:
- 1.0.1
rancher-eks-operator:
- 100.0.4+up1.1.5-rc1
rancher-eks-operator-crd:
- 100.0.4+up1.1.5-rc1
rancher-monitoring:
- 101.0.0+up19.0.3
rancher-monitoring-crd:
- 101.0.0+up19.0.3
rancher-webhook:
- 1.0.6+up0.2.7-rc4
```

and the build runs through.

But I have no idea if I'm using and understand the 'release.yaml' and validation logic correctly.

**Comment by hetii** [comment]
Hello.
When I can expect to merge this PR?
Do I need to wait then for new chart version or the existing one are going to be hotfixed without new version?

**Comment by aiyengar2** [comment]
@hetii thanks for the ping. Targeting this for 2.7.0 in https://github.com/rancher/rancher/issues/39090#issuecomment-1255541197

**Comment by aiyengar2** [comment]
Closing in favor of a cherry-pick in https://github.com/rancher/charts/pull/2109.

Thank you for your contribution @bashofmann!

**Comment by aiyengar2** [comment]
merged @hetii, it will be tested and released in `100.1.0` in Rancher `2.7.0`

**Pull request closed without merging**
