### PR TITLE
stable(openebs): update v2.2.0 release version 

### PR DESCRIPTION
**Pull request by prateekpandey14**
- Updated README
- Updated questions.yaml to point the NDM images instead of defaults to `quay.io`
- Updated values.yaml

### CODE REVIEW

**Comment by prateekpandey14** [comment]
@PennyScissors Can you please help merge ? Thanks!

**Comment by prateekpandey14** [comment]
@PennyScissors  need help to get this merge , Thanks!

**Comment by PennyScissors** [comment]
Could you please separate this into two commits in the following way to make it easier to review?
1st commit: Copy the directory of the older version of the chart (v2.1.0) and name it after the new version (V2.2.0)
2nd commit: Changes made to the older version to update it.

You have two commits, but the first commit seems to include modifications on multiple older versions of the chart rather than just copying the latest.

**Comment by prateekpandey14** [comment]
@PennyScissors do you want me to add an extra commit for the older version changes

**Comment by prateekpandey14** [comment]
@PennyScissors PTAL.

**Comment by PennyScissors** [comment]
@prateekpandey14 Thanks for splitting the commits, I'll get this reviewed asap.

**Pull request closed without merging**
