### PR TITLE
[rancher-logging] Update dependency for k8s 1.26

### PR DESCRIPTION
**Pull request by dbason**
## Testing
Testing has been completed as described in the linked issue

## Backporting considerations
N/A

@sanjay920 @MKlimuszka

### CODE REVIEW

**Review by diogoasouza — CHANGES_REQUESTED** [review]
Couple of things:

- The versioning for rancher 2.7 is 102.x.x, not 103, you should probably just change the patch version here
- Since you're adding a new version, you have to add an entry to the releases.yaml file with it

**Review by diogoasouza — APPROVED** [review]
lgtm

**Comment by dbason** [comment]
@diogosouza I don't have write permission to this repo so could you merge it for me?

**Comment by aridclown** [comment]
@dbason wrong Diogo 😄 

Nice to meet you, xará @diogoasouza 👋

**Comment by diogoasouza** [comment]
@dbason sure thing
@diogosouza ty! Nice to meet you 👋

**Pull request merged**
