### PR TITLE
[dev-v2.7] [v2.7.x-Q3] Add hull tests to CI

### PR DESCRIPTION
**Pull request by doflamingo721**
Added hull tests for feature charts as part of CI.

Linked issue: https://github.com/rancher/rancher/issues/41687

### CODE REVIEW

**Review by rohitsakala — APPROVED** [review]

**Comment by prachidamle** [comment]
@doflamingo721 Is there any Hull CI output to demo that the tests can catch chart issues?

Would be good to show examples of any output showing success and failure as part of CI

**Comment by doflamingo721** [comment]
@prachidamle  Attaching the screenshot to demo CI output in case hull tests fail or if there's missing coverage.
image

For refer the logs [here](https://github.com/rancher/charts/actions/runs/5108576488/jobs/9182517071) for more details related to hull & CI failure.

**Review by eliyamlevy — APPROVED** [review]
LGTM, My only comment is that this runs _**EVERY**_ hull test. We might want to look into maybe only running on the most recent change to the release yaml or something on that line to optimize the pr workflow addition.

**Comment by doflamingo721** [comment]
@eliyamlevy Merging this PR. We can track optimising the CI in a different ticket.

**Pull request merged**
