### PR TITLE
Add Longhorn 1.3.3 chart with dev-2.7

### PR DESCRIPTION
**Pull request by weizhe0422**
[Longhorn 5581](https://github.com/longhorn/longhorn/issues/5581)

Signed-off-by: Ray Chang [ray.chang@suse.com]

Tests
 - v1.24.11 +rke2r1 @Rancher 2.7.2 
   截圖 2023-04-21 上午11 34 02

cc @innobead @PhanLe1010 @khushboo-rancher

### CODE REVIEW

**Review by rohitsakala — APPROVED** [review]

**Comment by innobead** [comment]
@rohitsakala We should have QA sign off before merging this PR.

cc @khushboo-rancher

**Comment by rohitsakala** [comment]
> @rohitsakala We should have QA sign off before merging this PR.
> 
> cc @khushboo-rancher

Ohh..I saw `Tests` section in the description and assumed tests passed. My bad.

**Comment by khushboo-rancher** [comment]
The Functionality is working fine, but there is a UI issue. CSI Liveness image name and tag are not placed at right place as shown in attached screenshot.

Screenshot 2023-04-21 at 4 29 41 PM
Screenshot 2023-04-21 at 4 33 27 PM

The CSI Liveness probe tag in under `Longhorn CSI driver Images` section whereas the name is under `Longhorn CSI Liveness probe image` section.

**Expectation:**
There shouldn't be additional section for Longhorn CSI liveness probe, it should appear in the section `Longhorn CSI Driver images`

cc: @innobead

**Comment by innobead** [comment]
@khushboo-rancher let's create an issue at upstream about questions.yaml issue.

@rohitsakala The original test was made by @weizhe0422 who is the PR contributor, so before this PR merge, we should need you(rancher chart), Longhorn reviewer and QA review to ensure all good to prevent any surprises happening.

**Review by PhanLe1010 — COMMENTED** [review]
LGTM.

Sorry for the late response

**Comment by rohitsakala** [comment]
@innobead Should I revert this PR ?

**Comment by PhanLe1010** [comment]
I think no need to revert @rohitsakala The PR looks good to Longhorn reviewer and it passed Longhorn QA

But like @innobead said, we should wait for the Longhorn reviewer, Longhorn QA, and Rancher reviewer (yourself) to confirm before merging. Many thanks for helping!

**Comment by rohitsakala** [comment]
Gotcha. Noted from next time.

**Pull request merged**
