### PR TITLE
[dev-v2.10] longhorn 1.6.3 add

### PR DESCRIPTION
**Pull request by mantissahz**
Release Longhorn v1.6.3 into Rancher 2.10

Longhorn https://github.com/longhorn/longhorn/issues/9433

cc @innobead @derekbit @rebeccazzzz @PhanLe1010 @khushboo-rancher @roger-ryao

### CODE REVIEW

**Comment by khushboo-rancher** [comment]
@roger-ryao Could you please help test this?

**Comment by roger-ryao** [comment]
> @roger-ryao Could you please help test this?

Verify is passed as follows step
- [x] Fresh installation `105.0.0+up1.6.3`
- [X] Deploy workloads with volume
- [x] Scale down/up workload
- [x] Trigger replica rebuilding
- [x] Uninstallation

**Review by PhanLe1010 — COMMENTED** [review]
@mantissahz Can we remove:
* ./packages/longhorn/longhorn/longhorn-1.5
* ./packages/longhorn-crd/longhorn-1.5

Because we are not going release new Longhorn v1.5.x version. Ref https://github.com/longhorn/longhorn?tab=readme-ov-file#releases

**Comment by PhanLe1010** [comment]
> > @roger-ryao Could you please help test this?
> 
> Verify is passed as follows step
> 
> * [x]  Fresh installation `105.0.0+up1.6.3`
> * [x]  Deploy workloads with volume
> * [x]  Scale down/up workload
> * [x]  Trigger replica rebuilding
> * [x]  Uninstallation

Can you help to verify Rancher Prime with default Prime registry @roger-ryao ?

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by mantissahz** [comment]
>Can we remove:
>- ./packages/longhorn/longhorn/longhorn-1.5
>- ./packages/longhorn-crd/longhorn-1.5

Hi @PhanLe1010, packages/longhorn/longhorn*/longhorn-1.5 are removed.

**Pull request merged**
