### PR TITLE
Adding permits-os annotations to Longhorn charts

### PR DESCRIPTION
**Pull request by phillipsj**
This adds the permits-os annotations.

* https://github.com/rancher/rancher/issues/36401
* https://github.com/rancher/dashboard/issues/5137

### CODE REVIEW

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
where were the changes made to allow Longhorn to be deployed onto a Windows cluster? I don't see nodeSelectors or tolerations

**Comment by innobead** [comment]
Please refer to the previous discussion, https://github.com/rancher/charts/pull/1144#discussion_r622620753. 

If allowing Longhorn display on the mixed cluster, users need to set up node selector/tolerations by themselves, so probably this will cause some confusion because actually Longhorn only works for Linux.

cc @shuo-wu @khushboo-rancher @kaxing

**Comment by innobead** [comment]
BTW, one question: will `catalog.cattle.io/os` be deprecated?

**Comment by phillipsj** [comment]
Replaced by https://github.com/rancher/charts/pull/1783

**Pull request closed without merging**
