### PR TITLE
Remove disfunctional versions of rancher-operator

### PR DESCRIPTION
**Pull request by thedadams**
Issue:
https://github.com/rancher/rancher/issues/31954

### CODE REVIEW

**Review by cbron — APPROVED** [review]
Looks right to me, we aren't removing 0.2.0-alpha01-rc01 from crd dir in either index.yaml or asset.

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
@thedadams is your goal here to rewrite `rancher-operator-crd-0.2.0-alpha01-rc01` or do you just want to release a `rancher-operator-crd-0.2.0-alpha02-rc00`? If you aren't trying to overwrite the version, you should use the release-asset script instead.

Reasoning behind using the script is to avoid losing the rcVersion, in case we ever want to refer to it in the future.

e.g. see the description in https://github.com/rancher/charts/pull/1075#issue-608481186.

**Comment by thedadams** [comment]
@aiyengar2 There are a couple things I am trying to accomplish with this:
1. Remove the release that has a messed up version (rancher-operator-0.2.0-alpha0201-rc01.tgz). I don't really care to replace it, but it doesn't need to be there.
2. There is a rancher-operator-crd in the rancher-operator directory. This needs to go because it is causing issues.

I also have another PR to get a new version of rancher-operator(-crd) so QA can continue testing: https://github.com/rancher/charts/pull/1089

If I am going about this the wrong way and I should use the script to accomplish these things, please just let me know.

**Review by aiyengar2 — APPROVED** [review]
LGTM, make sure we do this in dev-v2.5 as well to keep them in sync.

**Pull request merged**
