### PR TITLE
Epinio 1.9.0 integration

### PR DESCRIPTION
**Pull request by andreas-kupries**
Updated integrated Epinio chart to release 1.9.0.

See https://github.com/epinio/epinio/issues/2464

Depends on https://github.com/rancher/image-mirror/pull/423 getting merged before testing is possible.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
The supporting PR https://github.com/rancher/image-mirror/pull/423 is merged.
It should be possible to test this PR now.

**Review by thehejik — APPROVED** [review]
## QA report
#### Testing setup:
* git repo: `https://github.com/epinio/charts.git` branch `epinio-1.9.0-integration`
* Installation of Epinio `102.0.4+up1.9.0` in Rancher `v2.7.5`  with Kubernetes version `v1.26.6+k3s1`.

#### Main checks:
* App helm chart in Rancher (local k3s cluster) by using default values (+entered base epinio domain) - epinio and epinio-crd apps were successfully deployed in cattle-epinio-system namespace
* All the input boxed for values were ok (Ingress class for the server, dex and for apps were added)
* No k8s API Deprecation messages present in the helm install log
* All the relevant resources like pods are in Ready state
* Accessed epinio-ui over ingress, login by using default credentials
* Login by using local Auth Provider over DEX

#### Specific checks once Epinio is deployed on MinIO as default storage:
* Created epinio workspace namespace for its applications
* Accessing the sample-app over provided URL in epinio-ui
* Deployment of sample-app phpinfo() app stored in local folder
* Bind of mysql-dev service to app
* Deployment of gitlab application both UI and CLI
* Checked export app images using UI and working fine. (no trace of manifest-undefined file)
* All resources still ok

#### Other checks:
* Tested as well deployment of Epinio with s3gw, application installation, simple app push and uninstall
* Upgrade of the release Epinio `102.0.3+up1.8.1` to `102.0.4+up1.9.0` with working app
* Uninstallation (epinio and then epinio-crd)

**Comment by andreas-kupries** [comment]
@olblak Over to you for final assessment and merge

**Comment by olblak** [comment]
It seems like we are deleting all the old Epinio version, is it on purpose? 
What about the previous Rancher release?

**Comment by andreas-kupries** [comment]
Yes, I removed it on purpose. Last time we left some older versions around we got asked by the Rancher people why we left them in.

**Review by olblak — APPROVED** [review]

**Pull request merged**
