### PR TITLE
Bump rancher-cis-benchmark:v2.0.3-rc1

### PR DESCRIPTION
**Pull request by dhruvmewada15**
This PR is for updating rancher cis-benchmark chart to v2.0.3.

Updates include:
- `rancher/security-scan` version bump to v0.2.6-rc1 which includes changes for AKS CIS Scan config
- `rancher/cis-operator` version bump to v1.0.7-rc1 which includes changes to update base image as SLE BCI

Linked Issue:
rancher/rancher#35844
rancher/rancher#35706

Depends on:
rancher/security-scan#66

### CODE REVIEW

**Comment by prachidamle** [comment]
I wonder if we need to update the field  catalog.cattle.io/rancher-version: '>= 2.6.0-0' 
 in https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-cis-benchmark/2.0.2/Chart.yaml#L9
 with this new version. @aiyengar2 do the new charts scripts take care of updating this or do we need to manually update?

**Comment by prachidamle** [comment]
> I wonder if we need to update the field catalog.cattle.io/rancher-version: '>= 2.6.0-0' in https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-cis-benchmark/2.0.2/Chart.yaml#L9 with this new version. @aiyengar2 do the new charts scripts take care of updating this or do we need to manually update?


Had a offline discussion with @aiyengar2 about this field - this field should be updated only if this chart cannot be installed and used with older versions of Rancher. 
So @dhruvmewada15 Please can we run a test to check this chart can work with Rancher v2.6.0 and the AKS scan profile can work? If there are no limitations to use this chart with Rancher v2.6.0 and  the Kubernetes versions available with 2.6.0, then we dont have to update this field.

**Comment by dhruvmewada15** [comment]
@prachidamle So we should check this with Rancher v2.5.x  as catalog.cattle.io/rancher-version is >=2.6.0?

**Comment by dhruvmewada15** [comment]
@prachidamle I have updated the PR with updated image [tag](https://github.com/rancher/charts/blob/3adecad254a9d45506f60a8cdb9a1adac6aac56d/charts/rancher-cis-benchmark/2.0.3-rc1/values.yaml#:~:text=tag%3A%20v1.0.7%2Drc1%2Damd64) for `rancher/cis-operator:v1.0.7-rc1-amd64` as image tag for `rancher/cis-operator:v1.0.7-rc1` is not yet pused to docker hub.

**Comment by prachidamle** [comment]
Seems the new tag rancher/cis-operator:v1.0.7-rc1 is not getting pushed to dockerhub, there is an error in the drone manifest step _ I will try recreating the tag to see if that helps

**Review by prachidamle — APPROVED** [review]

**Pull request merged**
