### PR TITLE
Traefik : add HostPort, NodePort ports selection, DaemonSet

### PR DESCRIPTION
**Pull request by w3blogfr**
Let the possibility for users to input http and https port instead to have random ports

### CODE REVIEW

**Comment by NotoriousRebel** [comment]
How breaking would it be to attempt to use traefik v2 with this chart?

**Comment by w3blogfr** [comment]
I think it will be better to use this new one and to recreate the questions.yml
https://github.com/containous/traefik-helm-chart

**Comment by PennyScissors** [comment]
Hello @NotoriousRebel @w3blogfr, I'm working on cleaning up this repository, and noticed we lost track of this PR. Should I go ahead and close this, or is it still relevant? You can always submit a new one if you like.

**Comment by w3blogfr** [comment]
This current pull request fix some issue using Traefik v1.7 and align rancher questions with helm questions.
I think it could be interesting to merge it now at least to have have a Traefik v1 working well with rancher. It does need extra effort, it's  already done.

About have a chart for Traefik v2, I suggested  to copy the official helm chart proposed by Traefik team 
https://github.com/containous/traefik-helm-chart
Then to add  questions.yml in order to create our version 2 of Traefik. 

Unfortunatly, I didn't do it yet this upgrade yet because for now I'm still using Traefik 1.7 on my personal projet. I can't give you a date and I will migrate or not.

But again, let's focus to make this v1.7 working well and have the possibility to select the ports or have it as daemon on each node (like a nginx controller)

**Comment by recena** [comment]
Closing since **traefik** is not part of rancher/charts anymore.

**Pull request closed without merging**
