### PR TITLE
Add experimental tag to opa gatekeeper

### PR DESCRIPTION
**Pull request by PennyScissors**

### CODE REVIEW

**Comment by PennyScissors** [comment]
@cbron Do I need to manually remove the tgz in branch `dev-v2.5`? Not sure if we are deleting those automatically already.

**Review by cbron — APPROVED** [review]
Tgz's get removed automatically now, this is all that should be needed. If there is an issue associated with this can you link it.

**Comment by PennyScissors** [comment]
@cbron There is no issue for this that I know.

**Comment by PennyScissors** [comment]
Rebased to solve conflicts.

**Review by cbron — APPROVED** [review]

**Pull request merged**
