### PR TITLE
[2.5.11] Backport fix merge logging

### PR DESCRIPTION
**Pull request by a-blender**
Backport [#34720](https://github.com/rancher/rancher/issues/34720) into 2.5.11. According to @paynejacob, kubeAudit changes will not be added until rancher-logging chart 3.14 so I left those out. Smoke tested.

### CODE REVIEW

**Review by paynejacob — DISMISSED** [review]

**Review by nickgerace — DISMISSED** [review]
Echoing with @paynejacob said

**Review by nickgerace — CHANGES_REQUESTED** [review]
I would reset and rebase. We do not want a merge commit in here.

**Review by paynejacob — APPROVED** [review]
can you rebase instead of merging?

**Review by paynejacob — CHANGES_REQUESTED** [review]
can you rebase instead of merging

**Pull request closed without merging**
