### PR TITLE
Add rancher-monitoring chart 0.0.1

### PR DESCRIPTION
**Pull request by thxCode**
This chart is used for Rancher monitoring. 
https://github.com/rancher/rancher/issues/15702

### CODE REVIEW

**Comment by thxCode** [comment]
@guangbochen ，please review this PR. FYI, @loganhz, @orangedeng , @aiwantaozi .

**Comment by guangbochen** [comment]
We need to discuss and implement how to `not-display` those `system-apps` on the catalog apps page, because the user is not expected to deploy those apps directly from the catalog page.

**Comment by orangedeng** [comment]
@guangbochen Like we did in 1.6, we can also create infrastructure services in system catalog. Why we can not deploy `system-apps` from catalog page?

**Comment by thxCode** [comment]
Close and republish to `rancher/system-charts` repo.

**Pull request closed without merging**
