### PR TITLE
update fleet to v0.3.6-rc4

### PR DESCRIPTION
**Pull request by kinarashah**
https://github.com/rancher/fleet/issues/424

### CODE REVIEW

**Review by nickgerace — CHANGES_REQUESTED** [review]
It appears that there's an index.yaml conflict

**Review by nickgerace — CHANGES_REQUESTED** [review]
I think we need to run make charts again even with the gitjob dep change

**Comment by kinarashah** [comment]
@nickgerace I did run `make charts` but got no changes. Comparing with https://github.com/rancher/charts/pull/1337/commits/049891f22b6d6dc5f9334b53c127cc7cfba32ad8, it's only fleet chart updates which were already included in the previous commit, so this looks expected?

**Comment by nickgerace** [comment]
I think we are good then!

**Review by nickgerace — APPROVED** [review]

**Pull request merged**
