### PR TITLE
[dev-v2.7] Add Longhorn 1.7.1 chart

### PR DESCRIPTION
**Pull request by mantissahz**
Release Longhorn v1.7.1 into Rancher 2.7

Longhorn https://github.com/longhorn/longhorn/issues/9346
Rancher https://github.com/rancher/rancher/issues/47182

cc @innobead @derekbit @rebeccazzzz @PhanLe1010 @khushboo-rancher @roger-ryao

### CODE REVIEW

**Comment by mantissahz** [comment]
Images are not mirrored because of some unauthorized issues https://github.com/rancher/image-mirror/actions/runs/10919337304/job/30306768564.
And we might need to request the EIO team to create a new repo for `longhorn-cli`

**Comment by PhanLe1010** [comment]
Looks like the chart doesn't actually use `longhorn-cli` image. We are good for now, I think

WDYT @mantissahz ?

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by mantissahz** [comment]
>Looks like the chart doesn't actually use longhorn-cli image. We are good for now, I think
WDYT @mantissahz ?

Yes, I agree with you @PhanLe1010.

**Comment by PhanLe1010** [comment]
@khushboo-rancher @roger-ryao Could you please help to test the merged chart at `dev-2.7` branch. Then signoff.After that, Rancher team release it into `release-v2.7` branch

**Comment by roger-ryao** [comment]
> @khushboo-rancher @roger-ryao Could you please help to test the merged chart at `dev-2.7` branch. Then signoff.After that, Rancher team release it into `release-v2.7` branch

Prerequisites:

Set the Concurrent Automatic Engine Upgrade Per Node Limit to a value greater than 0.
Rancher Prime: v2.7.15
Verify is passed as follows step

 - [x] Fresh installation
 - [x] Uninstallation
 - [x] Upgrade from `102.4.1+up1.6.2` -> `102.5.0+up1.7.1`
 - [x] Upgrade from `102.3.3+up1.5.5` -> `102.4.1+up1.6.2` -> `102.5.0+up1.7.1`
 
 **Note:**
We noticed that when installing Longhorn, the default value for `Container Registry for Rancher System Container Images` in `Rancher Prime` is enabled, with the value set to `registry.rancher.com`. However, all related Longhorn images are not synced to **registry.rancher.com**.

**Pull request merged**
