### PR TITLE
Update questions.yml

### LINKED ISSUE #268: OpenEBS Error: failed parsing --set data: key
I am getting the following error in the OpenEBS chart. I think it has something to do with the escaped commas in the questions.yaml file.

```
2019/10/11 20:08:54 [ERROR] AppController p-cm6sn/openebs [helm-controller] failed with : wait helm template failed. Error: failed parsing --set data: key "fd0\\" has no value (cannot end with ,)
: exit status 1
2019/10/11 20:08:54 [ERROR] AppController p-cm6sn/openebs [helm-controller] failed with : wait helm template failed. Error: failed parsing --set data: key "OpenEBS" has no value (cannot end with ,)
: exit status 1
```

### PR DESCRIPTION
**Pull request by clayrisser**
Fixed #268

### CODE REVIEW

**Comment by guangbochen** [comment]
@codejamninja can we please `rebase and push` against the `partner` branch, already changed the branch, thanks.

**Comment by codejamninja** [comment]
Sure

**Comment by codejamninja** [comment]
@guangbochen done

**Comment by guangbochen** [comment]
The latest folder is `v1.3.0`, you should update the `questions.yml` in that folder accordingly.

**Comment by kmova** [comment]
@codejamninja -- thanks for picking up on this PR. could you please help with resolving the conflict?

**Comment by codejamninja** [comment]
Sure

**Comment by codejamninja** [comment]
I'll have it done soon

**Comment by PennyScissors** [comment]
@clayrisser @guangbochen Hello, I'm working on cleaning up this repository, and noticed we lost track of this PR. Should I go ahead and close this, or is it still relevant? You can always submit a new one if you like.

**Comment by clayrisser** [comment]
@PennyScissors you can close it.

**Comment by PennyScissors** [comment]
@clayrisser Thanks for the confirmation, I'll go ahead and close it.

**Pull request closed without merging**
