### PR TITLE
[Logging v2] Split psp settings for logging

### PR DESCRIPTION
**Pull request by nickgerace**
Relevant issue: https://github.com/rancher/rancher/issues/31006
Original issue: https://github.com/rancher/rancher/issues/30771

### CODE REVIEW

**Comment by brendarearden** [comment]
so both the rbac psp and the global psp will be set to true?

**Comment by nickgerace** [comment]
@brendarearden: No, the `rbac.psp` will be set to false, which is the upstream default. The `global.psp` will be true because that only affects the overlay.

**Review by aiyengar2 — APPROVED** [review]
LGTM, as discussed offline this will not have any implications on an upgrade because `global.psp.enabled` is set to true by default. 

A user who did not have `rbac.psp.enabled=False` prior to this upgrade would only see new resources be created, and a user with `rbac.psp.enabled=True` prior to this upgrade would see no changes in the cluster.

The only way that resources would be lost on an upgrade is if is a user specifically override `global.psp.enabled=False` during the upgrade, which is expected. 

Confirmed that Rancher never automatically overrides `global.psp.enabled=False` as part of the UI.

**Review by brendarearden — APPROVED** [review]
LGTM

**Review by cbron — APPROVED** [review]

**Pull request merged**
