### PR TITLE
Release v2.5.12

### PR DESCRIPTION
**Pull request by SheilaghM**
https://github.com/rancher/rancher/issues/36184

### CODE REVIEW

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
@SheilaghM we need to run the following script in order to remove unnecessary file mode changes:

```diff
git diff -p --diff-filter=ACM \
    | grep -E '^(diff|old mode|new mode)' \
    | sed -e 's/^old/NEW/;s/^new/old/;s/^NEW/new/' \
    | git apply
```

Can you unstage your changes (`git reset HEAD~2`), run that command, and recommit your changes (`git add index.yaml assets; git commit -m "add index and assets"; git add charts; git commit -m "add charts"`)?

**Comment by SheilaghM** [comment]
@aiyengar2 unRCed backup-restore-operator and rancher-webhook, also ran this a few times:
```
git diff -p --diff-filter=ACM \
    | grep -E '^(diff|old mode|new mode)' \
    | sed -e 's/^old/NEW/;s/^new/old/;s/^NEW/new/' \
    | git apply
```    
All file mode changes should be good now.

**Review by PennyScissors — APPROVED** [review]
lgtm

**Comment by aiyengar2** [comment]
Following https://github.com/rancher/charts/pull/1664#issuecomment-997115583.

#### Checkpoint 0: LGTM

All the changes I saw are related to previously released charts placing the annotation in the wrong place alphabetically. This is not an issue.

#### Checkpoint 1: LGTM

#### Checkpoint 2a: LGTM

#### Checkpoint 2b: ERROR

The following newly released charts are missing required annotations:
```
...
Checking annotations on chart charts/rancher-alerting-drivers/rancher-alerting-drivers/1.0.301
WARN: Chart.yaml missing 'catalog.cattle.io/kube-version'
WARN: Chart.yaml missing 'catalog.cattle.io/upstream-version'
...
Checking annotations on chart charts/rancher-backup/rancher-backup/1.2.100+up1.2.1
WARN: Chart.yaml missing 'catalog.cattle.io/kube-version'
WARN: Chart.yaml missing 'catalog.cattle.io/upstream-version'
...
Checking annotations on chart charts/rancher-istio/rancher-istio/1.10.400
WARN: Chart.yaml missing 'catalog.cattle.io/kube-version'
WARN: Chart.yaml missing 'catalog.cattle.io/upstream-version'
...
Checking annotations on chart charts/rancher-logging/rancher-logging/3.15.0
WARN: Chart.yaml missing 'catalog.cattle.io/kube-version'
WARN: Chart.yaml missing 'catalog.cattle.io/upstream-version'
...
Checking annotations on chart charts/rancher-monitoring/rancher-monitoring-crd/16.6.1+up16.6.0
WARN: Chart.yaml missing 'catalog.cattle.io/rancher-version'
WARN: Chart.yaml missing 'catalog.cattle.io/kube-version'
WARN: Chart.yaml missing 'catalog.cattle.io/upstream-version'
...
Checking annotations on chart charts/rancher-vsphere-csi/rancher-vsphere-csi/2.3.1
WARN: Chart.yaml missing 'catalog.cattle.io/kube-version'
WARN: Chart.yaml missing 'catalog.cattle.io/upstream-version'
...
Checking annotations on chart charts/rancher-webhook/rancher-webhook/0.1.300+up0.1.3
WARN: Chart.yaml missing 'catalog.cattle.io/rancher-version'
WARN: Chart.yaml missing 'catalog.cattle.io/kube-version'
WARN: Chart.yaml missing 'catalog.cattle.io/upstream-version'
```

#### Checkpoint 3: LGTM

**Review by aiyengar2 — APPROVED** [review]

**Review by PennyScissors — APPROVED** [review]

**Review by brendarearden — APPROVED** [review]
LGTM

**Pull request merged**
