### PR TITLE
[stable/openebs] update charts to 1.0.0 release

### PR DESCRIPTION
**Pull request by ChandanSagar**
- Updated README
- Updated chart version
- Updated values.yaml
- Added node-disk-operator

Signed-off-by: ChandanSagar <chandan.pradhan@mayadata.io>

### CODE REVIEW

**Comment by prateekpandey14** [comment]
@guangbochen please take a look.

**Comment by ChandanSagar** [comment]
@guangbochen  : Hi,  Is there any changes required for this PR?

**Comment by ChandanSagar** [comment]
@guangbochen : Hi, made the changes requested, PTAL.

**Comment by guangbochen** [comment]
LGTM and merged, thanks.

**Pull request merged**
