### PR TITLE
Bump windows containers in rancher-monitoring and  rancher-logging charts

### PR DESCRIPTION
**Pull request by HarrisonWAffel**
## Problem
In June of 2023, [Microsoft announced the removal of foreign image layers from newly created windows containers](https://techcommunity.microsoft.com/t5/containers/announcing-removal-of-foreign-layers-from-windows-container/ba-p/3846833). 

Previously, Microsoft required that all base layers of Windows containers (`windows`, `servercore`, `nanoserver`, etc) be pulled from their managed container registry `mcr.microsoft.com`. This has implications for air-gapped registries, as clients will not have internet access and cannot contact `mcr.microsoft.com`. While there is a workaround to this behavior (proper configuration of the docker daemon before pushing windows images), it often leads to a bad UX for users who are not aware of this requirement. 

Now that foreign layers are not included by default, recreating the existing windows images used by the logging and monitoring charts will make loading air-gapped registries easier. This PR bumps the version of `windows_exporter-package` and windows `fluent-bit` to newly created versions which no longer contain foreign layers. 

`windows_exporter-package` has been bumped to `v0.0.5`. There is no difference in behavior between `v0.0.3` and `v0.0.5`

`fluent-bit` has been bumped to `v1.8.10`. There is no difference in behavior between `1.8.9` and `v1.8.10`. `v1.8.10` continues to use `fluent-bit` `v1.8.9`. A new issue was raised to investigate if we can bump this image to the `1.9` or `2.0` lines, https://github.com/rancher/rancher/issues/43740

### Manual Testing

I've deployed both charts to a test cluster running all supported versions of Windows. I did not notice any errors during the installation process, and confirmed that the new images no longer contain foreign layers. 

### Automated Testing
As this PR just bumps images which include no changes in behavior no automated testing has been added

### Regressions Considerations
The images this PR introduces are functionally identical to the current images, they just contain different image layers. A regression is highly unlikely 

## Backporting considerations
This change will need to be back ported to 2.7 and 2.8

### CODE REVIEW

**Review by thatmidwesterncoder — APPROVED** [review]

**Review by aiyengar2 — APPROVED** [review]

**Comment by nicholasSUSE** [comment]
Hello @HarrisonWAffel 
Is this Pull Request still relevant?
Can I close it?

**Comment by HarrisonWAffel** [comment]
@nicholasSUSE iiuc it was blocked by https://github.com/rancher/charts/pull/3412, since that has been merged I will need to come back to this PR and confirm it has solved my issue. Not stale, aiming to get to this again soon

**Comment by nicholasSUSE** [comment]
> @nicholasSUSE iiuc it was blocked by #3412, since that has been merged I will need to come back to this PR and confirm it has solved my issue. Not stale, aiming to get to this again soon

Ok thank you for your response.

**Comment by HarrisonWAffel** [comment]
Closing this PR as ongoing work around https://github.com/rancher/windows/issues/223 will likely invalidate the monitoring specific changes made here

**Pull request closed without merging**
