### PR TITLE
[dev-v2.9] Add Longhorn 1.7.1 chart

### PR DESCRIPTION
**Pull request by mantissahz**
Release Longhorn v1.7.1 into Rancher 2.9

Longhorn https://github.com/longhorn/longhorn/issues/9346
Rancher https://github.com/rancher/rancher/issues/47184

cc @innobead @derekbit @rebeccazzzz @PhanLe1010 @khushboo-rancher @roger-ryao

### CODE REVIEW

**Comment by mantissahz** [comment]
Images are not mirrored because of some unauthorized issues https://github.com/rancher/image-mirror/actions/runs/10919337304/job/30306768564.
And we might need to request the EIO team to create a new repo for `longhorn-cli`

**Comment by PhanLe1010** [comment]
> Images are not mirrored because of some unauthorized issues https://github.com/rancher/image-mirror/actions/runs/10919337304/job/30306768564. And we might need to request the EIO team to create a new repo for `longhorn-cli`

Same as https://github.com/rancher/charts/pull/4470#issuecomment-2369729209

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Comment by PhanLe1010** [comment]
@khushboo-rancher @roger-ryao Could you please help to test the merged chart at `dev-2.9` branch. Then signoff.After that, Rancher team release it into `release-v2.9` branch

**Comment by roger-ryao** [comment]
> @khushboo-rancher @roger-ryao Could you please help to test the merged chart at `dev-2.9` branch. Then signoff.After that, Rancher team release it into `release-v2.9` branch

Hi @PhanLe1010 , @khushboo-rancher 

Prerequisites:
- Set the Concurrent Automatic Engine Upgrade Per Node Limit to a value greater than 0.
- Rancher : `v2.9.2`

Verify is passed as follows step
- [x] Fresh installation
- [x] Uninstallation
- [x] Upgrade from `104.0.0+up1.5.5` -> `104.1.0+up1.6.2` -> `104.2.0+up1.7.1`
- [x] Upgrade from `104.1.0+up1.6.2` -> `104.2.0+up1.7.1`

**Pull request merged**
