### PR TITLE
Bump gke-operator to v1.1.1-rc5

### PR DESCRIPTION
**Pull request by cmurphy**
https://github.com/rancher/rancher/issues/33241

### CODE REVIEW

**Review by rmweir — APPROVED** [review]
LGTM

**Review by thedadams — CHANGES_REQUESTED** [review]
There should also be changes to `index.yaml`. Perhaps deleting it and running `make charts` will create the change.

**Comment by cmurphy** [comment]
I don't understand why it didn't just update when I originally ran `make charts`...

**Review by thedadams — APPROVED** [review]

**Review by rmweir — APPROVED** [review]
LGTM

**Review by cbron — APPROVED** [review]
lgtm, as we are splitting GKE across versions and keeping 1.1 on 2.6. This will likely get bumped soon for base image change.

**Pull request merged**
